test: remove async done
opensumi/core pull request #1002
Opened 2022-05-10 12:41 UTC by bytemain

### Types

- [x] ⏱ Tests

### Background or solution

### Changelog

2022-05-10 12:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/opensumi/core?pullRequest=1002) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/opensumi/core?pullRequest=1002) before we can accept your contribution.<br/><hr/>**Artin** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/opensumi/core?pullRequest=1002) it.</sub>

2022-05-13 08:08 UTC, erha19 requested changes
另外试了一下，目前运行某个包内测试的脚本貌似不能用了，例如 `npm run test:module -- --module=utils `

2022-05-13 08:08 UTC, erha19 commented on packages/extension/__tests__/browser/main.thread.workspace.test.ts
> +    await sleep(300);
这里为啥没用原来的 await，而用 sleep 处理？

2022-05-13 08:08 UTC, erha19 commented on packages/extension/__tests__/hosted/api/vscode/ext.host.comments.test.ts
> +      expect(reaction.label).toBe('点赞');
顺便把这个中文也改了吧。

2022-05-13 08:10 UTC, bytemain commented on packages/extension/__tests__/browser/main.thread.workspace.test.ts
> +    await sleep(300);
原来的那一句 initialize 提到顶部了，这里的 sleep 是额外加的。

2022-05-13 09:35 UTC, Aaaaash approved these changes
LGTM

2022-05-13 09:38 UTC, erha19 approved these changes

2022-05-13 09:39 UTC, merged