feat: extension management sync & styles
opensumi/core pull request #1005
Opened 2022-05-10 16:36 UTC by songhn233

### Types

- [x] 🎉 New Features
- [x] 🐛 Bug Fixes

### Background or solution

Related issues: https://github.com/opensumi/core/issues/747 https://github.com/opensumi/core/issues/750

目前解决的问题

- 插件详情页按钮样式
- 为 `<Extension />` 添加 type，在 init 时扩展市场可以正确判断安装、已安装与更新状态
- 修复部分 lint warning

这个改动复杂度比想象中大，所有有些疑问的点想先讨论下

- 发现额外的问题
  - 搜索栏切换到 “已安装插件” 后依然搜索市场中的插件
  - 插件有部分能力没有实现，包括激活、禁用、卸载
- browser 侧的 installedExtensions property 是通过 `getExtensionInstances` computed ，实际调用的 extensionMap 并没有在增删插件时更新，是通过 initExtensionMetaData 从 node 侧的 nodeExtensionService 初始化时读取的，要实现同步的话这块改动可能比较大
- 对于更新来说，可能还需要增加额外的逻辑，在安装前首先卸载相同 extensionId 的插件，保持插件唯一。另外项目本身也会在 `tools/extensions` 安装插件，和 `~/.sumi/extensions` 中 extensionId 相同时，更新应该操作哪一侧

2022-05-10 16:37 UTC, songhn233 commented
/cc @erha19 @Aaaaash

2022-05-11 03:10 UTC, erha19 commented
目前使用的插件市场为我们外部针对 OpenVSX 体系做的一个示例性质的插件市场，整体功能比较简陋，不过本身前端实现需要的接口应该都是有实现的。

> 搜索栏切换到 “已安装插件” 后依然搜索市场中的插件

这个应该就是逻辑问题，需要根据 Tab 选项卡调整一下展示内容

> 插件有部分能力没有实现，包括激活、禁用、卸载

这个应该是有实现过接口的 @hacke2 可以帮忙指个路

> browser 侧的 installedExtensions property 是通过 getExtensionInstances computed ，实际调用的 extensionMap 并没有在增删插件时更新，是通过 initExtensionMetaData 从 node 侧的 nodeExtensionService 初始化时读取的，要实现同步的话这块改动可能比较大

这个应该是要修改的，本身实现比较简陋。

> 对于更新来说，可能还需要增加额外的逻辑，在安装前首先卸载相同 extensionId 的插件，保持插件唯一。另外项目本身也会在 tools/extensions 安装插件，和 ~/.sumi/extensions 中 extensionId 相同时，更新应该操作哪一侧

实际上插件在加载时会去对插件版本做判断，只会取一个最新版本的同名插件进行加载，所以更新的逻辑应该只需要下周新的插件下来就行了，不过需要刷新重启一下 IDE，即更新情况下 -> 提示用户需要重启 ，新安装情况下 -> 动态激活

@hacke2 也帮忙看看

2022-05-11 03:48 UTC, hacke2 commented
@songhn233 我们内部因为最开始就是用的自建的插件市场，所以插件市场模块一直用的是内部模块，整个插件市场的功能还是比较多的，如果和目前 VS Code 插件市场面板相比，差的功能就更多了（比如最新的安装 pre-release 插件的功能）

说回来你的问题，如果要需要更新插件进程的话，参考下面代码调用：

```ts
@Autowired(AbstractExtensionManagementService)
 private readonly kaitianExtensionManagerService: AbstractExtensionManagementService;

await this.kaitianExtensionManagerService.postChangedExtension({
  upgrade: false,
  extensionPath: path,
  isBuiltin,
});
```

这个方法可以更新插件进程里的信息

更新插件确实需要先删除掉旧插件，再安装新插件，还需要判断安装插件后是否需要重启（如果这个插件被激活有副作用就得重启），如果不需要重启还是需要调用上述方法更新插件进程示例。

关于禁用、启用、按照工作空间禁用启用，内部都是有的，都是维护一个 storage 来存储这类的信息，具体代码位置在 https://github.com/opensumi/core/blob/main/packages/extension/src/browser/extension-instance-management.ts#L97
这里只负责读，插件市场模块负责写或监听它内容的变更。

我们之后计划将我们插件市场对外开放，并且将插件市场模块能力也对外，理想的情况是我们可以内置几个插件市场的 adapter，支持我们的插件市场和 openvsx，甚至支持链接 vscode marketplace？反正会把插件市场数据请求这块抽象一下，每次接入新的插件市场只用适配数据获取这一块，不用重新搞一个 extension-manager 这样有前端有后端的模块

2022-05-11 08:17 UTC, erha19 commented
@songhn233 rebase 一下 main 分支，如果这个分支已经完成了提到 issue 内的问题，可以另外再开 PR 和 issue 实现剩余部分，尽量保障 PR 的精炼，不要一个 PR 里实现太多内容吧。

2022-05-11 09:55 UTC, songhn233 commented
> 可以另外再开 PR 和 issue 实现剩余部分，尽量保障 PR 的精炼，不要一个 PR 里实现太多内容吧。

@erha19 好的，那这个 PR 只解决插件市场 tab 的显示问题

2022-05-11 10:07 UTC, erha19 requested changes
贴一下修改前和修改后的对比图吧

2022-05-11 10:07 UTC, erha19 commented on packages/extension-manager/src/browser/extension/index.tsx
> +        e.stopPropagation();
这里缩进增加了，是格式化问题吗？

2022-05-11 10:23 UTC, songhn233 commented on packages/extension-manager/src/browser/extension/index.tsx
> +        e.stopPropagation();
https://github.com/opensumi/core/blob/fe86148d84c18286a1ab540b99b5bcdc67872733/packages/extension-manager/src/browser/extension/index.tsx#L23-L24

因为增加 type 以后多了一个换行

2022-05-15 12:01 UTC, erha19 approved these changes

2022-05-15 12:02 UTC, merged