fix: add missing breadcrumb
opensumi/core pull request #1013
Opened 2022-05-11 08:06 UTC by iamxukai

### Types

- [x] 🐛 Bug Fixes

### Background or solution
closes #905 #992 

### Changelog

2022-05-11 09:26 UTC, erha19 requested changes

2022-05-11 09:26 UTC, erha19 commented on packages/editor/src/browser/breadcrumb/default.ts
> +import { USER_STORAGE_SCHEME } from '@opensumi/ide-preferences';
这里不能从 `@opensumi/ide-preferences` 引入 USER_STORAGE_SCHEME，本身 preference 模块已经依赖了 `@opensumi/ide-editor` ，这样会出现循环引用问题。

这里建议可以把 USER_STORAGE_SCHEME 从 preference 模块提到 `@opensumi/ide-core-common` 里面，写一个类似 `SUPPORTED_SCHEMES` 的数组以及 USER_STORAGE_SCHEME，FILE_SCHEME（位于 [file-scheme/src/common/index.ts#L3](https://github.com/opensumi/core/blob/8a433729452ba8397a553e9a886796b467774106/packages/file-scheme/src/common/index.ts#L3)），都放到公共模块去维护

2022-05-11 15:39 UTC, iamxukai commented on packages/editor/src/browser/breadcrumb/default.ts
> +import { USER_STORAGE_SCHEME } from '@opensumi/ide-preferences';
这里有个文件 [netwrok.ts](https://github.com/opensumi/core/blob/8a433729452ba8397a553e9a886796b467774106/packages/core-common/src/network.ts)， 里面有个file ，而且`scheme` 是要改成`schema` ？

2022-05-11 17:29 UTC, erha19 commented on packages/editor/src/browser/breadcrumb/default.ts
> +import { USER_STORAGE_SCHEME } from '@opensumi/ide-preferences';
正确的拼写应该是 `scheme`, `schemas` 感觉是拼写错误，可以一起改掉，统一在 [netwrok.ts](https://github.com/opensumi/core/blob/8a433729452ba8397a553e9a886796b467774106/packages/core-common/src/network.ts) 这个文件里面取感觉就可以了

2022-05-13 01:51 UTC, erha19 approved these changes

2022-05-13 01:51 UTC, merged