Feat/trace terminal retrox
opensumi/core pull request #1014
Opened 2022-05-11 09:12 UTC by life2015

### Types

增加对Terminal性能的监控

- [ ] 🎉 New Features
- [ ] 🐛 Bug Fixes
- [x] 📚 Documentation Changes
- [ ] 💄 Code Style Changes
- [x] 💄 Style Changes
- [ ] 🪚 Refactors

### Background or solution

增加了一些IPC监控，以及补充了一些旧代码的注释。

### Changelog

2022-05-11 09:12 UTC, life2015 commented
/publish

2022-05-13 02:00 UTC, erha19 commented on packages/terminal-next/src/browser/terminal.addon.ts
> +          // connection.onData 的时候 对lastInputTime进行差值运算，统计最后一次输入到收到回复的时间间隔
一个小建议，中英文注释，在英文左右加个空格格式会标准一些

2022-05-16 06:07 UTC, life2015 commented on packages/terminal-next/src/browser/terminal.addon.ts
> +          // connection.onData 的时候 对lastInputTime进行差值运算，统计最后一次输入到收到回复的时间间隔
done

2022-05-16 08:36 UTC, erha19 commented on packages/terminal-next/src/browser/terminal.addon.ts
> +          // connection.onData 的时候 对lastInputTime进行差值运算，统计最后一次输入到收到回复的时间间隔
你好像就改了一个地方，这个 PR 里面还有好几个，顺手改一下吧 ... @life2015

2022-05-17 09:32 UTC, erha19 requested changes

2022-05-17 11:22 UTC, life2015 commented on packages/terminal-next/src/node/pty.manager.ts
> +        this.logger.log(`PtyServiceManager.onData: ${timeDiff}ms data: ${resString.substring(0, 100)}`);
这里只会在write输入内容里面包含 "=" 字符的时候统计，不会对所有数据做记录，因为在测试的过程中偶现IPC通信太长的问题，因此在这里做一个埋点。

2022-05-17 11:23 UTC, life2015 commented on packages/terminal-next/src/node/pty.manager.ts
> +// 记录终端输入到输出的时间戳，主要是用于统计Pty处理 + IDE <--> PTY的IPC 耗时
PTY吧..

2022-05-18 06:32 UTC, erha19 commented on packages/terminal-next/src/node/pty.manager.ts
> +// 记录终端输入到输出的时间戳，主要是用于统计Pty处理 + IDE <--> PTY的IPC 耗时
我改掉了

2022-05-18 07:25 UTC, erha19 approved these changes

2022-05-18 10:16 UTC, merged