fix: wait for all preference provider ready
opensumi/core pull request #1020
Opened 2022-05-12 14:03 UTC by Aaaaash

### Types

- [x] 🐛 Bug Fixes

### Background or solution

### Changelog

2022-05-12 14:03 UTC, Aaaaash commented
/publish

2022-05-13 02:09 UTC, erha19 requested changes

2022-05-13 02:09 UTC, erha19 commented on packages/core-browser/src/preferences/preference-service.ts
> +    // return this.doResolveWithOutCache<T>(preferenceName, resourceUri, untilScope, language);
多余的测试代码删了吧

2022-05-16 06:37 UTC, Aaaaash commented
/publish

2022-05-16 06:39 UTC, hacke2 commented
这个修复的是啥问题？

2022-05-17 01:42 UTC, erha19 approved these changes

2022-05-17 01:43 UTC, merged