style: use color tokens to replace color values
opensumi/core pull request #1022
Opened 2022-05-13 02:28 UTC by iamxukai

### Types

- [x] 💄 Style Changes

### Background or solution
closes #993 

### Changelog

2022-05-13 02:34 UTC, erha19 requested changes
补充一下 Changelog 信息以及样式上的修改可以在描述里面补充一下修改前后的对比图

2022-05-13 02:34 UTC, erha19 commented on packages/theme/src/common/color-tokens/editor.ts
> +export const editorSuccessForeground = registerColor(
这个色值如果是为了给 notification 面板做样式 TOKEN 使用，建议直接在 notification.ts 里面定义，而且这里的国际化文案有一些问题

2022-05-13 02:34 UTC, erha19 commented on packages/theme/src/common/color-tokens/editor.ts
> +export const editorSuccessBorder = registerColor(
这里也一样

2022-05-13 02:34 UTC, erha19 commented on packages/theme/src/common/color-tokens/notification.ts
> +export const NOTIFICATIONS_SEPARATOR_BACKGROUND = registerColor(
这里注册的 Token 貌似没有看到使用的地方？

2022-05-13 02:47 UTC, iamxukai commented on packages/theme/src/common/color-tokens/notification.ts
> +export const NOTIFICATIONS_SEPARATOR_BACKGROUND = registerColor(
[这里](https://github.com/opensumi/core/pull/1022/commits/20308e43b6722b8a076c3dcac7bde321ade2640d#diff-ca76b10fd84904d6f3068ee171ee0bb71a01b38759825ea790b038cbbc6c8b67R27)

2022-05-15 11:46 UTC, erha19 requested changes

2022-05-15 11:46 UTC, erha19 commented on packages/theme/src/common/color-tokens/notification.ts
> +export const NOTIFICATIONS_SEPARATOR_BACKGROUND = registerColor(
这里看了一下只是把这个值当做一个变量在使用，实际上 `.../color-tokens` 目录下的色值 Token 是有潜规则的，不能这么随意去注册，默认的色值是从 vscode 内的 [theme.ts](https://github.com/microsoft/vscode/blob/8a9b9c3a1965d787717cf08e569b153acc2c0b06/src/vs/workbench/common/theme.ts) 文件内容提取，代表着 VS Code 的默认主题 Token，用于适配 VS Code 提供的插件

而自定义的 Token 应该放在 custom 目录下去独立管理，所以你这里更合适的方式应该是单独在 custom 目录内去声明该变量值

2022-05-15 12:39 UTC, iamxukai commented
@erha19 
那么`NOTIFICATIONS_SUCCESS_ICON_FOREGROUND` 怎么办呢，在`main` 分支的 [modal.ts](https://github.com/opensumi/core/blob/main/packages/theme/src/common/color-tokens/custom/modal.ts#L37) 中存在，在vs code的 [theme.ts](https://github.com/microsoft/vscode/blob/8a9b9c3a1965d787717cf08e569b153acc2c0b06/src/vs/workbench/common/theme.ts#L851) 文件中，这个是不存在的。

2022-05-15 12:43 UTC, erha19 commented
> @erha19 那么`NOTIFICATIONS_SUCCESS_ICON_FOREGROUND` 怎么办呢，在`main` 分支的 [modal.ts](https://github.com/opensumi/core/blob/main/packages/theme/src/common/color-tokens/custom/modal.ts#L37) 中存在，在vs code的 [theme.ts](https://github.com/microsoft/vscode/blob/8a9b9c3a1965d787717cf08e569b153acc2c0b06/src/vs/workbench/common/theme.ts#L851) 文件中，这个是不存在的。

应该挪到 `custom` 目录下面的 [notification.ts](https://github.com/opensumi/core/blob/80c8731fe4806871b70846c862de7debfa1a4303/packages/theme/src/common/color-tokens/custom/notification.ts) 去定义

2022-05-17 01:55 UTC, erha19 requested changes

2022-05-17 01:55 UTC, erha19 commented on packages/theme/src/common/color-tokens/custom/modal.ts
> +  { light: ktNotificationsSuccessIconForeground, dark: ktNotificationsSuccessIconForeground, hc: null },
这里的 `ktModalSuccessIconForeground` 和上面的 `ktModalSeparatorBackground` 本身就是自定义的 Token，其实没必要再通过另外的  `ktNotificationsSuccessIconForeground`, `ktTextSeparatorBackground` 变量去代理其默认值配置，尽量减少冗余的 Token 值，这些值最终都会挂载在页面的 root 下的。

这里建议就按原先 ktModalSuccessIconForeground 的默认色值进行设置就行了。

2022-05-17 06:48 UTC, erha19 approved these changes

2022-05-17 06:51 UTC, merged