feat: add unregister item
opensumi/core pull request #1058
Opened 2022-05-18 08:41 UTC by iamxukai

### Types

- [x] 🎉 New Features

### Background or solution
related: #1042 

### Changelog
注册菜单项用的是`registerMenuItem`函数，取消注册使用`unRegisterMenuItem`函数，所以我在 tab-bar-toolbar.tsx 中补充了一下，不确定能不能解决问题。

2022-05-19 03:23 UTC, bytemain submitted a review, later dismissed

2022-05-20 08:14 UTC, erha19 requested changes

2022-05-20 08:14 UTC, erha19 commented on packages/core-browser/src/layout/accordion/tab-bar-toolbar.tsx
> +  unRegisterItem(menuItemId: string) {
unregister 一般作为完整单词，不需要在 R 的位置大写

2022-05-24 07:57 UTC, erha19 approved these changes

2022-05-24 07:57 UTC, merged