WIP: chore: remove registry constant in fe
opensumi/core pull request #1064
Opened 2022-05-19 08:49 UTC by iamxukai

### Types
- [x] 🧹 Chores

### Background or solution

### Changelog

2022-05-24 07:45 UTC, erha19 requested changes

2022-05-24 07:45 UTC, erha19 commented on packages/extension-manager/src/browser/vsx-extension.service.ts
> +    this.openVSXRegistry = await this.backService.getOpenVSXRegistry();
这里是不是可以判断一下 `this.openVSXRegistry` 不存在时再去重新获取一下 registry，不然这里每次激活都会调用一次

2022-05-24 07:46 UTC, erha19 commented
另外 ChangeLog 需要写一下

2022-05-24 12:06 UTC, iamxukai commented on packages/extension-manager/src/browser/vsx-extension.service.ts
> +    this.openVSXRegistry = await this.backService.getOpenVSXRegistry();
我或许可以在 [vsx-extension.contribution.ts #L37](https://github.com/opensumi/core/blob/main/packages/extension-manager/src/browser/vsx-extension.contribution.ts#L37) 这里 判断有没有源

2022-05-25 03:38 UTC, erha19 commented on packages/extension-manager/src/browser/vsx-extension.service.ts
> +    this.openVSXRegistry = await this.backService.getOpenVSXRegistry();
一般修改源的操作比较低频，比较建议的方式是通过 `preferenceService.onPrefernceChange` 的方式去监听，这里在每次切换时就去请求一次有点多余。

2022-05-25 06:24 UTC, iamxukai commented on packages/extension-manager/src/browser/vsx-extension.service.ts
> +    this.openVSXRegistry = await this.backService.getOpenVSXRegistry();
@erha19 
我的第三次commit，添加了是否需要去请求的判断，你看看可以吗？

2022-05-25 06:25 UTC, erha19 approved these changes

2022-05-25 06:28 UTC, merged