feat: add pty line cache max length
opensumi/core pull request #1065
Opened 2022-05-19 09:58 UTC by life2015

### Types

终端 PTY 缓存数据的时候只存放前1024个字符，因为正常情况下也不会超过1024个，如果超过的话，基本上是用户误操作导致的cat 二进制文件或者其他未知问题，比如说之前npm会有一直往终端输出不可见内容的问题，导致打爆cache。

通过缓存限制在每行1024字符来避免潜在的单行字符量太大导致内存泄漏问题。

- [x] 🐛 Bug Fixes

2022-05-20 07:11 UTC, erha19 requested changes

2022-05-20 07:11 UTC, erha19 commented on packages/terminal-next/src/node/pty.proxy.ts
> +        cache?.add(e.slice(0, 1024));
这个缓存数据应该是最后 1024 个数据吧？这样好像会一直是前面 1024 个数据？

2022-05-20 07:11 UTC, erha19 commented on packages/terminal-next/src/node/pty.proxy.ts
> +        cache?.add(e.slice(0, 1024));
建议把这个值改成配置项或变量

2022-05-20 10:53 UTC, life2015 commented on packages/terminal-next/src/node/pty.proxy.ts
> +        cache?.add(e.slice(0, 1024));
终端的cache是按照最后的n个（目前是100）pty onData来算的，每一次onData我会算是一个line（虽然这个没有xterm buffer来的严谨，但是也差不多可以解决目前的问题）。而这个变更中的设置是限制了在缓存的时候单次onData的最大长度，这个本身是一个防御性的代码，用1024长度硬编码即可，做成配置反而会导致配置太多让人摸不着头脑。

2022-05-23 02:36 UTC, erha19 approved these changes

2022-05-23 02:36 UTC, merged