refactor: simplify deps
opensumi/core pull request #1102
Opened 2022-05-24 14:19 UTC by bytemain

### Types

- [x] 🪚 Refactors

### Background or solution

### Changelog

2022-05-25 01:58 UTC, erha19 requested changes

2022-05-25 01:58 UTC, erha19 commented on packages/debug/src/browser/editor/debug-hover-tree.model.service.ts
> +import { pSeries } from '@opensumi/ide-utils/lib/promises';
之前我考虑过沿用我们原来的规则，所有依赖都通过 core-browser -> core-common -> utils 引入，即这里的 pSeries 直接从 @opensumi/ide-core-browser 引入，本身这个模块内没有声明对 @opensumi/ide-utils 的依赖，这样写感觉直接依赖了隐式依赖

2022-05-25 04:04 UTC, bytemain commented
我们能不能自己维护一些这些 utils 的包，因为其他的代码库也想用。

p-series 最新版是 esm 的，没法直接使用，
p-series ^2 版本有俩依赖。。。

2022-06-02 06:22 UTC, erha19 commented
> 我们能不能自己维护一些这些 utils 的包，因为其他的代码库也想用。
> 
> p-series 最新版是 esm 的，没法直接使用， p-series ^2 版本有俩依赖。。。

如果是复用不高的依赖，感觉可以作为模块自己的依赖去引入

2022-06-20 09:59 UTC, erha19 approved these changes

2022-06-20 10:00 UTC, merged