fix: close terminal after type exit
opensumi/core pull request #1122
Opened 2022-05-26 09:03 UTC by erha19

### Types

- [x] 🐛 Bug Fixes

### Background or solution

close #1107 

https://user-images.githubusercontent.com/9823838/170456030-2668a962-2529-4712-93a9-6307f2d4fdc5.mp4

### Changelog

close terminal after type exit

2022-05-26 09:25 UTC, bytemain requested changes

2022-05-26 09:25 UTC, bytemain commented on packages/terminal-next/src/browser/terminal.controller.ts
> +        this.terminalView.removeWidget(client.id);
我记得我们有一些逻辑是展示 Client 报错的，建议判断一下这个 error 是什么再做关闭操作。
可以看看下面这个 _onDidCloseTerminal 的 Emitter 做了什么

2022-05-26 09:26 UTC, bytemain commented on packages/terminal-next/src/browser/terminal.controller.ts
> +        this.terminalView.removeWidget(client.id);
如果用户是主动关闭，就直接关了。

2022-05-26 09:30 UTC, erha19 commented on packages/terminal-next/src/browser/terminal.controller.ts
> +        this.terminalView.removeWidget(client.id);
判断一下 `error.code === 0` ? 这个 code 貌似就是正常退出的状态码

2022-05-26 09:39 UTC, Aaaaash commented on packages/terminal-next/src/browser/terminal.controller.ts
> +        this.terminalView.removeWidget(client.id);
展示报错理论上来讲应该是连接失败或者意外断开这种情况吧，pty 进程退出应该不算.. 否则有些进程退出 code 是 127，那这里非但不能去掉，还得切换成 error 状态，不太合理了

2022-05-26 09:41 UTC, bytemain commented on packages/terminal-next/src/browser/terminal.controller.ts
> +        this.terminalView.removeWidget(client.id);
看起来这里确实不需要再处理了，上层好像已经能判断是 error 还是 exit 了
[image](https://user-images.githubusercontent.com/13938334/170462470-fe586d73-e4c2-4076-927f-6b3101ac85ab.png)

2022-05-26 09:41 UTC, bytemain approved these changes

2022-05-26 09:46 UTC, yantze commented
在这个分支试了一下，虽然可以退出，但 #1107 提到的 terminal 实例还是没有销毁

<img width="775" alt="image" src="https://user-images.githubusercontent.com/2226423/170463373-e1159010-33d2-4175-92b0-071d1305de99.png">

2022-05-26 15:42 UTC, erha19 commented on packages/extension/src/hosted/api/vscode/ext.host.terminal.ts
> +      if (info.id.includes(TERMINAL_ID_SEPARATOR)) {
插件 JavaScript Debug Terminal 出现多个 terminal 实例的问题在这里，插件进程生成的 ID 在前端被拼接为 `${clientId}${TERMINAL_ID_SEPARATOR}${terminalId}` 的结构，后面所有 `|` 都换成 `TERMINAL_ID_SEPARATOR` 变量代替，周知 @bytemain @Aaaaash @life2015

2022-05-26 16:15 UTC, erha19 commented on packages/extension/src/hosted/api/vscode/ext.host.terminal.ts
> +    if (id.includes(TERMINAL_ID_SEPARATOR)) {
改到这里了，解决前端拼接导致的 TerminalId 查询不到的问题

2022-05-27 02:59 UTC, Aaaaash approved these changes

2022-05-27 03:00 UTC, life2015 commented
LGTM

2022-05-27 04:02 UTC, merged