fix: incorrect terminal type when OS is Windows
opensumi/core pull request #1164
Opened 2022-06-02 03:11 UTC by situ2001

### Types

- [x] 🐛 Bug Fixes

### Background

OS: **Windows**11 22000.708

When using opensumi(web, not electron) on Windows, terminal type is wrong.

<img width="780" alt="041b406f7cd24d67c6bd0832441c9a2" src="https://user-images.githubusercontent.com/28241963/171544807-569b8e66-188c-45de-82a0-70896fcd554b.png">

<img width="797" alt="b3fbe030d895e86f4d6fcf2603276ac" src="https://user-images.githubusercontent.com/28241963/171544814-58c81ed8-62af-4cea-aee3-c6353b0fe808.png">

After fixing it.

<img width="758" alt="d5e2219fd87d04e8a1db26c9a9c32d7" src="https://user-images.githubusercontent.com/28241963/171544832-659aafe1-3f38-4d56-ad03-4f822eac9734.png">

### Changelog

Just as the title shows.

2022-06-02 03:38 UTC, bytemain submitted a review, later dismissed

2022-06-02 03:39 UTC, bytemain commented
好像不太对，应该需要判断一下后端的 platform 类型再注入这些设置项。

2022-06-02 06:22 UTC, situ2001 commented
> 好像不太对，应该需要判断一下后端的 platform 类型再注入这些设置项。 可以看看：[getOs()](https://github.com/opensumi/core/blob/538c9acc691d81d2683d7d3d87764400555c1aef/packages/terminal-next/src/node/terminal.service.client.ts#L207)

I will take a look into it.

2022-06-02 06:50 UTC, bytemain requested changes

2022-06-02 06:50 UTC, bytemain commented on packages/terminal-next/src/browser/contribution/terminal.preference.ts
> +          terminalPreferenceSchema.properties['terminal.type'].enum = ['git-bash', 'powershell', 'cmd', 'default'];
不推荐这样改哈~ 这样是因为我们设计上的失误，没有 freeze 掉这个注入的 terminalPreferenceSchema，所以这里直接改了 enum 的话是直接改了底层的引用，导致代码还是按预期的 work 了。

推荐使用更新一个新的 schema 的方式来做，[PreferenceSchemaProvider.setSchema](https://github.com/opensumi/core/blob/58b998d9e1f721928f576579f16ded46b7505e84/packages/core-browser/src/preferences/preference-contribution.ts#L274)

参考这样：
<img width="1306" alt="CleanShot 2022-06-02 at 14 49 52@2x" src="https://user-images.githubusercontent.com/13938334/171570201-e53994cb-fead-49da-8834-402b15149f3c.png">

2022-06-02 07:21 UTC, situ2001 commented on packages/terminal-next/src/browser/contribution/terminal.preference.ts
> +          terminalPreferenceSchema.properties['terminal.type'].enum = ['git-bash', 'powershell', 'cmd', 'default'];
谢谢提示 已经修改👍

2022-06-02 07:25 UTC, bytemain commented on packages/terminal-next/src/browser/contribution/terminal.preference.ts
> +    const TERMINAL_TYPE = 'terminal.type';
这个常量可以放到一个固定的文件里（比如 packages/terminal-next/src/common/preference.ts），然后最好也可以把用到的地方都修改成这个常量。

2022-06-02 07:57 UTC, situ2001 commented on packages/terminal-next/src/browser/contribution/terminal.preference.ts
> +    const TERMINAL_TYPE = 'terminal.type';
Done.

2022-06-02 08:08 UTC, situ2001 commented on packages/terminal-next/src/browser/contribution/terminal.preference.ts
> +    const TERMINAL_TYPE = 'terminal.type';
好的 已revert
Thanks

2022-06-07 04:04 UTC, bytemain approved these changes

2022-06-07 04:05 UTC, merged