refactor: unified search ability
opensumi/core pull request #1189
Opened 2022-06-09 15:12 UTC by bytemain

### Types

- [x] 🪚 Refactors

### Background or solution

### Changelog

2022-06-15 09:00 UTC, erha19 requested changes
补充一下 BK 文档 https://github.com/opensumi/core/wiki/%E9%9B%86%E6%88%90%E6%8E%A5%E5%85%A5-Breaking-Changes

2022-06-15 09:32 UTC, bytemain commented
已经更新 Breaking Change: https://github.com/opensumi/core/wiki/%E9%9B%86%E6%88%90%E6%8E%A5%E5%85%A5-Breaking-Changes

2022-06-16 02:16 UTC, erha19 commented
@bytemain 冲突了，同时补充一下 Changelog 信息吧

2022-07-22 12:16 UTC, bytemain commented
2.x 系列暂不考虑这个 PR

2022-07-22 12:16 UTC, closed without merging