fix: set default terminal type
opensumi/core pull request #1194
Opened 2022-06-10 09:28 UTC by erha19

### Types

- [x] 🐛 Bug Fixes

### Background or solution

close #1165 

### Changelog

fix set default terminal type features

2022-06-13 03:58 UTC, bytemain requested changes

2022-06-13 03:58 UTC, bytemain commented on packages/terminal-next/src/browser/contribution/terminal.command.ts
> +    // 当存在工作区配置时，优先更新工作区中的配置
封装成一个函数放在 preferenceService 里面吧

2022-06-20 07:42 UTC, bytemain commented on packages/terminal-next/src/browser/contribution/terminal.command.ts
> +    this.preference.update('terminal.type', type);
好像这个值有一个 constants，可以直接引用那个

2022-06-20 07:50 UTC, erha19 commented on packages/terminal-next/src/browser/contribution/terminal.command.ts
> +    this.preference.update('terminal.type', type);
加了个公共的变量 `TERMINAL_PREFERENCES.TERMINAL_TYPE`

2022-06-20 08:31 UTC, bytemain requested changes

2022-06-20 08:36 UTC, bytemain submitted a review, later dismissed

2022-06-20 11:20 UTC, bytemain approved these changes

2022-06-20 15:31 UTC, merged