feat: dialog support custom props for overlay
opensumi/core pull request #1215
Opened 2022-06-18 18:04 UTC by songhn233

### Types

- [x] 🎉 New Features

### Background or solution

Close #1057

对于 `dialogService.open` 增加 `props` 透传给 Overlay 组件

**使用方式**

例如对 https://github.com/opensumi/core/blob/main/packages/editor/src/browser/untitled-resource.ts#L205，增加 props

<img width="600" alt="image" src="https://user-images.githubusercontent.com/47357585/174451008-43570164-119d-4db8-a6f9-e29ff02f57d0.png">

触发 dialog 增加对应 className

<img width="571" alt="image" src="https://user-images.githubusercontent.com/47357585/174451022-bbbd671a-5dd9-4f11-a89e-244b67917b02.png">

### Changelog
`dialogService.open` 增加 props 自定义 dialog 样式

2022-06-23 06:47 UTC, erha19 requested changes

2022-06-23 06:47 UTC, erha19 commented on packages/overlay/src/browser/dialog.service.ts
> +  protected props: Record<string, any> = {};
这里的 props 非动态化的值，类似于 className 等应该是一个一次性的动作，感觉没必要使用 `@observable` 去做处理

2022-06-23 18:04 UTC, songhn233 commented on packages/overlay/src/browser/dialog.service.ts
> +  protected props: Record<string, any> = {};
> 这里的 props 非动态化的值，类似于 className 等应该是一个一次性的动作，感觉没必要使用 `@observable` 去做处理

这样的看话似乎这些属性都不需要加 `@observable` 让 Dialog 响应 ？

`msg` 等属性在 `open` 里指定后就不会变化，只会通过 `reset` 清空

2022-06-24 07:14 UTC, erha19 commented on packages/overlay/src/browser/dialog.service.ts
> +  protected props: Record<string, any> = {};
想了一下，这里应该还是有同感 open 方法去更新 msg 一类的情况 ？ @hacke2  帮忙看看？

2022-06-24 07:18 UTC, songhn233 commented on packages/overlay/src/browser/dialog.service.ts
> +  protected props: Record<string, any> = {};
我理解 open 和 hide 都会修改 visible，只要让 visible 是 observable 就行了？

open 中改动其他的属性改动在 rerender 时候也会获取到

2022-06-29 02:30 UTC, hacke2 commented on packages/overlay/src/browser/dialog.service.ts
> +  protected props: Record<string, any> = {};
确实没必要都 observable，目前没有这样的用法，就只监听 visible 吧

2022-06-29 02:33 UTC, erha19 approved these changes

2022-06-29 02:33 UTC, merged