fix: if ExtensionClientAppContribution disposed  shouldn't dispose again
opensumi/core pull request #1240
Opened 2022-06-27 09:42 UTC by hacke2

### Types

- [x] 🐛 Bug Fixes

### Background or solution

![image](https://user-images.githubusercontent.com/6399899/175910843-633572a2-c88d-41c0-afb4-efdcedd7d495.png)

### Changelog
if ExtensionClientAppContribution disposed  shouldn't dispose again

2022-06-27 10:09 UTC, hacke2 commented on packages/core-browser/src/bootstrap/app.ts
> +    this.contributions = this.contributionsProvider.getContributions();
这个改在了 start 阶段初始化，防止 dispose 阶段获取会生成新的实例

2022-06-28 12:44 UTC, bytemain requested changes

2022-06-28 12:44 UTC, bytemain commented on packages/core-browser/src/bootstrap/app.ts
> +    this.contributions = this.contributionsProvider.getContributions();
感觉这个提前 会带来问题

2022-06-29 03:23 UTC, Aaaaash commented on packages/core-browser/src/bootstrap/app.ts
> +    this.contributions = this.contributionsProvider.getContributions();
这个应该问题不大，目前 ContributionProvider 都是静态的，也就是在 new ClientApp 的时候就已经能拿到所有 contribution 了

2022-09-08 09:43 UTC, closed without merging