[WIP]: feat: support extension contributes code snippets in packageJson
opensumi/core pull request #1254
Opened 2022-06-30 06:55 UTC by Ricbet

### Types

- [x] 🎉 New Features

### Background or solution

![image](https://user-images.githubusercontent.com/20262815/176611979-ee72b200-5514-43d4-8483-34035903aa33.png)

![image](https://user-images.githubusercontent.com/20262815/176612135-8331f11d-cd7b-44bb-99d5-b5f698d0ec52.png)

### Changelog
support extension contributes code snippets in packageJson

2022-07-01 10:20 UTC, hacke2 commented
wonderful!

2022-07-07 03:13 UTC, erha19 requested changes

2022-07-07 03:13 UTC, erha19 commented on packages/i18n/src/common/contributes/zh-CN.lang.ts
> +  'kaitianContributes.browserViews.view.icon': '图标名称，参考: [内置图标集](https://docs.antfin-inc.com/iconfont-demo/)',
这里还是内网地址，可以改成外网的

2022-07-07 03:13 UTC, erha19 commented on packages/i18n/src/common/contributes/zh-CN.lang.ts
> +  'kaitianContributes.viewsProxies': '声明需要绑定 componentProxy 调用的组件 id, 与导出名相同。例如声明 ["component"] 后, 即可在 node 层通过 **`context.componentProxy.component.xxxx`** 调用 browser 层 component 组件的 xxxx 函数',
markdown 支持的吗？

2022-07-07 03:13 UTC, erha19 commented on packages/i18n/src/common/contributes/zh-CN.lang.ts
> +    1. 如果 group 已注册, 将其注册在group内，跟随 group 出现
这里的序号有问题

2022-07-07 03:13 UTC, erha19 commented on packages/i18n/src/common/contributes/zh-CN.lang.ts
> +在 web 版本的 IDE 上，会额外存在这两个
web 版本 -> Web 版本

2022-07-07 03:13 UTC, erha19 commented on packages/i18n/src/common/contributes/zh-CN.lang.ts
> +  'kaitianContributes.toolbar.actions.button.states': '按钮状态，除了可以修改不同文案、图标路径和渲染模式外，还可以修改样式，类似声明一组 classname，可通过 API 改变按钮的状态',
ClassName

2022-07-07 03:13 UTC, erha19 commented on packages/i18n/src/common/contributes/zh-CN.lang.ts
> +  'kaitianContributes.toolbar.actions.button.states.showTitle': '是否显示 title, 默认为 true',
另外，现在不是推荐用 sumiContributes 了吗？还是改成 sumiContributes 吧，省的后面有硬编码依赖

2022-07-07 03:13 UTC, erha19 commented on packages/i18n/src/common/contributes/en-US.lang.ts
> +  'kaitianContributes.common.command': '',
这里没有文案

2022-07-07 03:13 UTC, erha19 commented on packages/i18n/src/common/contributes/en-US.lang.ts
> +  'kaitianContributes.browserViews.view.icon': 'Icon name, reference: [icon](https://docs.antfin-inc.com/iconfont-demo/)',
同样的内网地址

2022-07-07 03:55 UTC, Ricbet commented on packages/i18n/src/common/contributes/zh-CN.lang.ts
> +  'kaitianContributes.browserViews.view.icon': '图标名称，参考: [内置图标集](https://docs.antfin-inc.com/iconfont-demo/)',
外网地址是啥

2022-07-07 03:55 UTC, Ricbet commented on packages/i18n/src/common/contributes/zh-CN.lang.ts
> +  'kaitianContributes.viewsProxies': '声明需要绑定 componentProxy 调用的组件 id, 与导出名相同。例如声明 ["component"] 后, 即可在 node 层通过 **`context.componentProxy.component.xxxx`** 调用 browser 层 component 组件的 xxxx 函数',
支持的，有个 markdownDescription 字段

2022-07-07 03:57 UTC, erha19 commented on packages/i18n/src/common/contributes/zh-CN.lang.ts
> +  'kaitianContributes.browserViews.view.icon': '图标名称，参考: [内置图标集](https://docs.antfin-inc.com/iconfont-demo/)',
https://opensumi.github.io/core 这个

2022-07-08 03:12 UTC, erha19 requested changes

2022-07-08 03:12 UTC, erha19 commented on packages/core-browser/src/extensions/schema/opensumiExtensionPackageSchema.ts
> +        'All contributions of the KAITIAN extension represented by this package.',
这里还有个 KAITIAN

2022-07-08 03:12 UTC, erha19 commented on packages/core-browser/src/extensions/extensions-point.service.ts
> +export const EXTENSION_JSON_URI = 'vscode://schemas/vscode-extensions';
这里的自定义协议路径是不是没必要是 `vscode://` 改成 `sumi://` 也没啥影响的样子

2022-07-08 06:03 UTC, erha19 approved these changes

2022-07-08 06:03 UTC, merged