WIP: support multi-person collaborative editing
opensumi/core pull request #1274
Opened 2022-07-05 16:15 UTC by situ2001

### Types

- [x] 🎉 New Features

### Background or solution

This is an advance subject of [ASoC 2022](https://opensource.alibaba.com/asoc2022) and https://github.com/opensumi/core/issues/1103. 

For more details, visit https://github.com/opensumi/core/issues/1097.

close https://github.com/opensumi/core/issues/1097

### Changelog

- init collaboration module

2022-07-25 07:51 UTC, situ2001 commented
基本功能大致完成，操作效果如下

- 编辑

https://user-images.githubusercontent.com/28241963/180725600-e960c1f3-e2e9-4907-878d-4f58883cfe86.mov

- 新建文件，撤销与重做

https://user-images.githubusercontent.com/28241963/180726053-bbc5e31c-c36d-4cda-aa62-85331c298476.mov

2022-07-25 07:53 UTC, tyn1998 commented
🐮🍺

2022-07-25 08:01 UTC, situ2001 commented
Edit title for CI test

2022-08-28 12:56 UTC, situ2001 commented
告一段落，这里尝试简单指出后续的工作：https://github.com/situ2001/opensumi-core/issues/15

2022-09-13 10:14 UTC, erha19 commented
@situ2001 冲突处理一下

2022-09-15 15:04 UTC, erha19 requested changes

2022-09-15 15:04 UTC, erha19 commented on packages/collaboration/package.json
> +  "version": "2.18.7",
@situ2001 这里的版本号要对齐一下现在 main 分支版本号，否则构建会过不去

2022-09-19 09:07 UTC, Aaaaash approved these changes
LGTM

2022-09-19 09:10 UTC, erha19 approved these changes

2022-09-19 09:11 UTC, merged