feat: unify compressing
opensumi/core pull request #1299
Opened 2022-07-10 15:16 UTC by songhn233

### Types

- [x] 🪚 Refactors

### Background or solution

Close #976

https://github.com/node-modules/compressing/pull/73 有一个待合并的类型 typo，在代码中先重新定义了

### Changelog
- 解压缩统一依赖为 Compressing

2022-07-11 02:02 UTC, erha19 requested changes

2022-07-11 02:02 UTC, erha19 commented on packages/logs-core/src/node/utils.ts
> +// const debugLog = getDebugLogger('LogUtils');
不需要的语句移除掉吧

2022-07-11 02:02 UTC, erha19 commented on packages/logs-core/src/node/utils.ts
>      throw new Error(`日志目录不存在 ${foldPath}`);
顺带把这里的中文信息可以改成英文 Error 信息好一些

2022-08-15 07:31 UTC, erha19 commented
@songhn233 冲突处理一下 ~

2022-08-16 15:59 UTC, songhn233 commented
> @songhn233 冲突处理一下 ~

Done.

2022-08-22 08:20 UTC, erha19 commented
@songhn233 测试还是受到影响了，可能是这个文件 node/log.service.test.ts，可以用框架项目内的 `launch.json` 中定义的  Jest Current File 命令调试一下测试

2022-08-24 01:40 UTC, songhn233 commented
> @songhn233 测试还是受到影响了，可能是这个文件 node/log.service.test.ts，可以用框架项目内的
`launch.json` 中定义的 Jest Current File 命令调试一下测试

嗯看了下应该是一些副作用，一旦这个 case 通过后面的执行就会 crash，实际不影响

![Hoqh4KQIU7](
https://user-images.githubusercontent.com/47357585/186270760-135a6347-a438-4e90-82d0-f773f1d322e3.jpg
)

不过 `GetLogZipArchiveByDay` 本来就没有被使用到，这里测试我先 skip 掉吧～

2022-08-24 10:07 UTC, erha19 commented
@songhn233 这个文件测试还是存在问题 `logs-core/__tests__/node/log-manager.test.ts` ，相关代码可能比较陈旧，需要修改可以直接就改了

2022-08-24 16:39 UTC, songhn233 commented
> @songhn233 这个文件测试还是存在问题 `logs-core/__tests__/node/log-manager.test.ts` ，相关代码可能比较陈旧，需要修改可以直接就改了

可以，处理了～

2022-08-25 02:34 UTC, erha19 submitted a review, later dismissed

2022-08-25 02:35 UTC, erha19 commented
@songhn233 https://github.com/node-modules/compressing/pull/73 这里已经发了一个 1.6.1 版本，感觉可以升级一下把多余的 typo 定义去掉

2022-08-25 03:38 UTC, songhn233 commented
> @songhn233 [node-modules/compressing#73](https://github.com/node-modules/compressing/pull/73) 这里已经发了一个 1.6.1 版本，感觉可以升级一下把多余的 typo 定义去掉

可以，之前定义已经去掉了。我把版本也明确一下到 `^1.6.2` 吧

2022-08-25 03:38 UTC, erha19 approved these changes
LGTM

2022-08-25 07:32 UTC, merged

2022-08-25 07:34 UTC, hacke2 commented on packages/extension-manager/src/node/vsx-extension.service.ts
> -  return [448 /* S_IRWXU */, 56 /* S_IRWXG */, 7 /* S_IRWXO */]
之前选择 yauzl 的原因是 yauzl 可以保持文件自身的权限，这个代码不能被删除的

2022-08-25 07:39 UTC, bytemain commented on packages/extension-manager/src/node/vsx-extension.service.ts
> -  return [448 /* S_IRWXU */, 56 /* S_IRWXG */, 7 /* S_IRWXO */]
新版 compressing 已经修复了