fix: log recursive output
opensumi/core pull request #1309
Opened 2022-07-11 12:29 UTC by yantze

### Types

- [x] 🐛 Bug Fixes

### Background or solution
close #1308 

### Changelog
fix: log recursive output

2022-07-12 06:16 UTC, erha19 requested changes

2022-07-12 06:16 UTC, erha19 commented on packages/preferences/src/browser/userstorage/user-storage.service.ts
> +const DEFAULT_WATCH_OPTIONS = { recursive: false, excludes: ['**/logs/**'] };
这里应该不太对，默认还有一个 watchExclude，你这样写应该就少了 `node_modules/**`  那些的 watchExclude 配置了

2022-07-12 07:09 UTC, yantze commented on packages/preferences/src/browser/userstorage/user-storage.service.ts
> +const DEFAULT_WATCH_OPTIONS = { recursive: false, excludes: ['**/logs/**'] };
这个是直接从下面的代码移上来的。

至于 node_modules/** 感觉没有特别加上去的原因，其中一个场景，安装项目内的依赖似乎不会产生过多日志的问题

2022-07-14 01:59 UTC, erha19 approved these changes

2022-07-14 02:00 UTC, merged