fix: global search shortcut not working
opensumi/core pull request #1503
Opened 2022-08-13 09:07 UTC by iamxukai

### Types

- [x] 🐛 Bug Fixes

### Background or solution
#1105 的相关问题

在 Windows 环境下， Ctrl + Shift + F 快捷键不起作用，通过将快捷键对应的命令 id 替换成 `workbench.action.findInFiles` 可以让快捷键生效。
### Changelog
将快捷键对应的命令 id `content-search.openSearch` 替换成 `workbench.action.findInFiles`

2022-08-15 03:19 UTC, erha19 requested changes

2022-08-15 03:19 UTC, erha19 commented on packages/core-browser/src/common/common.command.ts
> +    id: 'workbench.action.findInFiles',
这里，建议是通过框架内置的 delegate 机制去映射一下命令，参考这里 https://github.com/opensumi/core/blob/74990a7142cee21f4d10ac04eace61316e82a667/packages/extension/src/browser/vscode/builtin-commands.ts ，你只需要写入一下映射规则就行了 @iamxukai

2022-08-15 06:14 UTC, yantze commented
在 Windows 里面试了一下， Ctrl+shift+F 是可以切换到搜索面板的，看看是不是你快捷键配置上的问题，还是因为 OpenSumi 其它问题导致这个问题的

2022-08-15 06:16 UTC, yantze commented
> 在 Windows OpenSumi Core 里面试了一下， Ctrl+shift+F 是可以切换到搜索面板的，看看是不是你快捷键配置上的问题，还是因为 OpenSumi 其它问题导致这个问题的

如果是快捷键插件上的优化，改内部 id 没问题

2022-08-16 05:43 UTC, iamxukai commented
> 在 Windows OpenSumi Core 里面试了一下， Ctrl+shift+F 是可以切换到搜索面板的，看看是不是你快捷键配置上的问题，还是因为 OpenSumi 其它问题导致这个问题的

我没做什么其它操作，虽然看到快捷键列表面板上原本是存在这个快捷键的，但是没效果，所以选择改下命令 id。
![Dingtalk_20220816134037](https://user-images.githubusercontent.com/85668115/184805984-b2ff78ec-6c1d-48d2-8fe5-7235318e9b74.jpg)
在原本的命令 id 下，点击快捷键，没看到有什么报错，就是没有切换到搜索面板的效果。
所以我是关闭 PR 呢，还是按照 request change 进行修改呢？

2022-08-24 08:39 UTC, erha19 approved these changes

2022-08-24 08:39 UTC, merged