feat: shortcut adaptaion of ctrlcmd+f1
opensumi/core pull request #1504
Opened 2022-08-14 15:39 UTC by iamxukai

### Types

- [x] 🎉 New Features

### Background or solution
#1105 的相关问题
<html>
<body>
<!DOCTYPE html>

Linux, Windows | macOS | Feature | 插件自身是否支持 | 对应的command | OpenSumi 是否有实现对应插件命令
-- | -- | -- | -- | -- | --
ctrl+f1 | cmd+f1 | Show descriptions of error or warning at caret | ✅ | workbench.action.showErrorsWarnings | N/A

</body>
</html>

### Changelog
注册一个 `workbench.action.showErrorsWarnings` 命令及编写命令的处理函数。
before:
![Dingtalk_20220814225158](https://user-images.githubusercontent.com/85668115/184544263-a288fd52-ec44-4e02-ad3f-889522d6fc6a.jpg)
after:
![after](https://user-images.githubusercontent.com/85668115/184544448-e83cacb2-97dd-4e6a-a5c4-3d389ff51ac9.jpg)

2022-08-15 02:01 UTC, erha19 requested changes

2022-08-15 02:01 UTC, erha19 commented on packages/markers/src/browser/markers-contribution.ts
> +  registerCommands(commands: CommandRegistry): void {
所以这里实际上是注册了一个命令用于给 IDEA 快捷键插件注册快捷键使用，实际上 macOS 下的快捷键不一定是 `CMD+F1` ，因为现在一些 mac 都是没有 F1 功能键了

2022-08-16 05:57 UTC, iamxukai commented on packages/markers/src/browser/markers-contribution.ts
> +  registerCommands(commands: CommandRegistry): void {
> 所以这里实际上是注册了一个命令用于给 IDEA 快捷键插件注册快捷键使用，实际上 macOS 下的快捷键不一定是 `CMD+F1` ，因为现在一些 mac 都是没有 F1 功能键了

在这插件里，这个命令对应的快捷键目前应该是设置成这个样子。

2022-08-16 06:04 UTC, erha19 commented on packages/markers/src/browser/markers-contribution.ts
> +    id: 'workbench.action.showErrorsWarnings',
这里跟你前面一个 PR 一样，比较建议用 delegate 机制去做，这里的 commandId 实际与框架内定义的格式差距比较大，一般而言，框架内的命令定义为 `marker.action.showErrorsWarnings`，然后统一放到 common.command.ts 文件内

2022-08-16 06:43 UTC, iamxukai commented on packages/markers/src/browser/markers-contribution.ts
> +    id: 'workbench.action.showErrorsWarnings',
> 这里跟你前面一个 PR 一样，比较建议用 delegate 机制去做，这里的 commandId 实际与框架内定义的格式差距比较大，一般而言，框架内的命令定义为 `marker.action.showErrorsWarnings`，然后统一放到 common.command.ts 文件内

 idea 快捷键插件快捷键和命令id有对应关系，[例如](https://github.com/kasecato/vscode-intellij-idea-keybindings/blob/c9c089665430f90b1eb43dc8914569b27fc9042f/package.json)。为了适配 idea 快捷键插件，那么需要让插件获取到快捷键对应的命令 id，所以命令 id 不能修改。这里的 delegate 不知道是哪个命令 id，我试过 `workbench.view.ide-markers` 和 `workbench.view.markers`，发现不可行。为什么选择尝试这个呢，因为[这里](https://github.com/opensumi/core/blob/main/packages/markers/src/browser/markers-contribution.ts#L43)和 [这里](https://github.com/opensumi/core/blob/main/packages/main-layout/src/browser/tabbar/tabbar.service.ts#L512)。

2022-08-16 06:52 UTC, erha19 commented on packages/markers/src/browser/markers-contribution.ts
> +    id: 'workbench.action.showErrorsWarnings',
这里不是说实现功能本身不对，是在于命令定义上的规范出发，比较理想的情况下，后续所有 OpenSumi 的公共命令，用户都可以通过 `common.command.ts` 文件找到并引用到。

同时，对于本身 showErrorsWarnings 这个命令，给到的建议是参考 `common.command.ts` 的命名规则，采用 `{模块名}.xx.xx` 的方式规范，最后再通过 [builtin-commands.ts](https://github.com/opensumi/core/blob/74990a7142cee21f4d10ac04eace61316e82a667/packages/extension/src/browser/vscode/builtin-commands.ts) 去给这些命令一个别名用于适配 VS Code 插件，否则长此以往，为了适配各类插件，OpenSumi 框架内就都是 VS Code 的内置命令了，对于之前部分没有规范的命令，后续也是需要慢慢改过来的。

2022-08-17 01:54 UTC, erha19 commented
@iamxukai 冲突处理一下 ~

2022-08-18 02:24 UTC, erha19 approved these changes

2022-08-18 07:04 UTC, merged