fix 解决不使用终端模块导致的其他底部的模块丢失 放大和折叠按钮的bug
opensumi/core pull request #1524
Opened 2022-08-16 10:03 UTC by dabaoshu

fix 解决不使用终端模块导致的其他底部的模块丢失 放大和折叠按钮的bug

2022-08-16 10:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/opensumi/core?pullRequest=1524) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/opensumi/core?pullRequest=1524) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/opensumi/core?pullRequest=1524) it.</sub>

2022-08-16 11:44 UTC, erha19 requested changes

2022-08-16 11:44 UTC, erha19 commented on packages/main-layout/src/browser/main-layout.contribution.ts
> +    // commands.registerCommand(EXPAND_BOTTOM_PANEL, {
这里可以直接删了，不用注释留着

2022-08-16 12:06 UTC, erha19 approved these changes
LGTM

2022-08-17 07:05 UTC, bytemain commented
需要签署一下 CLA 协议~ 请使用 commit 中的设置的用户账号来签署。

2022-08-17 07:08 UTC, erha19 commented
<img width="885" alt="image" src="https://user-images.githubusercontent.com/9823838/185056497-66715d37-25e7-4766-8378-caef5a03e5f6.png">

CLA 服务后台可以看到签署记录了，不过这个状态貌似不太准确

2022-08-17 07:09 UTC, merged

2022-08-17 07:09 UTC, bytemain commented
是楼主 commit 时的账户要签署协议，不是当前提 PR 的这个账号。

2022-08-17 07:11 UTC, erha19 commented
> 是楼主 commit 时的账户要签署协议，不是当前提 PR 的这个账号。

@dabaoshu 后续补充签订一下吧 csdnguoshu 这个账号 https://cla-assistant.io/opensumi/core?pullRequest=1524