feat: shortcut adaptation of shift+f6
opensumi/core pull request #1526
Opened 2022-08-16 13:30 UTC by iamxukai

### Types

- [x] 🎉 New Features

### Background or solution
#1105 相关问题

<html>
<body>
<!DOCTYPE html>

Linux, Windows | macOS | Feature | 插件自身是否支持 | 对应的command | OpenSumi 是否有实现对应插件命令
-- | -- | -- | -- | -- | --
shift+f6 | shift+f6 | Rename | ✅ | editor.action.rename | N/A

</body>
</html>

### Changelog
通过命令代理，借助现有的 `RENAME_FILE` 的命令适配插件的 `Shift+F6` 快捷键。

2022-08-18 06:57 UTC, erha19 requested changes

2022-08-18 06:57 UTC, erha19 commented on packages/extension/src/browser/vscode/builtin-commands.ts
> +  id: 'renameFile',
这里不应该是 `editor.action.rename` 吗？

2022-08-18 07:04 UTC, iamxukai commented on packages/extension/src/browser/vscode/builtin-commands.ts
> +  id: 'renameFile',
> 这里不应该是 `editor.action.rename` 吗？
我复制错命令的信息，已经更新了下 Background or solution 内容。

2022-08-24 08:38 UTC, erha19 approved these changes

2022-08-24 08:38 UTC, merged