WIP: feat: support rerun last task
opensumi/core pull request #1528
Opened 2022-08-17 03:19 UTC by bytemain

### Types

- [x] 🎉 New Features

### Background or solution

### Changelog

2022-08-24 08:35 UTC, erha19 requested changes
另外冲突可以处理一下

2022-08-24 08:35 UTC, erha19 commented on packages/task/src/browser/task.contribution.ts
> +  // 以下命令的 ID 最好和 VSCode 保持一致，因为部分插件会执行 Task 相关的命令
@bytemain 这里的命令实际上可以按模块内的命名去写，通过插件进程的 delegate 逻辑做命令调用的转发，下面这个命令看了一下还没有实现，是不是可以先删了？

2022-08-24 08:35 UTC, erha19 commented on packages/task/src/browser/task.contribution.ts
> +    // commandRegister.registerCommand(TaskContribution.RESTART_RUNNING_TASK, {
这里没有做实现。

2022-08-24 08:35 UTC, erha19 commented on packages/task/src/browser/task.service.ts
> +    this.outputChannel = this.outputService.getChannel('task.output.channel');
这里如果把 localize 去掉了，输出面板上面的选项会变成 'task.output.channel'，应该是不符合预期的。

2022-08-24 08:35 UTC, erha19 commented on packages/terminal-next/src/node/terminal.service.ts
> +          t.kill(); // terminalProfile 有 isTransient 的参数化，要Kill，不保活
"参数化" =>  "参数时"？

2022-08-25 02:58 UTC, erha19 commented
ref #1531.

2022-08-25 02:59 UTC, bytemain commented
> ref #1531.

1531 还没修

2022-08-25 03:09 UTC, erha19 commented on packages/task/src/browser/task.contribution.ts
> +  // static readonly RESTART_RUNNING_TASK: Command = {
这些近期如果没计划写可以先删了，没太必要留着注释

2022-08-29 08:04 UTC, erha19 approved these changes

2022-08-29 08:04 UTC, merged