feat: shortcut adaptation of ctrl+shift+f12
opensumi/core pull request #1557
Opened 2022-08-22 00:21 UTC by iamxukai

### Types

- [x] 🎉 New Features

### Background or solution
#1105 的相关问题
<html>
<body>
<!DOCTYPE html>

Linux, Windows | macOS | Feature | 插件自身是否支持 | 对应的command | OpenSumi 是否有实现对应插件命令
-- | -- | -- | -- | -- | --
ctrl+shift+f12 | cmd+shift+f12 | Toggle maximizing editor | ✅ | workbench.action.maximizeEditor | N/A

</body>
</html>

### Changelog
在 `MAIN_LAYOUT_COMMANDS` 命名空间内新增 `MAXIMIZE_EDITOR` 命令，通过命令代理适配插件的最大化编辑器快捷键 `ctrl+shift+f12` 。
注意到，最大化编辑器并不会隐藏底部的终端面板，而是会隐藏左右两侧的面板。

2022-08-22 02:16 UTC, erha19 commented on packages/extension/src/browser/extension.contribution.ts
> +      VSCodeBuiltinCommands.MAIN_LAYOUT_COMMAND_MAXIMIZE_EDITOR,
@iamxukai 这里的代码缩进及换行感觉有点问题

2022-08-22 03:55 UTC, iamxukai commented on packages/extension/src/browser/extension.contribution.ts
> +      VSCodeBuiltinCommands.MAIN_LAYOUT_COMMAND_MAXIMIZE_EDITOR,
> 这里的代码缩进及换行感觉有点问题

commit的时候，应该会用 https://github.com/opensumi/core/blob/main/package.json#L74-L76 进行格式化吧？

2022-08-24 08:18 UTC, erha19 requested changes

2022-08-24 08:18 UTC, erha19 commented on packages/main-layout/src/browser/main-layout.contribution.ts
> +          this.commandService.executeCommand('main-layout.right-panel.toggle', false);
这里的 ID 从 `TOGGLE_RIGHT_PANEL_COMMAND` 和 `TOGGLE_LEFT_PANEL_COMMAND` 里面引入进来吧，尽量减少硬编码命令 ID 的情况

2022-08-25 03:04 UTC, erha19 approved these changes

2022-08-25 03:06 UTC, erha19 commented on packages/extension/src/browser/vscode/builtin-commands.ts
> +export const LAYOUT_COMMAND_MAXIMIZE_EDITOR: Command = {
发现这个文件里面命名上很多多余的 `xxx_COMMAND_xx`  的写法，后续有空可以都改掉，统一一下写法

2022-08-25 03:06 UTC, merged