feat: for ASoC2022 chrome devtools
opensumi/core pull request #1560
Opened 2022-08-22 04:46 UTC by tyn1998

> 先借助Action来测试一下问题，Description中的内容之后补充。

### Types

- [ ] 🎉 New Features
- [ ] 🐛 Bug Fixes
- [ ] 📚 Documentation Changes
- [ ] 💄 Code Style Changes
- [ ] 💄 Style Changes
- [ ] 🪚 Refactors
- [ ] 🚀 Performance Improvements
- [ ] 🏗️ Build System
- [ ] ⏱ Tests
- [ ] 🧹 Chores
- [ ] Other Changes

### Background or solution

### Changelog

2022-08-22 10:17 UTC, tyn1998 commented
@yantze @erha19 @bytemain

Hi guys! Please take minutes to review the code, thanks!

2022-08-22 10:24 UTC, tyn1998 commented
对于Web端，只要浏览器安装了opensumi devtools插件即可生效；对于Electron端，需要等该插件上架到chrome webstore后再利用[electron-devtools-installer](https://www.npmjs.com/package/electron-devtools-installer)进行集成（见[此issue](https://github.com/tyn1998/opensumi-devtools/issues/55)）。

所以不想分好几个PR的话，可以等到插件发布上架后再合并这个PR。

2022-08-23 01:41 UTC, yantze commented on packages/connection/src/common/proxy.ts
> +                getCapturer() && getCapturer()({ type: 'sendNotification', serviceMethod: prop, arguments: args });
getCapturer() 保存为一个本地变量就好了，最好不要用 prettier-ignore

2022-08-23 01:44 UTC, tyn1998 commented on packages/connection/src/common/proxy.ts
> +                getCapturer() && getCapturer()({ type: 'sendNotification', serviceMethod: prop, arguments: args });
收到，我改一下~

用两次getcapture和用prettier-ignore是为了想捕获逻辑尽量少点“存在感”，能占的少就少，并且长长的一条容易识别出来。

2022-08-23 01:47 UTC, yantze commented on packages/connection/src/common/proxy.ts
> +                getCapturer() && getCapturer()({ type: 'sendNotification', serviceMethod: prop, arguments: args });
这里看起来定义一个 get getCapturer() 就好了吧

2022-08-23 01:47 UTC, yantze commented on packages/connection/src/common/proxy.ts
> +                getCapturer() && getCapturer()({ type: 'onRequestResult', status: 'success', requestId, serviceMethod: method,  data: result.data });
有限固定值 比如 success 或者 fail 用 map 定义会好一点，之后可以只用修改定义内容

2022-08-23 01:47 UTC, yantze commented on packages/addons/src/browser/chrome-devtools.contribution.ts
> +    global.setInterval(() => {
这里空转浪费性能，先判断 `window.__OPENSUMI_DEVTOOLS_GLOBAL_HOOK__` 这个全局变量，看看插件能不能在激活的时候注入进 Window 全局变量

2022-08-23 01:51 UTC, tyn1998 commented on packages/connection/src/common/proxy.ts
> +                getCapturer() && getCapturer()({ type: 'onRequestResult', status: 'success', requestId, serviceMethod: method,  data: result.data });
> 这里看起来定义一个 get getCapturer() 就好了吧

这个没大懂。。

> 有限固定值 比如 success 或者 fail 用 map 定义会好一点，之后可以只用修改定义内容

收到！

2022-08-23 01:54 UTC, yantze commented on packages/connection/src/common/proxy.ts
> +                getCapturer() && getCapturer()({ type: 'onRequestResult', status: 'success', requestId, serviceMethod: method,  data: result.data });
就设置一个 getter 方法，然后用 `this.getCapturer({ type: xxx })` 这样

2022-08-23 01:56 UTC, tyn1998 commented on packages/addons/src/browser/chrome-devtools.contribution.ts
> +    global.setInterval(() => {
@yantze 老师，这个能不能描述地更加详细一点点？

这个setInterval的确不优雅，我想达到的目的就是为了让opensumi-devtools能够控制opensumi/core，于是想到的方法就是opensumi/core进行轮询。

2022-08-23 02:17 UTC, yantze commented on packages/addons/src/browser/chrome-devtools.contribution.ts
> +    global.setInterval(() => {
至少有两个方法：
1. OpenSumi Devtools 先注入 window 全局变量，然后 OpenSumi 轮训三次等 OpenSumi  Devtools 注册
2. OpenSumi 创建一个 new Event('opensumi-devtools') 事件，然后监听来自 OpenSumi Devtools 插件的事件发起

2022-08-23 03:29 UTC, tyn1998 commented on packages/addons/src/browser/chrome-devtools.contribution.ts
> +    global.setInterval(() => {
> 2. OpenSumi 创建一个 new Event('opensumi-devtools') 事件，然后监听来自 OpenSumi Devtools 插件的事件发起

这个听上去好nice！由于是两个app，我都没往这方面想。

2022-08-24 02:29 UTC, tyn1998 commented on packages/addons/src/browser/chrome-devtools.contribution.ts
> +    global.setInterval(() => {
opensumi devtools对应的dispatchEvent：https://github.com/tyn1998/opensumi-devtools/pull/58

2022-08-24 08:29 UTC, erha19 requested changes

2022-08-24 08:29 UTC, erha19 commented on packages/connection/src/common/utils.ts
> +export function generateUniqueId() {
这个方法可以从 `@opensumi/ide-core-common` 里面引入 `uuid`

2022-08-24 08:29 UTC, erha19 commented on packages/addons/src/browser/chrome-devtools.contribution.ts
> +    if (window.__OPENSUMI_DEVTOOLS_GLOBAL_HOOK__ && window.__OPENSUMI_DEVTOOLS_GLOBAL_HOOK__.capture) {
这里写成 `window.__OPENSUMI_DEVTOOLS_GLOBAL_HOOK__?.capture` 就行了

2022-08-24 08:29 UTC, erha19 commented on packages/addons/src/browser/chrome-devtools.contribution.ts
> +      if (command === 'start') {
这里几个 Event 的状态抽出来用一个 DEVTOOLS_EVENT 的 enum 管理吧，类似于 
 
```ts
export enum DEVTOOLS_EVENT {
  START: 'start',
  ...
}
```

2022-08-24 08:30 UTC, tyn1998 commented on packages/addons/src/browser/chrome-devtools.contribution.ts
> +      if (command === 'start') {
收到~

2022-08-25 02:26 UTC, erha19 approved these changes
LGTM

2022-08-25 07:01 UTC, merged