fix: shortcut adaptation of alt+f12
opensumi/core pull request #1564
Opened 2022-08-22 15:02 UTC by iamxukai

### Types

- [x] 🐛 Bug Fixes

### Background or solution
#1105 的相关问题

<html>
<body>
<!DOCTYPE html>

Linux, Windows | macOS | Feature | 插件自身是否支持 | 对应的command | OpenSumi 是否有实现对应插件命令
-- | -- | -- | -- | -- | --
alt+f12 | alt+f12 | Opens and focuses corresponding tool window (Terminal) | ✅ | workbench.action.terminal.focus | N/A
alt+f12 | alt+f12 | Close corresponding tool window (Terminal) | ✅ | workbench.action.terminal.toggleTerminal | N/A

</body>
</html>

原先仅仅依靠 `workbench.action.terminal.toggleTerminal`命令代理，是不能实现切换终端视图的，因此就不能适配插件的快捷键 `alt+f12`。

### Changelog
依靠 `workbench.action.terminal.toggleTerminal` 命令代理，实现终端 focus 效果。
实现 `TERMINAL_COMMANDS.TOGGLE_VISIBILITY`命令，用于 `TERMINAL_COMMAND_TOGGLE_VISIBILITY`命令的代理。
before:
![before](https://user-images.githubusercontent.com/85668115/185952997-54d61788-9d91-44c2-9863-babd1cc4401c.jpg)
原先虽然注册了插件的命令 `workbench.action.terminal.toggleTerminal`，但是仅仅依靠 `workbench.action.terminal.toggleTerminal`命令代理，是不能实现切换终端视图的，因此就不能适配插件的快捷键 `alt+f12`。

after:
![after](https://user-images.githubusercontent.com/85668115/185952508-62556903-e9f2-4a96-897c-541a783d97c5.jpg)

2022-08-24 02:38 UTC, erha19 requested changes

2022-08-24 02:38 UTC, erha19 commented on packages/terminal-next/src/browser/contribution/terminal.command.ts
> +export const TERMINAL_CONTAINER_ID = 'ide-terminal-next';
这里的 CONTAINER_ID = 'terminal' 就行了，并且可以把定义放到 `common`  代码分层里面，与框架其他 CONTAINER_ID 统一命名，否则会导致 OpenView 命令出现这个奇怪的 “ide-terminal-next” 字段

2022-08-24 04:30 UTC, iamxukai commented on packages/terminal-next/src/browser/contribution/terminal.command.ts
> +export const TERMINAL_CONTAINER_ID = 'ide-terminal-next';
> 这里的 CONTAINER_ID = 'terminal' 就行了，并且可以把定义放到 `common` 代码分层里面，与框架其他 CONTAINER_ID 统一命名，否则会导致 OpenView 命令出现这个奇怪的 “ide-terminal-next” 字段

新建一个文件，放入 CONTAINER_ID，那么文件名是 types.ts 还是 constants.ts ？我看到两者都有

2022-08-24 06:05 UTC, erha19 commented on packages/terminal-next/src/browser/contribution/terminal.command.ts
> +export const TERMINAL_CONTAINER_ID = 'ide-terminal-next';
在 #1263 这个提交之后应该就没有了，没有合适位置你也可以新建一个 constants.ts 文件来存

2022-08-24 06:54 UTC, iamxukai commented on packages/terminal-next/src/browser/contribution/terminal.command.ts
> +export const TERMINAL_CONTAINER_ID = 'ide-terminal-next';
@erha19 原来有这个 [CONTAINER_ID](https://github.com/opensumi/core/blob/main/packages/terminal-next/src/common/index.ts#L18) ，那么我直接导入这个 CONTAINER_ID 就行了。

2022-08-25 01:58 UTC, erha19 approved these changes

2022-08-25 01:58 UTC, merged