WIP: feat: capture Electron IPC messages for opensumi devtools
opensumi/core pull request #1583
Opened 2022-08-26 11:33 UTC by tyn1998

#1098 also requires implementing IPC messages capturing and presenting within opensumi devtools. This PR provides messages capturing support for opensumi devtools.

### Types

- [x] 🎉 New Features

### Background or solution

之后补充

### Changelog

Electron IPC messages capturing support for opensumi devtools.

2022-08-29 08:24 UTC, erha19 requested changes

2022-08-29 08:24 UTC, erha19 commented on packages/connection/src/common/utils.ts
> +  if (typeof window !== 'undefined' && window.__OPENSUMI_DEVTOOLS_GLOBAL_HOOK__?.captureRpc) {
RPC 和 IPC 这种专有名词一般是大写的，写法上还是大写吧，例如 captureRPC

2022-08-29 08:24 UTC, erha19 commented on packages/core-electron-main/src/bootstrap/window.ts
> +    initForDevtools(this.browser);
这里是不是可以加一个开发态判断，Production 版本就不应该有这个代码的执行

2022-08-29 08:24 UTC, erha19 commented on packages/connection/src/common/utils.ts
> +  if (typeof window !== 'undefined' && window.__OPENSUMI_DEVTOOLS_GLOBAL_HOOK__?.captureRpc) {
下面还有 IPC 相关的写法也统一改一下

2022-08-29 09:29 UTC, tyn1998 commented on packages/connection/src/common/utils.ts
> +  if (typeof window !== 'undefined' && window.__OPENSUMI_DEVTOOLS_GLOBAL_HOOK__?.captureRpc) {
ok没问题~

2022-08-29 09:31 UTC, tyn1998 commented on packages/core-electron-main/src/bootstrap/window.ts
> +    initForDevtools(this.browser);
Dan老师的意思是说生产版本禁用opensumi devtools吗？我一直以为普通用户也是可以用opensumi devtools的，因为普通用户也是程序员，有时候可以用opensumi devtools帮助排查问题。

2022-08-29 13:07 UTC, tyn1998 commented on packages/connection/src/common/utils.ts
> +  if (typeof window !== 'undefined' && window.__OPENSUMI_DEVTOOLS_GLOBAL_HOOK__?.captureRpc) {
@erha19 老师，我发现electron在命名的时候也有“Ipc”这样的情况：

<img width="1493" alt="image" src="https://user-images.githubusercontent.com/32434520/187208071-434983d3-d74c-4d38-abc6-15e152f5b7ab.png">

还是说，驼峰命名的开头有例外的规范？

2022-09-05 03:02 UTC, erha19 requested changes

2022-09-05 03:02 UTC, erha19 commented on packages/core-electron-main/src/bootstrap/window.ts
> +    initForDevtools(this.browser);
一般对于这种开发工具代码，有点类似“后门”的程序，最好还是把是否集成的逻辑交给集成方去决定，默认开启的话会造成一些不必要的问题，用户可能在未知的情况下升级版本过程中集成了你这个特性，这里比较建议通过 AppCofig 中追加配置项来控制，例如 `devtool: boolean`, 默认值在开发态时为 True，这样不会影响已集成的用户

2022-09-05 03:04 UTC, tyn1998 commented
收到！学到了～

Dan ***@***.***>于2022年9月5日 周一11:02写道：

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In packages/connection/src/common/utils.ts
> <https://github.com/opensumi/core/pull/1583#discussion_r962439983>:
>
> > @@ -37,8 +37,8 @@ export function parse(input: string, reviver?: (this: any, key: string, value: a
>  }
>
>  export function getCapturer() {
> -  if (typeof window !== 'undefined' && window.__OPENSUMI_DEVTOOLS_GLOBAL_HOOK__?.capture) {
> -    return window.__OPENSUMI_DEVTOOLS_GLOBAL_HOOK__.capture;
> +  if (typeof window !== 'undefined' && window.__OPENSUMI_DEVTOOLS_GLOBAL_HOOK__?.captureRpc) {
>
> 那些地方的写法也是不规范的，有机会可以一起改掉，这种专有名词出现的时候还是要大写比较规范，例如 macOS，后面的 OS 全程是 Operating
> System，所以简称一般用大写表示，这里的 IPC，RPC 同样也是缩写，因此规范的写法也要是大写，比较好识别
> ------------------------------
>
> In packages/core-electron-main/src/bootstrap/window.ts
> <https://github.com/opensumi/core/pull/1583#discussion_r962441185>:
>
> > @@ -94,6 +95,10 @@ export class CodeWindow extends Disposable implements ICodeWindow {
>        ...this.appConfig.overrideBrowserOptions,
>        ...options,
>      });
> +
> +    // initialize for OpenSumi DevTools
> +    initForDevtools(this.browser);
>
> 一般对于这种开发工具代码，有点类似“后门”的程序，最好还是把是否集成的逻辑交给集成方去决定，默认开启的话会造成一些不必要的问题，用户可能在未知的情况下升级版本过程中集成了你这个特性，这里比较建议通过
> AppCofig 中追加配置项来控制，例如 devtool: boolean, 默认值在开发态时为 True，这样不会影响已集成的用户
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/opensumi/core/pull/1583#pullrequestreview-1095797892>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHXOSWAOCMI2RMGKKPQH2Y3V4VPDTANCNFSM57WMZDEQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-09-11 12:17 UTC, tyn1998 commented
@erha19 老师，“专有名词大小写”的问题[已经解决](https://github.com/opensumi/core/pull/1583/commits/82e764e6b67b9f1b94a4b9073317e44a02ee55b1)，在devtools项目中也有[对应的修改](https://github.com/opensumi/devtools/pull/5/commits/f19945945784b4dc0fe4aba021dccacb386b9aa3)。

但是，“增加配置项”这个要求我虽然push了一个[commit](https://github.com/opensumi/core/pull/1583/commits/fad552751128735acdc583f9ef832723c5f0a88c)，但还没有完成，需要帮助。我的思路和遇到的困难是这样的：

截止到此PR最新的commit，在opensumi/core中，与devtools相关的代码有[多处](https://github.com/opensumi/core/pull/1560/files#diff-e480ff35a638647fe38b0614efabfd5ef254e9216bf00a2695e388dc8b33c366)：

1. [暴露global hook的地方](https://github.com/opensumi/core/blob/0a64da0d159d2b712677a9dfef469f483fb88343/packages/core-browser/src/bootstrap/app.ts#L149-L151)
2. [connection模块](https://github.com/opensumi/core/blob/main/packages/connection/src/common/proxy.ts)
3. [chrome-devtools.contribution.ts](https://github.com/opensumi/core/blob/main/packages/addons/src/browser/chrome-devtools.contribution.ts)（目前只用于获取网络延迟）
4. [core-electron-main/src/bootstrap/window.ts](https://github.com/tyn1998/opensumi-core/blob/fad552751128735acdc583f9ef832723c5f0a88c/packages/core-electron-main/src/bootstrap/window.ts#L99-L102)中捕获ipcMain的消息
5. [core-electron-main/browser-preload/index.js](https://github.com/tyn1998/opensumi-core/blob/fad552751128735acdc583f9ef832723c5f0a88c/packages/core-electron-main/browser-preload/index.js#L61)中捕获ipcRenderer的消息

目前，通过新加入的`devtools: boolean`配置项，我可以控制1和4的开关，但是对于2、3、5我没有找到合适方法在相应的文件中获取配置项的值，于是就没法判断是否要运行与devtools有关的代码了。这就是我遇到的困难，此处可能还需要 @yantze 老师。

此外需要注意的是，对于Electron端来说，控制devtools的开关需要考虑两个地方：

1. core-browser捕获RPC的部分（对web端来说只要考虑这一个就行）
2. core-electron-main捕获IPC的部分。

所以在此PR中，我分别在`ElectronAppConfig`和`IClientAppOpts`两个配置项接口中加入了`devtools`这个配置项。于是，对于集成方来说，就要设置两个`devtools`，但事实上这两个devtools要么都是true要么都是false。所以，要是`IClientAppOpts.devtools`能通过`ElectronAppConfig.devtools`给出就好了，这又涉及到上面说的困难——如何把配置项传到需要的地方。

<img width="1056" alt="image" src="https://user-images.githubusercontent.com/32434520/189526901-4a0919ec-aef0-4b2d-9423-6b8d93ae8c25.png">

（可能描述得不是很清晰，再配一个图）

2022-09-13 11:04 UTC, yantze commented
IClientAppOpts 里面配置 devtools 就好了，至于 electron preload 的内容，可以加到 metadata 中，通过 metadata 去获取是否开启 devtools

2022-09-13 11:06 UTC, tyn1998 commented
> 可以加到 metadata 中，通过 metadata 去获取是否开启 devtools

谢谢 @yantze 老师！metadata这部分能不能稍微再展开一下~

2022-09-13 11:39 UTC, yantze commented
> > 可以加到 metadata 中，通过 metadata 去获取是否开启 devtools
> 
> 谢谢 @yantze 老师！metadata这部分能不能稍微再展开一下~

1. electron appConfig -> 2. electron window metadata -> 3. preload electronEnv.meta -> 4. renderApp(opts)

1. electron appConfig 初始化 https://github.com/tyn1998/opensumi-core/blob/fad5527511/packages/core-electron-main/src/bootstrap/app.ts#L81
2. 传递到 metadata https://github.com/tyn1998/opensumi-core/blob/fad5527511/packages/core-electron-main/src/bootstrap/window.ts#L128 
3. 通过 preload 获取 meta https://github.com/tyn1998/opensumi-core/blob/fad552751128735acdc583f9ef832723c5f0a88c/packages/core-electron-main/browser-preload/index.js#L93
4. 初始化 browser appConfig 通过 electronEnv.metadata 设置

这里的 electron 的 appConfig 和 browser 的 appConfig 是两个实例，确实都要声明的

2022-09-19 09:25 UTC, yantze submitted a review, later dismissed
LGTM

2022-09-20 13:56 UTC, erha19 requested changes

2022-09-20 13:56 UTC, erha19 commented on packages/core-electron-main/src/bootstrap/devtools.ts
> +  // 所以我不知道怎么处理. 如果可以实现, 注意判断channel是否为'main->browser'
不要在代码内加上主观阐述，直接说明原因就行了

2022-09-20 13:56 UTC, erha19 commented on packages/core-electron-main/src/bootstrap/app.ts
> +    if (this.config.devtools === undefined) {
这里可以从 `@opensumi/ide-core-common` 内引入 `isUndefined` 方法来判断，统一写法

2022-09-20 13:56 UTC, erha19 commented on packages/core-electron-main/browser-preload/index.js
> +      if (channel !== 'main->browser') {
这里的消息通道用 `main->browser` 感觉怪怪的，也没有所谓的 `browser->main`, 感觉这里可以跟框架内的部分消息体命名上保持一样格式 `{xxx}-{xxx}`, 用一个常量，例如 `CONNECTION_CAPTURE_CHANNAL='connection-capture-message` 去作为消息通道名称

2022-09-20 13:56 UTC, erha19 commented on packages/core-electron-main/src/bootstrap/devtools.ts
> +      // TODO event.returnValue会作为ipcRenderer.sendSync的response, 可捕获
这里这句注释的 TODO 貌似没有什么用？

2022-09-20 13:56 UTC, erha19 commented on packages/core-electron-main/src/bootstrap/devtools.ts
> +      // TODO event.returnValue会作为ipcRenderer.sendSync的response, 可捕获
另外有个问题，一个 Electron 客户端只会有一个 Main 进程，即会存在一个 Main 进程对应多个 Renderer 进程的情况，如果这里把 Main 通信消息都往 Browser 进程发，是不是会导致窗口 A，B 的通信消息串了的问题？比较理想的方式可能需要根据 WindowId 把消息区分处理一下

2022-09-23 07:46 UTC, tyn1998 commented on packages/core-electron-main/src/bootstrap/devtools.ts
> +      // TODO event.returnValue会作为ipcRenderer.sendSync的response, 可捕获
@erha19 老师，在Electron客户端打开了两个文件夹（两个窗口）测试，的确有这个Bug！我会修复的。

2022-09-23 07:58 UTC, tyn1998 commented on packages/core-electron-main/browser-preload/index.js
> +      if (channel !== 'main->browser') {
> CONNECTION_CAPTURE_CHANNAL='connection-capture-message 去作为消息通道名称

老师您觉得“notify-renderer”这个channel名称怎么样？

之所以用“main->browser”是因为与main进程相关的IPC api有`ipcMain.on`和`ipcMain.handle`，这两个IPC api的消息是在main进程中的，只有先转发到renderer进程才能被页面中的插件捕获。“connection-capture-message”这个名称蕴含的范围太大了，我感觉不合适，这个channel仅仅用于把main中的消息发到renderer进程中。

2022-09-23 08:09 UTC, erha19 commented on packages/core-electron-main/browser-preload/index.js
> +      if (channel !== 'main->browser') {
`notify-renderer` 在 main 进程内写有点怪，而且 renderer 反而更特指 Electron 环境，可以考虑用一点通用的名称命令 `devtools-xxx` 后面你可以自己决定一下，后面描述一下消息类型或作用就行了

2022-09-24 12:38 UTC, tyn1998 commented
> 另外有个问题，一个 Electron 客户端只会有一个 Main 进程，即会存在一个 Main 进程对应多个 Renderer 进程的情况，如果这里把 Main 通信消息都往 Browser 进程发，是不是会导致窗口 A，B 的通信消息串了的问题？比较理想的方式可能需要根据 WindowId 把消息区分处理一下

@erha19 老师的request changes里，最重要的是上面这个，因为影响功能的正确性，所以我仔细捋了一下，在此更新：

<img width="1155" alt="image" src="https://user-images.githubusercontent.com/32434520/192097379-7c23bf6d-f528-4b88-bf77-f9fe281bb7bc.png">

图中提到的套娃问题是刚刚发现并验证的，之前没有考虑到；第二个问题“ipcMain.on从各个renderer收到的消息都会被每一个窗口捕获”不知道是不是Dan老师说的“串了”，这的确是不合适的。

> @erha19 老师，在Electron客户端打开了两个文件夹（两个窗口）测试，的确有这个Bug！我会修复的。

这个测试是这样的：打开两个窗口，拖移其中一个窗口，两个窗口的IPC消息列表中都出现了“ipcRenderer.on”事件。于是我马上回复了“的确有这个Bug！”。但今天在捋思路的时候，我发现了这个：

https://github.com/opensumi/core/blob/ebe8d665eee5db43cfa8c74b74415ed0e28fd1a4/packages/core-electron-main/src/bootstrap/api.ts#L99-L104

opensumi/core中已经存在对Electron API的代理，上面代码是其中的一部分。会遍历app的所有窗口并发送消息，昨天我遇到的是这种情况。所以其实不是我以为的“串了”，而是设计就是这样。Q：为什么要遍历发送消息呢？

以上是关于“消息串了”的一些思考，下一个comment是我的新思路。

2022-09-24 12:52 UTC, tyn1998 commented
新思路：

我认为不要捕获main进程这侧的消息了（ipcMain.on、ipcMain.handle...），在devtools中只呈现renderer侧的消息（ipcRenderer.on、ipcRenderer.send、ipcRenderer.invoke、ipcRenderer.sendSync）。

理由如下：

1. 在RPC消息的呈现中，我们关心的就是客户端这侧的收发消息，服务端的不管的
2. 现在虽然捕获了ipcMain.on和ipcMain.handle的消息，但都是接受的消息，这些消息的内容其实和对应的ipcRenderer.send/invoke/sendSync的内容是一样的，没什么意义
3. 对用户来说，真正有意义的是renderer侧调用ipcRenderer.sendSync/invoke后从main进程得到的返回值——**这反而还没有捕获**

若采用这个新思路，上面的几个requested changes都迎刃而解了。

@yantze @erha19 两位老师怎么看？

2022-09-25 10:02 UTC, tyn1998 commented
以下是新思路下的IPC view：

<img width="1463" alt="image" src="https://user-images.githubusercontent.com/32434520/192137734-b1b55c36-8b59-4aa1-8004-2a6f9fcaf52d.png">

由于core中使用ipcRenderer.sendSync()和ipcRenderer.invoke()基本没有，所以自己本地加了两个测试channel用于测试效果。OpenSumi DevTools那里也做了相应的[修改](https://github.com/opensumi/devtools/pull/5/commits/b556d5e46c2404f971dea7178dcb1430c9f1000e)。

2022-09-26 02:08 UTC, erha19 commented
@tyn1998 新思路可以的，也能减少对于 IPC 和 RPC 的兼容写法，只关注 Browser/Renderer 进程的消息就可以了

2022-09-26 02:19 UTC, yantze commented
ipcRenderer.invoke 之后会有，目前只监听 renderer 侧也可以的

2022-09-26 02:23 UTC, yantze approved these changes

2022-09-26 06:56 UTC, erha19 approved these changes

2022-09-26 06:57 UTC, merged