WIP: Implementation of cross-end and cross-window file system service
opensumi/core pull request #1594
Opened 2022-08-29 15:27 UTC by songhn233

### Types

- [x] 🎉 New Features
- [x] 🐛 Bug Fixes

### Background or solution

Related issue: 
- https://github.com/opensumi/core/issues/1259
- https://github.com/opensumi/core/issues/1556

Close PR: https://github.com/opensumi/core/pull/1384 分支乱了，新开一个（

 - [x] web 复制能力改造
 - [x] electron 复制能力改造
 - [x] web 拖拽能力改造
 - [x] electron 拖拽能力改造
 - [ ] electron Clipboard write/read Buffer
 - [ ] native 与 opensumi 交互增强 https://github.com/opensumi/core/issues/1259#issuecomment-1226015485

**Cross-window copy**

https://user-images.githubusercontent.com/47357585/179896679-0835c0e7-c6aa-4b5f-8189-dc3ad2d60be3.mov

**Cross-window drag and drop**

https://user-images.githubusercontent.com/47357585/179896698-bc98761a-55bb-4643-b1d4-0ab98cc51830.mov

**Electron**

https://user-images.githubusercontent.com/47357585/187236837-37bc9683-371f-45cb-b288-9090fb1d7c89.mov

### Changelog

2022-09-12 12:40 UTC, songhn233 commented
- [x] https://github.com/songhn233/opensumi/pull/8
当使用 clipboard 内容时作为复制文件时弹出 dialog 确认


https://user-images.githubusercontent.com/47357585/189543889-aa912279-cbfa-4961-8ae8-a3937fa52422.mov

2022-09-12 12:52 UTC, songhn233 commented
**native 与 opensumi 交互增强**
- [x] https://github.com/songhn233/opensumi/pull/9

https://user-images.githubusercontent.com/47357585/189546728-73fd8c1d-c6eb-41cf-800a-0c0c8c77c3a4.mov

只支持单个文件的拖拽，出于考虑文件内容不通过 file-service 读取，直接将 文件 uri 作为内容

看了下当前 node 没有提供 create url from file 的后端 api 服务，如果加上的话可以通过 url 进行下载完整内容

2022-09-14 02:53 UTC, erha19 commented
@songhn233 支持 Electron 或 Web 环境下的文件拖拽"复制-粘贴"吗？

2022-09-14 03:03 UTC, erha19 requested changes

2022-09-14 03:03 UTC, erha19 commented on packages/file-tree-next/src/browser/services/file-tree-model.service.ts
> +  private readonly nativeClipboardService: INativeClipboardService;
这里感觉不需要写 `IClipboardService` 和 `INativeClipboardService` 两个 Token 对应不同服务，实际上可以在 Electron 启动代码内通过 DI 覆盖的方式覆盖 `IClipboardService` 实现从而达到在 Electron 下采取不同逻辑处理，这样做有两个好处：

1. 这里不需要在考虑 `isElectronRenderer` 情况，减少维护成本
2. Electron 逻辑在 Electron 逻辑独立处理，减少冗余代码

当前 DI 在注册服务是采取先注册先生效的逻辑，如果不确定服务注册时机，你也可以通过 `injector.overrideProvider` 的方式覆盖实现。

2022-09-14 03:03 UTC, erha19 commented on packages/core-browser/src/services/electron-clipboard.service.ts
> +export class ElectronClipboardService implements INativeClipboardService {
这块代码可以独立放在 Electron 启动逻辑内处理，从代码结构上不适合从 `@opensumi/ide-core-browser` 中导出

2022-09-14 03:25 UTC, songhn233 commented
> @songhn233 支持 Electron 或 Web 环境下 IDE 窗口间的文件拖拽"复制-粘贴"吗？

拖拽应该做的直接就是 move 操作了

2022-09-14 19:08 UTC, songhn233 commented on packages/file-tree-next/src/browser/services/file-tree-model.service.ts
> +  private readonly nativeClipboardService: INativeClipboardService;
之前是想把 clipboard 逻辑直接放在 electron，但是看起来没有注入进去，加上看其他服务也是类似操作的
在 https://github.com/opensumi/core/issues/1259#issuecomment-1229513530 讨论过这个问题

具体来说，看了一下 electron app 这里 injector
https://github.com/opensumi/core/blob/58b998d9e1f721928f576579f16ded46b7505e84/packages/core-electron-main/src/bootstrap/app.ts#L74-L102
这里做 add 或者 overrideProvider 应该是不生效的，我找了一下好像也没看到之前 electron 有这种替换 class 实现的逻辑

2022-09-15 14:34 UTC, erha19 commented on packages/file-tree-next/src/browser/services/file-tree-model.service.ts
> +  private readonly nativeClipboardService: INativeClipboardService;
@songhn233 你这里的代码时在 Electron Main 层运行的代码，覆盖以及注册不了倒是正常的，因为你这里两个 IClipboardService 都是在 Browser 层运行的，覆盖位置可以在这里（Electron Renderer 层） [packages/electron-basic/src/browser/index.ts#L42](https://github.com/opensumi/core/blob/50b22026968bd2119b877621ba5aad955760c7cc/packages/electron-basic/src/browser/index.ts#L42) 处理。

2022-09-23 07:18 UTC, erha19 approved these changes

2022-09-23 07:18 UTC, merged