fix: do not restore task terminal
opensumi/core pull request #1605
Opened 2022-08-30 16:42 UTC by bytemain

### Types

- [x] 🐛 Bug Fixes

### Background or solution

this close: #1531 

### Changelog

- suppress logging exit message twice
- do not restore task terminal

2022-08-30 16:43 UTC, bytemain commented
上个PR #1528 没有修复掉退出信息打印两次，这个应该真的修掉了。

2022-08-30 16:45 UTC, bytemain commented
https://github.com/opensumi/core/discussions/1606

2022-08-31 03:10 UTC, erha19 requested changes

2022-08-31 03:10 UTC, erha19 commented on packages/task/src/browser/task.schema.ts
> +      description: localize('JsonSchema.version', "The config's version number.12"),
这里的 12 是多写了？

2022-08-31 03:14 UTC, bytemain commented on packages/task/src/browser/task.schema.ts
> +      description: localize('JsonSchema.version', "The config's version number.12"),
我测了一下这个 localize 是否生效，忘记删了

2022-08-31 06:57 UTC, erha19 approved these changes

2022-08-31 06:57 UTC, merged