Update README-zh_CN.md
opensumi/core pull request #164
Opened 2021-12-21 02:30 UTC by fattydevelop

fix: use new taobao registry

### 变动类型

- [x] 文档改进

### 需求背景和解决方案
registry.taobao 域名即将更换
### changelog

2021-12-21 02:32 UTC, erha19 approved these changes
Thanks, LGTM

2021-12-21 02:37 UTC, fattydevelop commented
遗漏一处，重新提了一个PR

2021-12-21 03:35 UTC, erha19 commented
@fattydevelop  冲突处理一下

2021-12-21 10:15 UTC, lengthmin requested changes

2021-12-21 10:15 UTC, lengthmin commented on README-zh_CN.md
> +$ npm install --canvas_binary_host_mirror=https://registry.npmmirror.com/mirrors/node-canvas-prebuilt/
```diff
- https://registry.npmmirror.com
+ https://npmmirror.com
```

2021-12-22 03:37 UTC, lengthmin commented
为什么我 merge 了一下 main，就没有 file change 了

2021-12-22 03:40 UTC, lengthmin commented
看了一下，这部分内容已经合并进了 main，这个就先 close 了

2021-12-22 03:40 UTC, closed without merging