fix: create files with options take the content
opensumi/core pull request #1648
Opened 2022-09-09 04:30 UTC by samyzh

### Types
- [ ] 🐛 Bug Fixes

### Changelog
放开功能，创建文件时，可选携带内容文件

2022-09-09 04:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/opensumi/core?pullRequest=1648) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/opensumi/core?pullRequest=1648) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/opensumi/core?pullRequest=1648) it.</sub>

2022-09-13 01:51 UTC, erha19 requested changes

2022-09-13 01:51 UTC, erha19 commented on packages/file-tree-next/src/browser/services/file-tree-api.service.ts
> +  async createFile(uri: URI,content:string) {
这里的 `,` 后少了一个空格

2022-09-13 01:51 UTC, erha19 commented on packages/file-tree-next/src/browser/services/file-tree-api.service.ts
> +            options: {content},
前后也少了空格

2022-09-13 01:51 UTC, erha19 commented
@samyzh 感谢贡献 ~ 麻烦签署一下 CLA 协议方便我们合并代码 https://github.com/opensumi/core/pull/1648#issuecomment-1241486464

2022-09-13 02:35 UTC, samyzh commented on packages/file-tree-next/src/browser/services/file-tree-api.service.ts
> +  async createFile(uri: URI,content:string) {
ok, 我修改下

2022-09-13 10:06 UTC, erha19 submitted a review, later dismissed
LGTM

2022-09-13 10:06 UTC, erha19 commented
/publish

2022-09-13 10:17 UTC, erha19 commented
@samyzh 你这个修改没有通过语法校验，需要修一下

![image](https://user-images.githubusercontent.com/9823838/189876401-ed4c5e01-7f15-4adf-b3f3-c9e30e9cb9d2.png)

2022-09-15 14:58 UTC, merged