feat: toolbar dropdown-button contribute
opensumi/core pull request #1753
Opened 2022-10-09 03:43 UTC by hacke2

### Types

- [x] 🎉 New Features

### Background or solution

```
"kaitianContributes": {
    "toolbar": {
      "actions": [
        {
          "type": "dropdownButton",
          "id": "common-start",
          "command": "common-start.select",
          "options": [
            {
              "label": "运行",
              "value": "run"
            },
            {
              "label": "调试",
              "value": "debug"
            }
          ]
        }
      ]
    }
  },
```

![image](https://user-images.githubusercontent.com/6399899/194736818-d69461a6-53d7-4053-b123-c91268e48405.png)

### Changelog
Add DropdownButton Component
Add DropdownButton Toolbar contribute

2022-10-13 09:24 UTC, erha19 requested changes

2022-10-13 09:24 UTC, erha19 commented on packages/extension/src/browser/sumi/main.thread.toolbar.ts
> +          'sumi-extension.toolbar.dropdownButton.onSelect',
这里类似 `sumi-extension.toolbar.dropdownButton.onSelect` 的 Event 参数是不是可以统一到一个变量的地方维护？

2022-10-13 09:24 UTC, erha19 commented on packages/extension/src/common/sumi/toolbar.ts
> +} from '../../browser/sumi/types';
这里在 common 里面 import  browser 代码是不是不太合理？

2022-10-13 09:24 UTC, erha19 commented on packages/extension/src/hosted/api/sumi/ext.host.toolbar.ts
> +} from '../../../browser/sumi/types';
结合上面代码，这里基础声明感觉放到 common 中更合适。

2022-10-13 09:24 UTC, erha19 commented on packages/extension/src/hosted/api/sumi/ext.host.toolbar.ts
> +      case 'button':
这里的 type 值类型感觉也可以通过对象变量去维护，'type' 值目前感觉比较宽泛，可以用 'button' | 'dropdownButton' 约束一下

2022-10-13 09:24 UTC, erha19 commented on packages/extension/src/hosted/api/sumi/ext.host.toolbar.ts
> +    private kaitianCommon: ExtHostCommon,
这里既然改到了，顺带把 `kaitian` 这个老写法改掉吧。感觉直接改成 extHostCommon 就行了

2022-10-19 11:30 UTC, hacke2 commented on packages/extension/src/hosted/api/sumi/ext.host.toolbar.ts
> +      case 'button':
![image](https://user-images.githubusercontent.com/6399899/196679015-00781805-edc7-4637-85bf-2dc5ab749abb.png)

现在其实有约束的

2022-10-19 11:33 UTC, hacke2 commented on packages/extension/src/common/sumi/toolbar.ts
> +} from '../../browser/sumi/types';
这个感觉比较难移，里面确实依赖了前端的模块。。

2022-12-27 06:38 UTC, closed without merging