优化部分启动逻辑
opensumi/core pull request #1772
Opened 2022-10-11 11:22 UTC by Aaaaash

### Types

- [x] 🚀 Performance Improvements

### Background or solution

### Changelog

2022-10-11 11:22 UTC, Aaaaash commented on packages/core-browser/src/services/storage-service.ts
> +      runWhenIdle(() => {
清理 localStorage 逻辑可以稍后执行

2022-10-11 11:23 UTC, Aaaaash commented on packages/editor/src/browser/editor.view.tsx
> +        runWhenIdle(() => {
首屏的 diffEditor 在空闲时创建

2022-10-11 11:24 UTC, Aaaaash commented on packages/file-service/src/browser/file-service-contribution.ts
> +        contrib.onFileServiceReady && contrib.onFileServiceReady();
fsContribution 的钩子方法并行执行，避免被其他 contribution 的逻辑阻塞

2022-10-11 11:25 UTC, Aaaaash commented on packages/keymaps/src/browser/keymaps.service.ts
> +      runWhenIdle(() => {
延迟更新快捷键绑定

2022-10-11 11:25 UTC, Aaaaash commented on packages/output/src/browser/output.view.tsx
> +      const handler = layoutService.getTabbarHandler(OUTPUT_CONTAINER_ID);
视图隐藏时默认不创建 outoutEditor

2022-10-11 11:25 UTC, Aaaaash commented
/publish

2022-10-11 11:50 UTC, bytemain commented
特别棒

2022-10-14 08:53 UTC, Aaaaash commented
/publish

2022-10-14 09:01 UTC, life2015 commented on packages/connection/src/common/message.ts
> +  export function replacer(key: string | undefined, value: any) {
这个会优化Buffer场景下 JSON parse的性能吗？

2022-10-14 09:03 UTC, life2015 commented on packages/core-browser/src/logger/browser-logger.ts
> +    // return this.logger.verbose(...args);
这里为什么要注掉？

2022-10-14 09:33 UTC, Aaaaash commented
/publish

2022-10-14 09:34 UTC, Aaaaash commented on packages/core-browser/src/logger/browser-logger.ts
> +    // return this.logger.verbose(...args);
测试

2022-10-17 02:05 UTC, Aaaaash commented
/publish

2022-10-17 03:19 UTC, erha19 commented
@Aaaaash 冲突处理一下

2022-10-17 05:58 UTC, Aaaaash commented
/publish

2022-10-18 06:50 UTC, Aaaaash commented on packages/connection/src/common/message.ts
> +  export function replacer(key: string | undefined, value: any) {
实际不会，只是为了规范性写法，但是为了避免 bk 我先去掉了

2022-10-19 01:52 UTC, erha19 requested changes

2022-10-19 01:52 UTC, erha19 commented on package.json
> +    "uWebSockets.js": "uNetworking/uWebSockets.js#v20.10.0",
这下面两个依赖好像没地方用到

2022-10-19 02:59 UTC, Ricbet commented
这个改动看起来蛮大的，放在 2.21 ？

2022-10-19 03:08 UTC, Aaaaash commented
> 这个改动看起来蛮大的，放在 2.21 ？

不算很大，2.21 的话准备重构一下

2022-10-24 02:06 UTC, Aaaaash commented
/publish

2022-10-25 07:55 UTC, erha19 approved these changes

2022-10-25 08:04 UTC, Aaaaash commented on packages/core-browser/src/bootstrap/inner-providers.ts
> +      token: AppLifeCycleServiceToken,
因为这个 class 太简单，没有 interface，叫 IAppLifeCycleService 会很奇怪

2022-10-26 01:46 UTC, Aaaaash commented
/publish

2022-10-26 10:15 UTC, erha19 approved these changes

2022-10-27 03:05 UTC, life2015 commented
优秀的优化  期待部署效果

2022-10-27 03:13 UTC, erha19 approved these changes

2022-10-27 03:15 UTC, life2015 submitted a review, later dismissed
LGTM

2022-10-27 07:44 UTC, erha19 approved these changes

2022-10-27 07:45 UTC, merged