Test/implement go to defination by cmd click
opensumi/core pull request #1786
Opened 2022-10-13 05:44 UTC by Ricbet

### Types

- [x] ⏱ Tests

### Background or solution

### Changelog
新增 "通过鼠标 Go To Defination" 的 e2e 测试

2022-10-13 08:36 UTC, erha19 commented
@Ricbet  看一下，这个修改会导致其他测试挂掉
<img width="950" alt="image" src="https://user-images.githubusercontent.com/9823838/195546121-ab5eb46f-96f5-46af-acb6-bba6ade50f2d.png">

2022-10-18 09:06 UTC, Aaaaash submitted a review, later dismissed

2022-10-18 09:12 UTC, erha19 requested changes
这个目前是有报错的

2022-10-28 08:28 UTC, Ricbet commented
> 这个目前是有报错的

CI 过了

2022-10-31 02:18 UTC, erha19 approved these changes

2022-10-31 02:18 UTC, merged