feat: intranet resource config
opensumi/core pull request #1808
Opened 2022-10-19 06:41 UTC by Ricbet

### Types

- [x] 🎉 New Features

### Background or solution

### Changelog
新增 extensionBrowserStyleSheet Config，支持配置插件 browser 层的样式表文件

2022-10-19 06:52 UTC, Ricbet commented
/publish

2022-10-20 01:58 UTC, erha19 approved these changes

2022-10-20 02:13 UTC, erha19 requested changes

2022-10-20 02:13 UTC, erha19 commented on packages/core-common/src/types/extension.ts
> +  componentUri: string;
这里的 `componentUri` 以及 `iconfontUri` 有啥参考案例吗？

2022-10-20 02:15 UTC, erha19 commented on packages/core-common/src/types/extension.ts
> +  componentUri: string;
这个跟 Browser 环境下的 `iconStyleSheets` 会不会有影响，会不会相互冲突？

2022-10-20 02:27 UTC, Ricbet commented on packages/core-common/src/types/extension.ts
> +  componentUri: string;
不会，这是给插件 browser 层用的，是在 shadowRoot 下渲染的

2022-10-20 02:30 UTC, Ricbet commented on packages/core-common/src/types/extension.ts
> +  componentUri: string;
> 这里的 `componentUri` 以及 `iconfontUri` 有啥参考案例吗？

内部有需求是需要一个纯内网环境下运行 opensumi，这两个样式文件是放在 cdn 上的，所以需要支持可配置

2022-10-20 02:32 UTC, erha19 commented on packages/core-common/src/types/extension.ts
> +  componentUri: string;
这个配置 `iconStyleSheets` 也是给插件进程 ShadowRoot 提供 Icon 的配置文件以及自定义前缀定义，这块不会跟你这里的 iconfontUri 功能有一些重复吗？感觉  `iconStyleSheets`  的定义方式能满足 iconfont 定义的场景，看一下这里的用法
https://github.com/opensumi/core/blob/1e19624ab596794f92625c59a53cf726dba4666e/packages/components/README.md#usage

2022-10-20 02:34 UTC, erha19 commented on packages/core-common/src/types/extension.ts
> +  componentUri: string;
> 内部有需求是需要一个纯内网环境下运行 opensumi，这两个样式文件是放在 cdn 上的，所以需要支持可配置

懂了 ... 那我理解错了

2022-10-20 02:36 UTC, erha19 approved these changes

2022-10-20 02:36 UTC, merged