WIP: feat: implement walkthroughs contribution API
opensumi/core pull request #1902
Opened 2022-11-02 09:02 UTC by Ricbet

### Types

- [x] 🎉 New Features

### Background or solution

### Changelog
实现 walkthroughs contribution API

2022-11-04 07:18 UTC, Ricbet commented
- [x] 基础 walkthroughs 贡献点渲染（标题、step、media）
- [x] step description 渲染并支持 command、when
- [x] media image 渲染
- [x] media svg 渲染
- [ ] media svg command 事件处理
- [ ] media markdown 渲染（需支持资源以相对路径的方式打开）
- [ ] completionEvents 机制（例如当用户做了某些操作之后给当前 step 设置成 completion 的状态，也就是会在左边的 checkbox 打勾勾）
- [x] 主题适配

2022-11-07 05:49 UTC, Ricbet commented
> * [x]  基础 walkthroughs 贡献点渲染（标题、step、media）
> * [x]  step description 渲染并支持 command、when
> * [x]  media image 渲染
> * [x]  media svg 渲染
> * [ ]  media svg command 事件处理
> * [x]  media markdown 渲染（需支持资源以相对路径的方式打开）
> * [x]  completionEvents 机制（例如当用户做了某些操作之后给当前 step 设置成 completion 的状态，也就是会在左边的 checkbox 打勾勾）
> * [x]  主题适配

针对 media svg 的 command 事件处理和 color token 另开 pr 解决
相关 issue：https://github.com/opensumi/core/issues/1928

2022-11-08 02:33 UTC, Ricbet commented
/publish

2022-11-10 02:22 UTC, erha19 requested changes

2022-11-10 02:22 UTC, erha19 commented on packages/core-browser/src/utils/iconLabels.tsx
> +export function renderLabelWithIcons(text: string): Array<React.ReactElement | string> {
这里考虑复用一下吧，可以用一下这里的 https://github.com/opensumi/core/blob/fbb5ce9e7613898255a8ba82dc730b6fe5890ec4/packages/core-browser/src/utils/label.tsx , 后续支持 `~spin` 语法省事一点

2022-11-10 02:22 UTC, erha19 commented on packages/extension/src/browser/components/walkthroughs-view.tsx
> +  }, [walkthrough]);
这里少了 `currentStepId`

2022-11-10 02:22 UTC, erha19 commented on packages/extension/src/browser/components/walkthroughs-view.tsx
> +    if (href.startsWith('https://') || href.startsWith('http://')) {
这里感觉用一句正则优雅一点 `/^http(s)?:/.test`

2022-11-10 02:22 UTC, erha19 commented on packages/extension/src/browser/walkthroughs.service.ts
> +        case 'onLink':
这里的 Type 建议都用常量管理

2022-11-10 02:22 UTC, erha19 commented on packages/extension/src/browser/walkthroughs.service.ts
> +        this.logger.error(`无法处理 step 为 ${step.id} 的 completionEvent 事件: ${event}`);
没 i18n 的情况下，报错用英文吧

2022-11-10 02:22 UTC, erha19 commented on packages/extension/src/browser/walkthroughs.service.ts
> +            this.logger.error(`无法解析 step 为 ${step.id} 的 context: ${expression}`);
报错信息改成英文吧

2022-11-10 03:12 UTC, Ricbet commented on packages/extension/src/browser/components/walkthroughs-view.tsx
> +  }, [walkthrough]);
这里就是需要判断 currentStepId 是否为 undefined 的

2022-11-10 03:29 UTC, Ricbet commented on packages/extension/src/browser/walkthroughs.service.ts
> +  public async registerExtensionWalkthroughContributions(
测试后面再搞吧，现在 extension 模块下还没有 contribution 的测试

2022-11-10 03:43 UTC, erha19 commented on packages/extension/src/browser/components/walkthroughs-view.tsx
> +  }, [walkthrough]);
我的意思是 `[walkthrough]  -> [walkthrough, currentStepId]`

2022-11-10 03:45 UTC, Ricbet commented on packages/extension/src/browser/walkthroughs.service.ts
> +        this.logger.error(`无法处理 step 为 ${step.id} 的 completionEvent 事件: ${event}`);
logger 信息都是程序日志，不会展示在前端，应该不影响吧

2022-11-10 03:58 UTC, erha19 commented on packages/extension/src/browser/walkthroughs.service.ts
> +        this.logger.error(`无法处理 step 为 ${step.id} 的 completionEvent 事件: ${event}`);
之前约定是没有做 i18n 的情况下，默认用英文，这样对于海内外用户都比较友好

2022-11-10 04:04 UTC, erha19 commented on packages/extension/src/browser/walkthroughs.service.ts
> +export class WalkthroughsService extends Disposable {
可以只写一下这个文件的测试，另外有个空文件 `packages/extension/src/common/walkthroughs.service.ts`

2022-11-24 08:21 UTC, erha19 commented
@Ricbet 这个修一下，补点测试

2022-11-28 02:28 UTC, erha19 requested changes

2022-11-28 02:28 UTC, erha19 commented on packages/core-browser/src/utils/iconLabels.tsx
> +        <span className={getExternalIcon(codicon)}></span>
这里没有设置 key，可能会出现 React 警告，而且上面应该可以直接用 `transformLabelWithCodicon` 方法来处理 text, 不需要自己在用正则来处理了才对？

2022-11-28 02:30 UTC, erha19 commented on packages/core-browser/src/utils/iconLabels.tsx
> +        <span className={getExternalIcon(codicon)}></span>
@Ricbet  再看下这里

2022-11-28 03:30 UTC, Ricbet commented on packages/core-browser/src/utils/iconLabels.tsx
> +        <span className={getExternalIcon(codicon)}></span>
我把这个文件删了吧，这里是从原先的 https://github.com/opensumi/core/pull/1902/files#diff-0fcadb6d79646a439a0d31c5e368a121f87ec7632428c122dba70d34859f0f45L14 这个地方拷贝出来的

2022-11-28 08:02 UTC, erha19 approved these changes

2022-11-28 08:02 UTC, merged