feat: support opentrs extension marketplace
opensumi/core pull request #1933
Opened 2022-11-07 09:25 UTC by bk1012

### Types
- [x] 🎉 New Features

### Background or solution
增加对 https://marketplace.opentrs.com opentrs 插件市场的支持

### Changelog
feat: support opentrs extension marketplace

2022-11-07 09:27 UTC, erha19 commented on scripts/download.js
>  const api = 'https://open-vsx.org/api/';
download 脚本可以冲 TRS 插件市场里面装插件吗？

2022-11-07 09:29 UTC, erha19 requested changes

2022-11-07 09:29 UTC, erha19 commented on packages/extension-manager/src/node/vsx-extension.service.ts
> +import { DEFAULT_OPENVSX_REGISTRY, DEFAULT_TRS_REGISTRY } from '@opensumi/ide-core-common/lib/const';
`DEFAULT_TRS_REGISTRY` 引入了，但好像没地方使用？

2022-11-07 09:33 UTC, bk1012 commented on scripts/download.js
>  const api = 'https://open-vsx.org/api/';
> download 脚本可以冲 TRS 插件市场里面装插件吗？

download 脚本装 trs 插件市场的插件？这个需要改造下 download 脚本，configs/vscode-extensions.json 这里面的一些配置是跟 open-vsx 强相关的

2022-11-08 02:35 UTC, bk1012 commented on scripts/download.js
>  const api = 'https://open-vsx.org/api/';
download 脚本可以下载 TRS 的插件了，不过需要设置对应的 type 及 ak

2022-11-08 11:57 UTC, hacke2 commented on packages/extension-manager/src/node/marketplace/opentrs-marketplace.ts
> +    this.downloadHeaders = this.getAKHeaders();
这里漏加了 x-download-mode、x-framework-version 这两个比较关键

2022-11-08 11:59 UTC, hacke2 commented on packages/extension-manager/src/node/marketplace/opentrs-marketplace.ts
> +export class OpentrsMarketplaceImpl extends AbstractMarketplace {
用 DI 装饰一下

2022-11-08 11:59 UTC, hacke2 commented on packages/extension-manager/src/node/vsx-extension.service.ts
> +        ? new OpenvsxMarketplaceImpl(marketplaceConfig)
不要自己 new，用 DI

2022-11-17 08:06 UTC, erha19 requested changes

2022-11-17 08:06 UTC, erha19 commented on packages/extension-manager/src/common/index.ts
> +export const OpentrsMarketplaceToken = Symbol('OpentrsMarketplaceToken');
这里按框架内的规范，最好的方式是 Token + Interface + Implement，比较建议命名成 `IOpentrsMarketplaceService` 即作为 Token，同时声明一个 `IMarketplaceService` 的定义作为公共接口定义，让 `AbstractMarketplace implements IMarketplaceService`.

2022-11-17 08:06 UTC, erha19 commented on scripts/download.js
> +const marketplaceType = process.env.MARKETPLACE ?? 'openvsx';
这里 Download 脚本还是要处理一下，最好还是默认用我们的插件市场服务，这样减少由于下载插件用的  OpenVSX，管理插件用的 OpenTRS 导致的不一致或需要额外处理的情况。

2022-11-17 08:06 UTC, erha19 commented on packages/core-node/src/bootstrap/app.ts
> +          accountId: 'clcJKq_Gea47whxAJGrgoYqf',
这里的 AK 还是统一到一个常量配置里面维护吧，例如 DEFAULT_TRS_REGISTRY.ACCOUND_ID 之类的

2022-11-21 02:39 UTC, erha19 commented on scripts/download.js
> +    // 解压插件，使用 opentrs 插件时解压缩容易出错，因此这里加一个重试逻辑
这里解压缩容易出错的具体原因定位到了吗？目前修改完还是不能将 `marketplace.opentrs.com` 作为默认的插件源吗？

2022-11-21 03:17 UTC, bk1012 commented on scripts/download.js
> +    // 解压插件，使用 opentrs 插件时解压缩容易出错，因此这里加一个重试逻辑
目前默认的插件源就是 marketplace.opentrs.com 啊

2022-11-21 03:19 UTC, erha19 commented on scripts/download.js
> +    // 解压插件，使用 opentrs 插件时解压缩容易出错，因此这里加一个重试逻辑
我看到上面有这句 `const marketplaceType = process.env.MARKETPLACE ?? 'opentrs'; ` 是不是代表的默认情况不带 MARKETPLACE 执行情况下还是用的 OpenVSX 源？

2022-11-21 06:05 UTC, bk1012 commented on scripts/download.js
> +    // 解压插件，使用 opentrs 插件时解压缩容易出错，因此这里加一个重试逻辑
这里不是写的 opentrs 么，不是 openVSX 啊

2022-11-21 06:33 UTC, erha19 approved these changes
LGTM，后面记得补上测试

2022-11-21 06:33 UTC, merged