chore: upgrade typescript version to 4.9.+
opensumi/core pull request #1996
Opened 2022-11-21 13:55 UTC by erha19

### Types

- [x] 🏗️ Build System

### Background or solution

升级 `typescript` 版本至 4.9+，从而支持 `"moduleResolution": "nodenext",` ，进而支持动态 import 能力。

相关 PR [#43329](https://github.com/microsoft/TypeScript/issues/43329)。

### Changelog

upgrade typescript version to 4.9.+

2022-11-28 04:02 UTC, erha19 commented
移除了 `@opensumi/ide-core-browser` 中对于 `bootstrap/app.ts` 的默认导出，该导出会引起测试代码的大量内存泄漏问题，带来 BreakingChanges 如下：
```diff
- import { ClientApp } from '@opensumi/ide-core-browser';
// 需要修改为下面引入方式
+ import { ClientApp } from '@opensumi/ide-core-browser/lib/bootstrap/app';
```

同时移除了框架内存留的部分对于 `uuid` 幽灵依赖的引入，统一使用 `@opensumi/ide-core-common` 内导出的 `uuid` 方法。

2022-11-28 04:04 UTC, erha19 commented
同时追加配置，后续 GitHub Actions 中日志将不再输出代码内的 `console.*` ，方便问题被快速发现

2022-12-05 10:16 UTC, bytemain requested changes

2022-12-05 10:16 UTC, bytemain commented on packages/collaboration/__tests__/browser/textmodel-binding.test.ts
> +  // @ts-ignore
这个 ignore 的是什么？

2022-12-05 13:00 UTC, merged