WIP: refactor: 重构创建 Terminal 流程
opensumi/core pull request #200
Opened 2021-12-23 14:24 UTC by lengthmin

### 变动类型

- [x] 重构

### 需求背景和解决方案

### changelog

2021-12-27 06:32 UTC, erha19 requested changes

2021-12-27 06:32 UTC, erha19 commented on packages/extension/webpack.config.worker.js
> +/** @type { import('webpack').Configuration } */
这句加了有用吗?

2021-12-27 06:32 UTC, erha19 commented on packages/terminal-next/src/node/pty.ts
> +    try {
这段如果引用自 VS Code 的话加个版头吧

2021-12-27 06:40 UTC, erha19 commented
测试也要补充一下，非 feat 和 refactor 都是需要保证测试的

2021-12-27 06:40 UTC, Aaaaash commented on packages/extension/webpack.config.worker.js
> +/** @type { import('webpack').Configuration } */
有的..

2021-12-27 07:42 UTC, Aaaaash approved these changes
LGTM

2021-12-28 06:25 UTC, erha19 approved these changes
LGTM

2021-12-28 06:25 UTC, merged