feat: diagnostic support display code href
opensumi/core pull request #2056
Opened 2022-12-06 15:10 UTC by bytemain

### Types

- [x] 🎉 New Features

### Background or solution

诊断的 code 可以传一个对象：`{ value: string, target: URI }`

target 会渲染在这个地方：
![CleanShot 2022-12-06 at 23 24 37@2x](https://user-images.githubusercontent.com/13938334/205952996-e9a567db-bb25-4810-a83f-81df9f4fa5d2.png)

同时问题面板也支持渲染：
![CleanShot 2022-12-06 at 23 25 55@2x](https://user-images.githubusercontent.com/13938334/205953135-e861a3bb-1dd5-4364-bcdc-6f015b8ab72e.png)

### Changelog

extension api `language.Diagnostic` support code href.
problem panel support display code href.

2022-12-09 06:17 UTC, erha19 commented on packages/core-common/src/problem-pattern.ts
> +  if (typeof a === 'undefined' && typeof b === 'undefined') {
这个方法补点测试吧

2022-12-09 06:23 UTC, bytemain commented on packages/markers/src/browser/markers-tree.view.tsx
> +          <MarkerCode data={data.code} href={data.codeHref} />
这里这么写的话，如果命中 codeMatches，code 那部分就没有点击链接了。

2022-12-12 02:47 UTC, erha19 approved these changes

2022-12-12 02:48 UTC, erha19 requested changes

2022-12-12 02:48 UTC, erha19 commented on packages/core-common/__tests__/problem-pattern.test.ts
> +        target: 'https://antgroup.com',
这里的链接替换成 `opensumi.com` 吧

2022-12-12 02:48 UTC, erha19 commented on packages/core-common/__tests__/types/markers/markers-manager.test.ts
> +  const testUri = URI.parse('https://antgroup.com');
这里也是..

2022-12-13 03:25 UTC, erha19 approved these changes

2022-12-13 03:25 UTC, merged