feat: improve preference panel
opensumi/core pull request #2089
Opened 2022-12-15 13:35 UTC by bytemain

### Types

- [ ] 🎉 New Features
- [ ] 🐛 Bug Fixes
- [ ] 📚 Documentation Changes
- [ ] 💄 Code Style Changes
- [ ] 💄 Style Changes
- [ ] 🪚 Refactors
- [ ] 🚀 Performance Improvements
- [ ] 🏗️ Build System
- [ ] ⏱ Tests
- [ ] 🧹 Chores
- [ ] Other Changes

### Background or solution

### Changelog

2022-12-22 14:25 UTC, erha19 requested changes

2022-12-22 14:42 UTC, bytemain commented on packages/components/src/markdown/render.tsx
> +      className='md-renderer-wrap'
对，没有对应的样式选择器，但是写个这个在调试的时候看出来是由该组件渲染出来的

2022-12-22 14:43 UTC, bytemain commented on packages/preferences/src/common/types.ts
> +  _path?: string;
在上下滚动右边的选项列表的时候，靠这个来高亮左边的文件树。

2022-12-23 01:56 UTC, erha19 approved these changes
LGTM

2022-12-23 01:56 UTC, merged