fix: quick open argument
opensumi/core pull request #2117
Opened 2022-12-24 12:41 UTC by Aaaaash

### Types

- [x] 🐛 Bug Fixes

### Background or solution

### Changelog

2022-12-25 05:11 UTC, erha19 requested changes

2022-12-25 05:11 UTC, erha19 commented on packages/quick-open/src/browser/quick-open.contribution.ts
> +      execute: () => this.prefixQuickOpenService.open('>'),
https://github.com/opensumi/core/blob/75511a4849d2dde6936616bccd3c8d987326d62f/packages/main-layout/src/browser/main-layout.contribution.ts#L333 有依赖

2022-12-26 01:41 UTC, Aaaaash commented on packages/quick-open/src/browser/quick-open.contribution.ts
> +      execute: () => this.prefixQuickOpenService.open('>'),
那可能这个实现是错的，右键菜单的 command palette 也会传如一个 uri，但参数并不支持这种形式，导致右键菜单无法打开 quickOpen

2022-12-26 01:47 UTC, Aaaaash commented on packages/quick-open/src/browser/quick-open.contribution.ts
> +      execute: () => this.prefixQuickOpenService.open('>'),
这里改了一下，新增了一个 openview 命令，不依赖这个 open 了

2022-12-26 04:01 UTC, erha19 approved these changes

2022-12-26 04:01 UTC, merged