refactor: use nsfw on linux
opensumi/core pull request #2154
Opened 2023-01-03 07:10 UTC by Ricbet

### Types

- [x] 🪚 Refactors

### Background or solution

### Changelog
在 Linux 中使用 nsfw 来做文件 watcher

2023-01-05 07:01 UTC, hacke2 commented
切回 nsfw 要加上这个逻辑，否则在 linux 监听会漏掉事件 https://github.com/opensumi/core/commit/5b4ff00a6e21ba8bd0c223bdd05dca95792b0a49

2023-01-05 07:24 UTC, Ricbet commented
> 

是有的

2023-01-10 06:51 UTC, erha19 requested changes

2023-01-10 06:51 UTC, erha19 commented on packages/extension/webpack.config.ext-host.js
> +      if (['node-pty', 'nsfw', '@parcel/watcher', 'spdlog', 'electron'].indexOf(request) !== -1) {
这里在集成侧都需要修改，补一下 BreakingChange 文档吧，可以说明一下修改原因  https://github.com/opensumi/core/blob/main/CHANGELOG.md

2023-01-11 12:18 UTC, erha19 requested changes

2023-01-11 12:18 UTC, erha19 commented on packages/file-service/src/node/file-service-watcher.ts
> +import nsfw from 'nsfw';
这里如果采用直接 import 的方式，会在 Mac 和 Windows 环境下引入额外不必要的原生模块依赖，感觉还是不能直接 import，可能得看一下 Jest 如何测试含 Dynamic import 的代码

2023-01-11 12:18 UTC, erha19 commented on packages/extension/webpack.config.ext-host.js
> +      if (['node-pty', 'nsfw', '@parcel/watcher', 'spdlog', 'electron'].indexOf(request) !== -1) {
这里的文档没有加

2023-02-08 03:53 UTC, Ricbet commented on packages/file-service/src/node/file-service-watcher.ts
> +import nsfw from 'nsfw';
done

2023-02-08 03:54 UTC, Ricbet commented on packages/extension/webpack.config.ext-host.js
> +      if (['node-pty', 'nsfw', '@parcel/watcher', 'spdlog', 'electron'].indexOf(request) !== -1) {
ok

2023-02-10 02:29 UTC, merged