fix: settings.json should be jsonc
opensumi/core pull request #2181
Opened 2023-01-10 08:03 UTC by bytemain

### Types

- [x] 🐛 Bug Fixes

### Background or solution

close: #1385 

### Changelog

settings.json will be considered as `jsonc` language

2023-01-10 08:44 UTC, erha19 requested changes

2023-01-10 08:44 UTC, erha19 commented on packages/file-scheme/src/browser/file-doc.ts
> +        return 'jsonc';
除了这个类型，还有一个 `log` 类型也很常用，是不是用个变量统一管理起来？

2023-01-10 08:54 UTC, bytemain commented on packages/file-scheme/src/browser/file-doc.ts
> +        return 'jsonc';
是说把 jsonc 用一个常量表示吗？

2023-01-10 08:56 UTC, erha19 commented on packages/file-scheme/src/browser/file-doc.ts
> +        return 'jsonc';
类似 `LANGUAGE_TYPES = { JSONC: 'jsonc', LOG: 'log'}`

2023-01-11 07:52 UTC, erha19 commented on packages/utils/src/objects.ts
> +export function cloneAndChangeByKV(obj: any, changer: (key: string, orig: any) => any): any {
这个方法加个测试吧

2023-01-11 12:22 UTC, erha19 approved these changes

2023-01-11 12:54 UTC, merged