feat(status-bar): do not display info icon if there is no info
opensumi/core pull request #2182
Opened 2023-01-10 08:06 UTC by bytemain

### Types

- [x] 🎉 New Features

### Background or solution

### Changelog

do not display info icon if there is no info

2023-01-10 08:32 UTC, erha19 requested changes

2023-01-10 08:32 UTC, erha19 commented on packages/markers/src/browser/markers-contribution.ts
> +        text: iconTexts.filter(Boolean).join(' '),
这里这么写起不到过滤效果吧？

2023-01-11 06:57 UTC, bytemain commented on packages/markers/src/browser/markers-contribution.ts
> +        text: iconTexts.filter(Boolean).join(' '),
这个 filter 确实没用，忘记删掉了

2023-01-11 07:51 UTC, erha19 approved these changes

2023-01-11 07:51 UTC, merged