fix: resizeObserver unobserve error
opensumi/core pull request #2183
Opened 2023-01-10 08:23 UTC by AhkunTa

### Types

- [ x ] 🐛 Bug Fixes

### Background or solution
<img width="829" alt="截屏2023-01-10 15 51 45" src="https://user-images.githubusercontent.com/31676999/211498573-7f1018e1-2f0c-4e11-bb51-05b824ce0974.png">

### Changelog

2023-01-10 08:24 UTC, AhkunTa commented
/publish

2023-01-10 08:55 UTC, bytemain requested changes

2023-01-10 08:55 UTC, bytemain commented on packages/core-browser/src/layout/layout-hooks.ts
>        resizeObserver.observe(containerRef.current);
这里是不是也得判断下再 observe

2023-01-11 03:56 UTC, AhkunTa commented on packages/core-browser/src/layout/layout-hooks.ts
>        resizeObserver.observe(containerRef.current);
> 这里是不是也得判断下再 observe

应该不用 问题出在作为组件嵌入时 当组件销毁时dispose报错 初始化时应该没有这个问题

2023-01-11 03:57 UTC, bytemain requested changes

2023-01-11 03:57 UTC, bytemain commented on packages/core-browser/src/layout/layout-hooks.ts
>        resizeObserver.observe(containerRef.current);
44 行都得判断，这一行为什么不用判断？只是因为 observe 传了 undefined 没报错而已吧

2023-01-11 03:59 UTC, erha19 approved these changes

2023-01-11 03:59 UTC, erha19 commented on packages/core-browser/src/layout/layout-hooks.ts
>        resizeObserver.observe(containerRef.current);
上面一点的代码有相应判断，这里应该是没问题的 https://github.com/opensumi/core/blob/df680e662bb52a381f02c6c237a3c903d07890d2/packages/core-browser/src/layout/layout-hooks.ts#L44

2023-01-11 04:00 UTC, hacke2 commented
注册的时候有，不一定代表卸载的时候有，这个问题出现在切换极速版组件的情况下

2023-01-11 06:22 UTC, bytemain approved these changes

2023-01-11 06:26 UTC, merged