WIP: feat: add cli engine
opensumi/core pull request #2210
Opened 2023-01-18 03:21 UTC by bk1012

### Types

- [x] 🎉 New Features

### Background or solution

### Changelog

2023-01-28 09:00 UTC, bk1012 commented
/publish

2023-01-30 09:41 UTC, erha19 requested changes

2023-01-30 09:41 UTC, erha19 commented on tools/cli-engine/.gitignore
> +.yarn
这个文件好像有点多余，直接复用全局的 `.gitignore` 文件应该就可以了

2023-01-30 09:41 UTC, erha19 commented on tools/cli-engine/.npmrc
> +package-lock=false
这个文件也有点多余

2023-01-30 09:41 UTC, erha19 commented on tools/cli-engine/README.md
> +# @opensumi/opensumi-cli-engine
`@opensumi/opensumi-cli-engine` -> `@opensumi/cli-engine`

2023-01-30 09:41 UTC, erha19 commented on tools/cli-engine/package.json
> +    "build1": "npm run build:node && npm run build:browser && npm run build:exthost && npm run build:webview && npm run build:ext-worker-host",
这里的 `build1` 应该没用？

2023-01-30 09:41 UTC, erha19 commented on tools/cli-engine/package.json
> +    "@opensumi/ide-core-browser": "2.22.0",
这里的版本号不对，可以 `cli-engine` 应该是随 OpenSumi 版本发布的，应该把这个包加入到发布的包列表内，并且通过 yarn workspace 链接，如 `2.22.0` -> `workspace:*`

2023-01-30 09:41 UTC, erha19 commented on tools/cli-engine/package.json
> +    "node": ">=10.15.0"
这里的 `engines` 版本有点多余，而且版本限制也与 core 不一致

2023-01-30 09:41 UTC, erha19 commented on tools/cli-engine/src/browser/index.html
> +      window.KAITIAN_SDK_CONFIG = <%- JSON.stringify(config) %>
新增代码里面，不要用 `KAITIAN_*` 前置了，统一改成 `SUMI_*` 吧，不然后面又要改一遍。

2023-01-30 09:41 UTC, erha19 commented on tools/cli-engine/src/browser/index.ts
> +const layoutConfig = {
可以从  main-layout 中引默认的 `defaultConfig`, 有需要再覆盖，维护起来简单点

2023-01-30 09:41 UTC, erha19 commented on tools/cli-engine/src/node/env.ts
> +export const DEV_PATH = path.join(os.homedir(), '.opensumi-dev');
这里的 `DEV_PATH` 感觉不太准确，可以用  `CLI_DEVELOPMENT_PATH`, 同时，后面的 `.opensumi-dev` 改成 `.sumi-dev` 吧（目前默认的路径是 .sumi, 你可以引 `${StoragePaths.DEFAULT_STORAGE_DIR_NAME}-dev` 的方式来拼接）

2023-01-30 09:41 UTC, erha19 commented on tools/cli-engine/src/node/index.ts
> +const argv = require('yargs-parser')(process.argv.slice(2));
这里没必要引入 `yargs-parser`, 用 `mri` 吧

2023-01-30 09:41 UTC, erha19 commented on tools/cli-engine/src/node/index.ts
> +const opensumiDevConfigPath = path.resolve(extensions[0], 'opensumi-dev.config.js');
这个文件名也可以修改一下 `sumi-dev.config.js`

2023-01-30 09:41 UTC, erha19 commented on tools/cli-engine/src/node/server.ts
> +        // todo: 手动读取外层 `package.json`
这里的 TODO 好像没必要，已经读了外部的 `package.json` 了

2023-01-30 09:41 UTC, erha19 commented on tools/cli-engine/src/node/server.ts
> +      服务启动成功，请点击 http://${deviceIp}:${port} 访问 OpenSumi IDE.
展示的内容用英文吧。

2023-01-30 09:41 UTC, erha19 commented on tools/cli-engine/src/webview/webview-host/web-preload.ts
> +    // newFrame.contentWindow.onbeforeunload = () => {
没必要的内容可以删了，或者加一点注释说明一下。

2023-01-30 09:41 UTC, erha19 commented on tools/cli-engine/src/webview/webview-host/webview.html
> +</html>
行末少了个换行

2023-01-31 03:13 UTC, bk1012 commented
/publish

2023-02-02 06:41 UTC, erha19 requested changes

2023-02-02 06:41 UTC, erha19 commented on tools/cli-engine/README.md
> +DEBUG_ENGINE_PATH=~/your-_folder/ide-framework/tools/cli-engine/lib opensumi dev
这里如果是命令行使用示意的话，前面需要加个 `$`, 并且命令 'opensumi' -> 'sumi' 写错了，Debug 路径的写法也有点怪，可以改成 `{project folder path}/tools/cli-engine/lib`

2023-02-02 06:41 UTC, erha19 commented on tools/cli-engine/configs/tsconfig.json
> +{
这个文件是不是多余的？

2023-02-02 06:51 UTC, bk1012 commented on tools/cli-engine/configs/tsconfig.json
> +{
不是，webpack.config.browser.js 依赖了这个

2023-02-03 02:22 UTC, erha19 approved these changes

2023-02-03 02:22 UTC, merged