feat: bread scrumbs support menus
opensumi/core pull request #2258
Opened 2023-02-09 06:35 UTC by wangxiaojuan

### Types

- [x] 🎉 New Features

### Background or solution
![image](https://user-images.githubusercontent.com/1762334/217735869-692b8f5e-c691-409f-9a7d-9b7f3a749075.png)

### Changelog

2023-02-09 06:48 UTC, erha19 requested changes

2023-02-09 06:48 UTC, erha19 commented on packages/editor/src/browser/editor.contribution.ts
> +      group: '0_tab',
这里的 group 命名有点怪，这里应该是 `0_path` ?

2023-02-09 06:48 UTC, erha19 commented on packages/editor/src/browser/menu/breadcrumbs.menus.ts
> +  ctxMenuService: AbstractContextMenuService;
私有服务前面加上 `private readonly`

2023-02-09 06:48 UTC, erha19 commented on packages/editor/src/browser/menu/breadcrumbs.menus.ts
> +      this._breadcrumbsTitleContextKey = this.contextKeyService.createKey('breadcrumbsTitleContext', false);
这里 `breadcrumbsTitleContext` 变量统一维护到 https://github.com/opensumi/core/blob/f3fd01381d6ee854102d491b14957e9e634941a3/packages/core-browser/src/contextkey 这里吧，然后这个貌似目前没有地方用到？

2023-02-09 06:48 UTC, erha19 commented on packages/editor/src/browser/menu/breadcrumbs.menus.ts
> +    const titleContext = (group as EditorGroup).contextKeyService.createScoped();
这里的 `createScoped` 需要传入 DOM，否则就是一个不受控的子作用域，感觉这里可以直接用 group 上的 ContextKeyService。

2023-02-09 06:48 UTC, erha19 commented on packages/editor/src/browser/menu/breadcrumbs.menus.ts
> +    const titleContext = (group as EditorGroup).contextKeyService.createScoped();
并且上面 `this.contextKeyService.createKey('breadcrumbsTitleContext', ...` 调用又是用的全局 ContextKeyService，这里要理清楚关系，如果只是局部使用，那就放到局部 ContextKeyService 内去注册使用。

2023-02-09 06:48 UTC, erha19 commented on packages/editor/src/browser/navigation.view.tsx
> +      <span>1_{part.name}</span>
这里是不是写错了？多了个 `1_`

2023-02-09 06:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/opensumi/core?pullRequest=2258) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/opensumi/core?pullRequest=2258) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/opensumi/core?pullRequest=2258) it.</sub>

2023-02-09 08:24 UTC, bytemain commented
- Reveal In File Tree

这个也很常用，可以加一个吗

2023-02-09 09:04 UTC, erha19 requested changes

2023-02-09 09:04 UTC, erha19 commented on packages/editor/src/browser/menu/breadcrumbs.menus.ts
> +    // 设置resourceScheme
这里的注释有点迷惑

2023-02-09 09:04 UTC, erha19 commented on packages/editor/src/browser/menu/breadcrumbs.menus.ts
> +    const titleContext = group.contextKeyService.createScoped(domTarget);
这里的处理还是有问题，BreadCrumbsMenu 使用的 ContextKeyService 应该是固定的，而不是每次 show 的时候反复创建 ScopeContextKeyService，你这里要么就直接用 group.contextKeyService 好了

2023-02-10 07:58 UTC, Ricbet commented
![image](https://user-images.githubusercontent.com/20262815/218034245-34819193-db2f-47b4-9779-7578e07922d6.png)

需要注意面包屑的最后末尾部分可能是当前文件的 symbol 信息，这里是不能右键的

2023-02-14 02:28 UTC, erha19 requested changes

2023-02-14 02:28 UTC, erha19 commented on packages/editor/src/browser/editor.contribution.ts
> +    menus.registerMenuItem(MenuId.BreadcrumbsTitleContext, {
这里的 `REVEAL_IN_EXPLORER` 应该是另外一个分组下的命令? 例如 `1_file`

2023-02-14 02:28 UTC, erha19 commented on packages/editor/src/browser/menu/breadcrumbs.menus.ts
> +    const titleContext = group.contextKeyService.createScoped(domTarget);
这里的修改还是不太符合预期，建议这里
`const titleContext = group.contextKeyService.createScoped(domTarget);` 改成 `const titleContext = group.contextKeyService`，可以不需要 titleContext 这个中间变量

2023-02-14 02:28 UTC, erha19 commented on packages/editor/src/browser/menu/breadcrumbs.menus.ts
> +    const resourceContext = new ResourceContextKey(titleContext);
以你这里目前的实现需求看，这里的 `resourceContext` 貌似也没有实际作用，没有必要额外创建。

另外，`ContextKey` 不应该在每次右键菜单展示的时候生成一遍，建议放到 `group.contextKeyService` 内部去维护，否则会出现很多冗余的注册逻辑，或参考 https://github.com/opensumi/core/blob/f861cbda0eb3d66f8659514b02b5f62dc80e333c/packages/file-tree-next/src/browser/file-contextkey.ts 去初始化 ContextKey 及管理

2023-02-15 08:49 UTC, erha19 commented
@wangxiaojuan CI 处理下

2023-02-15 08:49 UTC, erha19 commented on packages/editor/src/browser/menu/breadcrumbs.menus.ts
> +    const resourceContext = new ResourceContextKey(titleContext);
@wangxiaojuan 这里评论看一下

2023-02-17 04:57 UTC, erha19 requested changes

2023-02-17 04:57 UTC, erha19 commented on packages/editor/src/browser/menu/breadcrumbs.menus.ts
> +      titleContext = group.contextKeyService.createScoped();
这里的 `this._groupContextKeyService` 是没有作用的，而且也不需要创建 scoped，直接用 group.contextKeyService ?

2023-02-23 01:51 UTC, wangxiaojuan commented
https://github.com/opensumi/core/issues/2272

2023-02-23 10:05 UTC, erha19 requested changes

2023-02-23 10:05 UTC, erha19 commented on packages/editor/src/browser/editor.contribution.ts
> +      command: EDITOR_COMMANDS.COPY_PATH.id,
这里的修改你理解错了，是 “复制相对路径”、“复制路径” 归类到 `0_path` 分组，而 “定位文件” 归类到 `1_file` 分组，这样，在菜单上会有分隔符区分两类菜单操作。

2023-03-01 10:12 UTC, erha19 approved these changes

2023-03-01 10:12 UTC, merged