fix: electron header bar default height
opensumi/core pull request #2269
Opened 2023-02-10 10:08 UTC by yantze

### Types

- [x] 🐛 Bug Fixes

### Background or solution
修复 Windows 环境 Header Bar 高度异常
<img width="1027" alt="image" src="https://user-images.githubusercontent.com/2226423/218063823-bc0c4031-ae95-481e-95cc-481e934d7d40.png">
正常场景
<img width="1037" alt="image" src="https://user-images.githubusercontent.com/2226423/218064186-d2a918d3-37c0-44d0-8da7-1f5f5c450edc.png">

### Changelog
修复 Windows 环境 Header Bar 高度异常

2023-02-13 06:12 UTC, erha19 submitted a review, later dismissed

2023-02-13 06:12 UTC, erha19 commented
@yantze 这个指到 2.22 吧

2023-02-14 02:14 UTC, erha19 requested changes

2023-02-14 02:14 UTC, erha19 commented on packages/electron-basic/src/browser/header/header.module.less
> +  background: var(--menu-background) !important;
这里的样式是被哪里的样式所覆盖？是不是可以通过提高 CSS 优先级的方式（例如增加 CSS 层级）来让这个样式生效，而不是用 `!important` ，这个容易造成后面样式问题难以排查的问题

2023-02-14 03:09 UTC, yantze commented on packages/electron-basic/src/browser/header/header.module.less
> +  background: var(--menu-background) !important;
memubar 背景色完成

2023-02-14 06:12 UTC, erha19 approved these changes

2023-02-14 06:12 UTC, merged