feat: support upstream control tree node render behavior
opensumi/core pull request #2290
Opened 2023-02-15 09:38 UTC by Ricbet

### Types

- [x] 🎉 New Features
- [x] 🐛 Bug Fixes

### Background or solution

1. 将 resolveChildren 里对每个 tree 节点的处理抽离成独立函数，方便上游 override
2. CommentContentNode 增加 isAllowExpand 字段，用于判断是否允许 expand 的行为

### Changelog
支持上游集成方控制评论模块的树组件渲染行为

2023-02-15 09:38 UTC, Ricbet commented
/publish

2023-02-15 09:50 UTC, erha19 requested changes

2023-02-15 09:50 UTC, erha19 commented on packages/comments/src/browser/tree/tree-node.defined.ts
> +    this.isExpanded = true;
这里这句 `this.setIsAllowExpand(false);` 是不是可以去掉，给 `_isAllowExpand` 一个初始值就行了？

2023-02-15 09:50 UTC, erha19 commented on packages/comments/src/browser/tree/tree-node.defined.ts
> +    this.isExpanded = true;
然后是不是 `isAllowToggle` 好一点？

2023-02-15 09:53 UTC, Ricbet commented on packages/comments/src/browser/tree/tree-node.defined.ts
> +    this.isExpanded = true;
> 

我们这边也是需要控制这个字段的，给个 setXXX 函数好一点

2023-02-15 09:54 UTC, Ricbet commented on packages/comments/src/browser/tree/tree-node.defined.ts
> +    this.isExpanded = true;
> 然后是不是 `isAllowToggle` 好一点？

嗯

2023-02-16 02:26 UTC, erha19 approved these changes
LGTM

2023-02-16 02:27 UTC, merged