feat: support inspectExtensionHost config
opensumi/core pull request #2310
Opened 2023-02-20 06:40 UTC by Ricbet

### Types

- [x] 🎉 New Features

### Background or solution

### Changelog
新增 inspectExtensionHost config 配置项，允许设置插件进程 inspect 时的 host 地址

2023-02-21 13:19 UTC, erha19 requested changes

2023-02-21 13:19 UTC, erha19 commented on packages/core-browser/src/react-providers/config-provider.tsx
> +   * 需要开启 enableDebugExtensionHost 配置才生效
enableDebugExtensionHost 两边可以加个 "`"

inspect ip -> `Inspect IP`

2023-02-21 13:19 UTC, erha19 commented on packages/extension/src/common/extension.ts
> +   * 调试插件进程的 ip 地址
ip -> IP

2023-02-23 06:40 UTC, Ricbet commented on packages/core-browser/src/react-providers/config-provider.tsx
> +   * 需要开启 enableDebugExtensionHost 配置才生效
不用吧，注释能解释清楚就行

2023-02-23 06:57 UTC, erha19 commented on packages/core-browser/src/react-providers/config-provider.tsx
> +   * 需要开启 enableDebugExtensionHost 配置才生效
专有名词还是规范一下，虽然是注释，不然到时候代码里面一堆大小写写法

2023-02-23 07:26 UTC, Ricbet commented on packages/core-browser/src/react-providers/config-provider.tsx
> +   * 需要开启 enableDebugExtensionHost 配置才生效
我觉得本末倒置了，首先 inspect 也不是什么专有名词，其次就是注释的目的就是为了让人知道这个配置是干什么用的。就拿 inspect 举例，熟悉的人肯定都是 `--inspect=xxxx` 这样去用，不熟悉的人搜索引擎肯定也是小写占大多数。然后倒提醒我了，其实这里应该不叫 ip，按照 node 的文档来看应该是叫 host

2023-02-23 07:36 UTC, erha19 commented on packages/core-browser/src/react-providers/config-provider.tsx
> +   * 需要开启 enableDebugExtensionHost 配置才生效
这里的 Inspect 是短语开头首字母大写，而 IP 是 Internet Protocol Address 全称的缩写，所以需要全大写，跟搜索和使用习惯没有啥关系 ... 只是一种常见规范，可能也不太重要，但是还是要统一写法的

2023-02-23 07:38 UTC, erha19 approved these changes

2023-02-23 08:19 UTC, merged