feat: toolbar dropdown-button contribute
opensumi/core pull request #2312
Opened 2023-02-20 07:49 UTC by hacke2

### Types

- [x] 🎉 New Features

### Background or solution

resolve #1740

```
"kaitianContributes": {
    "toolbar": {
      "actions": [
        {
          "type": "dropdownButton",
          "id": "common-start",
          "command": "common-start.select",
          "options": [
            {
              "label": "运行",
              "value": "run"
            },
            {
              "label": "调试",
              "value": "debug"
            }
          ]
        }
      ]
    }
  },
```

![image](https://user-images.githubusercontent.com/6399899/194736818-d69461a6-53d7-4053-b123-c91268e48405.png)

### Changelog
Add DropdownButton Component
Add DropdownButton Toolbar contribute

2023-02-28 02:15 UTC, erha19 requested changes

2023-02-28 02:15 UTC, erha19 commented on packages/components/src/dropdown/dropdown-button.tsx
> +import EllipsisOutlined from '@ant-design/icons/EllipsisOutlined';
这里是不是用 DownOutlined 更合理一点？

2023-02-28 02:15 UTC, erha19 commented on packages/components/src/button/index.tsx
> +export default Button;
为啥要加一句 export default ？这里统一导出内容格式吧

2023-02-28 02:15 UTC, erha19 commented on packages/extension/src/hosted/api/sumi/ext.host.toolbar.ts
> +      case 'button':
这里的 `button` 和 `dropdownButton` 可以归纳到一个常量里面

2023-02-28 02:15 UTC, erha19 commented on packages/core-browser/src/toolbar/components/dropdown-button.tsx
> +export function ToolbarActionDropdownButton<T>(
这里的 Function Component 声明与其他地方声明方式保持一致吧，改成 `export const  ToolbarActionDropdownButton<Type> = ...` 的方式吧，下面也一样，另外感觉使用 `React.` 引用方法的方式会让代码很长，比较建议 `import React, { useRef, useEffect ... } from 'react'`, 然后直接使用 `useRef` 等方法

2023-03-03 09:36 UTC, hacke2 commented on packages/components/src/dropdown/dropdown-button.tsx
> +import EllipsisOutlined from '@ant-design/icons/EllipsisOutlined';
这里参考 Ant Design 官方示例
![image](https://user-images.githubusercontent.com/6399899/222685453-f2cf52ba-c480-4051-9b86-29f6b872372f.png)

2023-03-07 09:37 UTC, erha19 requested changes

2023-03-07 09:37 UTC, erha19 commented on packages/extension/src/common/sumi/toolbar.ts
> +export const BUTTON_SET_STATE_ID = 'sumi-extension.toolbar.btn.setState';
这里可以考虑写成
```ts

export const EXTENSION_TOOLBAR_ACTION_PREFIX = 'sumi-extension.toolbar';

export enum EXTENSION_TOOLBAR_ACTIONS {
   BUTTON_SET_STATE: `${EXTENSION_TOOLBAR_ACTION_PREFIX}.btn.setState`,
}
```

2023-03-07 09:37 UTC, erha19 commented on packages/extension/src/common/sumi/toolbar.ts
> +export enum TOOLBAR_ACTION {
`TOOLBAR_ACTION` -> `TOOLBAR_ACTION_TYPE` ?

2023-03-07 09:37 UTC, erha19 commented on packages/extension/src/common/sumi/toolbar.ts
> +} from '../../browser/sumi/types';
有没有可能把 browser 的类型定义挪到 common 内，不然这里很容易循环依赖

2023-03-07 09:47 UTC, hacke2 commented on packages/extension/src/common/sumi/toolbar.ts
> +} from '../../browser/sumi/types';
我看了，不太好挪，之前代码就是这样的

2023-03-08 02:47 UTC, Ricbet commented on packages/extension/src/common/sumi/toolbar.ts
> +} from '../../browser/sumi/types';
我建议新开个 pr 统一整理一下现在的类型引用吧，我看了一下原来这地方的代码就是这样的，如果改的话涉及到的地方会很多

2023-03-08 02:47 UTC, Ricbet approved these changes
LGTM

2023-03-17 07:10 UTC, erha19 approved these changes

2023-03-17 07:10 UTC, merged