feat: statusbar pophover support icon
opensumi/core pull request #2340
Opened 2023-02-27 13:04 UTC by hacke2

### Types

fix #1977

- [x] 🎉 New Features

### Background or solution

![image](https://user-images.githubusercontent.com/6399899/221570970-f18abfba-18ae-49f6-bc02-5899380c41e0.png)

### Changelog
feat: statusbar pophover support icon

2023-02-28 01:58 UTC, erha19 requested changes

2023-02-28 01:58 UTC, erha19 commented on packages/status-bar/src/browser/status-bar-item.view.tsx
> +import { parseLabel, LabelIcon, replaceLocalizePlaceholder } from '@opensumi/ide-core-browser';
这里目前使用的 parseLabel 是从 Theia 引入，跟 transformLabelWithCodicon 方法是存在重复建设的，是不是直接移除掉这块代码，统一使用 transformLabelWithCodicon ?

2023-03-07 09:30 UTC, erha19 requested changes

2023-03-07 09:48 UTC, hacke2 commented on packages/status-bar/src/browser/status-bar-item.view.tsx
> +          {text && transformLabelWithCodicon(text, {}, iconService.fromString.bind(iconService), (text) => (
是有效的，transformLabelWithCodicon 我扩展了，需要根据不同情况渲染不同的节点

2023-03-07 09:48 UTC, hacke2 commented on packages/status-bar/src/browser/status-bar.module.less
> +  span:global(.codicon),
是有效的，一些 icon 是 .kt-icon 开头的

2023-03-07 09:54 UTC, bytemain commented on packages/markers/src/browser/markers-contribution.ts
> +        `$(codicon/error) ${normalize(stats.errors)}`,
应该没问题，就是转为使用 codicon 的图标。 我之前是想保留一点 OpenSumi 的本味，所以用了 kticon

2023-03-07 09:55 UTC, bytemain approved these changes

2023-03-08 02:40 UTC, merged