fix: localization lifecycle
opensumi/core pull request #2382
Opened 2023-03-07 09:42 UTC by Ricbet

### Types

- [x] 🐛 Bug Fixes

### Background or solution

由于 localizations 贡献点的 contribute 被提前 resolve 了
导致其插件的 nls 翻译文件还未加载完成就开始了 LifeCyclePhase.Starting 生命周期的加载。

像 SCM 面板中的菜单是通过 commands 贡献点注册上去的，文案翻译也是在这里开始，但此时 localizations 贡献点还在加载当中，导致找不到 i18n 文案

修复后:
![image](https://user-images.githubusercontent.com/20262815/223368041-41616740-cdc2-48e0-9582-ac9fd269d98d.png)

### Changelog
修复 localizations contribution 生命周期的问题

2023-03-07 09:53 UTC, erha19 requested changes

2023-03-07 09:53 UTC, erha19 commented on packages/extension/src/browser/vscode/contributes/localization.ts
> +          (async () => {
写个函数名在调用吧，闭包结构不好调试，可读性有点差

2023-03-07 11:52 UTC, bytemain requested changes

2023-03-07 11:52 UTC, bytemain commented on packages/extension/src/browser/vscode/contributes/localization.ts
> +          const storagePath = (await this.extensionStoragePathServer.getLastStoragePath()) || '';
这里的 `|| ''` 不会对后面的逻辑有影响吗？
传一个空的 storagePath 似乎不合理啊

2023-03-07 11:55 UTC, Ricbet commented on packages/extension/src/browser/vscode/contributes/localization.ts
> +          const storagePath = (await this.extensionStoragePathServer.getLastStoragePath()) || '';
updateLanguagePack 里面有处理的，缺省目录是 DEFAULT_NLS_CONFIG_DIR

2023-03-09 02:53 UTC, erha19 approved these changes

2023-03-09 03:12 UTC, merged