fix: show theme quick picker after theme extension installed
opensumi/core pull request #2398
Opened 2023-03-12 16:56 UTC by PerfectPan

### Types

- [ ] 🎉 New Features
- [x] 🐛 Bug Fixes
- [ ] 📚 Documentation Changes
- [ ] 💄 Code Style Changes
- [ ] 💄 Style Changes
- [ ] 🪚 Refactors
- [ ] 🚀 Performance Improvements
- [ ] 🏗️ Build System
- [ ] ⏱ Tests
- [ ] 🧹 Chores
- [ ] Other Changes

### Background or solution
fix https://github.com/opensumi/core/issues/1232
### Changelog
show theme quick picker after theme extension installed

2023-03-12 16:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/opensumi/core?pullRequest=2398) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/opensumi/core?pullRequest=2398) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/opensumi/core?pullRequest=2398) it.</sub>

2023-03-12 16:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/opensumi/core?pullRequest=2398) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/opensumi/core?pullRequest=2398) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/opensumi/core?pullRequest=2398) it.</sub>

2023-03-13 02:24 UTC, erha19 requested changes
验证通过，功能与预期一致

2023-03-13 02:24 UTC, erha19 commented on packages/i18n/src/common/en-US.lang.ts
> +    current: 'Current',
这里的国际化文本内， `current` 这个 key 容易与其他情况下的使用冲突，如果只是在 Theme 中使用，可以改成  `theme.current`

2023-03-13 03:17 UTC, PerfectPan commented on packages/i18n/src/common/en-US.lang.ts
> +    current: 'Current',
好，晚上回去看一下

2023-03-14 03:26 UTC, erha19 approved these changes
LGTM

2023-03-15 08:21 UTC, merged

2023-03-15 08:22 UTC, erha19 commented
@PerfectPan 感谢你的贡献，后续代码将会在 v2.23.0 版本中发布