WIP: refactor: upgrade react 18
opensumi/core pull request #2404
Opened 2023-03-14 02:39 UTC by Ricbet

### Types

- [x] 🪚 Refactors

### Background or solution

### Changelog

2023-06-08 02:51 UTC, bytemain commented on lerna.json
> +      "npmClientArgs": ["--no-package-lock", "--legacy-peer-deps"]
目前没用使用 lerna 作为 bootstrap 工具，直接用的 yarn3，这个可以去掉

2023-06-08 02:52 UTC, bytemain commented on packages/comments/src/browser/comments-item.view.tsx
> +              <span className={styles.comment_item_body}>{typeof body === 'string' ? body : body.value}</span>
这个看起来改的有点奇怪，感觉不是 react 18 带来的改变啊

2023-06-08 02:55 UTC, bytemain commented on packages/debug/src/browser/editor/debug-hover-widget.tsx
> +    this.layoutContentWidget();
为啥这里 160 行没有放到 render 的回调里

2023-06-08 02:56 UTC, bytemain commented on packages/file-tree-next/src/browser/services/file-tree-model.service.ts
> -          } else {
why?

2023-06-08 02:59 UTC, bytemain commented on packages/scm/src/browser/scm-model.ts
> +  public repoList: ISCMRepository[] = observable.array<ISCMRepository>([]);
学到了，`observable.array`，之前我做那个 preference 的时候不知道有这个东西... 普通的 [] 搭配 `@observable` 好像没用

2023-06-08 03:24 UTC, Ricbet commented on packages/comments/src/browser/comments-item.view.tsx
> +              <span className={styles.comment_item_body}>{typeof body === 'string' ? body : body.value}</span>
comment 模块的 IThreadComment 类型变了

2023-06-28 06:46 UTC, Ricbet commented on packages/debug/src/browser/editor/debug-hover-widget.tsx
> +    this.layoutContentWidget();
18 去掉了 render 的回调，因为 createRoot API 用的是异步渲染树模式，不需要放在回调里

2023-06-29 02:49 UTC, erha19 requested changes

2023-06-29 02:49 UTC, erha19 commented on packages/scm/src/browser/scm-view-container.tsx
> +  const hasMultiRepos = viewModel.repoList.length > 1;
这里我看移除了 mobx 的 observer，但又给 repoList 声明了 @observer，应该是无效的？

2023-06-29 09:54 UTC, Ricbet commented on packages/scm/src/browser/scm-view-container.tsx
> +  const hasMultiRepos = viewModel.repoList.length > 1;
这里之前是为了想去掉 mobx 相关的逻辑，现在改回去了

2023-11-16 02:00 UTC, erha19 commented
在 https://github.com/opensumi/core/pull/3171 进一步处理。

2023-11-16 02:00 UTC, closed without merging