fix: namespace conflicts between extHost and extBrowser
opensumi/core pull request #2415
Opened 2023-03-15 04:57 UTC by yantze

### Types

- [x] 🐛 Bug Fixes

### Background or solution
一般情况下，插件进程的日志会写入到 logDir/20230315/extHost.log 文件中，但由于 OpenSumi 在插件实现上有自己的 browser 层，会导致情况特殊，browser 写入的日志是通过 Node 进程写入的。

插件中 browser 层的日志是通过 Node 进程也同时写入到 extHost.log 中，在两个进程同时打开文件句柄，会导致 Windows 环境下的写锁保护机制报错，导致日志写入失败。

解决方法：插件的 Browser 使用另外一个命名空间，和插件进程区分开，保证不同的集成不会写入同一个文件，同时也能保证逻辑清晰。

closed #2383 

### Changelog
修复插件浏览器层的日志和插件进程的命名空间冲突

2023-03-15 08:24 UTC, erha19 requested changes

2023-03-15 08:24 UTC, erha19 commented on packages/extension/src/browser/vscode/api/debug/extension-debug-service.ts
> +    this.logger = this.loggerManager.getLogger(SupportLogNamespace.ExtensionBrowser);
应该没有所谓的 `ExtensionBrowser` 层，这里能不能直接用 `Browser` ? 这样修改感觉会有一些歧义

2023-03-17 01:29 UTC, zhuzeyu22 commented on packages/extension/src/browser/vscode/api/debug/extension-debug-service.ts
> +    this.logger = this.loggerManager.getLogger(SupportLogNamespace.ExtensionBrowser);
从字面上理解 ExtensionHost 是整个插件的命名空间，ExtensionBrowser 是插件页面的命名空间，与之对应的还可以有 ExtensionNode 的后台进程命名空间。以及代码里还有 XXXClient 的命名方式，这使我很迷惑。

2023-03-17 02:39 UTC, yantze commented on packages/extension/src/browser/vscode/api/debug/extension-debug-service.ts
> +    this.logger = this.loggerManager.getLogger(SupportLogNamespace.ExtensionBrowser);
命名空间可以直接改为 Browser

2023-03-17 02:40 UTC, erha19 commented on packages/extension/src/browser/vscode/api/debug/extension-debug-service.ts
> +    this.logger = this.loggerManager.getLogger(SupportLogNamespace.ExtensionBrowser);
@yantze 感觉这里别引入命名空间了，直接用 ILogger 去输出日志就行了

2023-03-17 02:47 UTC, yantze commented on packages/extension/src/browser/vscode/api/debug/extension-debug-service.ts
> +    this.logger = this.loggerManager.getLogger(SupportLogNamespace.ExtensionBrowser);
> @yantze 感觉这里别引入命名空间了，直接用 ILogger 去输出日志就行了

别引入命名空间？

2023-03-17 03:08 UTC, erha19 approved these changes
LGTM

2023-03-17 03:58 UTC, erha19 commented
/publish

2023-03-17 07:11 UTC, merged