fix: uninstall extension failed in electron
opensumi/core pull request #2469
Opened 2023-03-23 03:23 UTC by yantze

### Types

- [x] 🐛 Bug Fixes

### Background or solution
close https://github.com/opensumi/ide-electron/issues/64

electron 环境卸载插件调用了 fileService.delete， delete 实现中判断如果是 electron 并且设置了 moveToTrash 就会使用 electron 的 api 删除文件。但如果没有设置 moveToTrash 标记，就会走原始的删除文件。原始的删除文件在 mac 下会报错， 找不到 app/node/macos-trash 可执行文件。

在 ide-electron 环境中，删除插件其实移到 Trash 可能更好，避免一些误操作导致文件无法恢复。

### Changelog
修复 ide-electron 环境卸载插件失败的问题

2023-03-23 06:08 UTC, yantze commented
/publish

2023-03-23 07:48 UTC, erha19 requested changes

2023-03-23 07:48 UTC, erha19 commented on packages/file-service/src/browser/file-service-client.ts
> +    if (this.appConfig.isElectronRenderer) {
这里感觉还是要保留 `moveToTrash` 配置项逻辑，是不是给 options 一个默认值？默认删除是走回收站？ @yantze 

另外这里的判断可以用 `options?.xxx` 简化一下

2023-03-24 02:24 UTC, erha19 approved these changes
LGTM, 相关问题 https://github.com/opensumi/core/discussions/2410

2023-03-28 08:53 UTC, merged

2023-04-03 06:18 UTC, shilin8805 commented
@yantze 这个在windows上还是有问题。windows上uriString传进来的是C:\\xxx\xxx\这种格式的，没有scheme，导致uri.scheme === Schemes.file判断的时候没有走进去。
<img width="963" alt="image" src="https://user-images.githubusercontent.com/3340210/229426453-e799eec4-06b3-45c2-82b5-57f7f5df7cfa.png">

2023-04-04 06:37 UTC, yantze commented
> @yantze 这个在windows上还是有问题。windows上uriString传进来的是C:\xxx\xxx\这种格式的，没有scheme，导致uri.scheme === Schemes.file判断的时候没有走进去。 <img alt="image" width="963" src="https://user-images.githubusercontent.com/3340210/229426453-e799eec4-06b3-45c2-82b5-57f7f5df7cfa.png">

可以提供一下复现路径，目前没有在 OpenSumi 2.23.2 版本上复现这个问题

2023-04-04 08:27 UTC, shilin8805 commented
> > @yantze 这个在windows上还是有问题。windows上uriString传进来的是C:\xxx\xxx\这种格式的，没有scheme，导致uri.scheme === Schemes.file判断的时候没有走进去。 <img alt="image" width="963" src="https://user-images.githubusercontent.com/3340210/229426453-e799eec4-06b3-45c2-82b5-57f7f5df7cfa.png">
> 
> 可以提供一下复现路径，目前没有在 OpenSumi 2.23.2 版本上复现这个问题

我也试的2.23.2版本，uriString是C:\\这种格式的，前面没有scheme，new URI后，scheme变成了C，你重现的uriString是什么？

![WX20230404-161228@2x](https://user-images.githubusercontent.com/3340210/229733252-f226d76a-8fa0-4832-8420-ff9af1baf337.png)

2023-04-04 10:23 UTC, yantze commented
> 

确实是 uriString 没有进行处理，我这边修复一下

2023-04-04 11:01 UTC, yantze commented
已提交 https://github.com/opensumi/core/pull/2548