feat: support show unsaved files
opensumi/core pull request #2491
Opened 2023-03-24 09:58 UTC by AhkunTa

### Types
- [x] 🎉 New Features
### Background or solution

close#2314 
### Changelog
- support show unsaved files

2023-03-25 05:46 UTC, Ricbet commented
feat pr 合到 main 吧

2023-03-25 05:57 UTC, Ricbet commented
changelog 再写详细一点点，是哪里支持了 unsaved files

2023-03-25 06:00 UTC, Ricbet commented on packages/opened-editor/src/browser/services/opened-editor-model.service.ts
> +      accordionService.updateViewBadge('file-opened-editor', dirtyMsg);
不要硬编码，用 `ExplorerOpenedEditorViewId` 常量

2023-03-27 03:45 UTC, Ricbet submitted a review, later dismissed
LGTM

2023-03-27 04:58 UTC, erha19 requested changes

2023-03-27 04:58 UTC, erha19 commented on packages/main-layout/src/browser/accordion/styles.module.less
> +  text-overflow: ellipsis;
你这里的样式应该有问题（超出部分不会省略号，因为是自适应大小），默认情况下应该是优先保留 Section 的名称，如： `SECTION_NAME  [Badge ...]`

2023-03-27 10:10 UTC, AhkunTa commented on packages/main-layout/src/browser/accordion/styles.module.less
> +  text-overflow: ellipsis;
<img width="208" alt="截屏2023-03-27 18 09 05" src="https://user-images.githubusercontent.com/31676999/227912094-a54d43bd-2330-48bf-a6d0-f8b044c50520.png">
<img width="215" alt="截屏2023-03-27 18 09 20" src="https://user-images.githubusercontent.com/31676999/227912107-ed859ffb-9a8b-4b24-bb73-b3b9ca704d55.png">

v老师是第一张图 要不参考下v老师的设计？

2023-03-27 10:13 UTC, erha19 commented on packages/main-layout/src/browser/accordion/styles.module.less
> +  text-overflow: ellipsis;
可以的，这里的 Badge 信息的展示优先级应该要更高

2023-03-28 02:07 UTC, erha19 commented
@AhkunTa CI 处理一下

2023-03-31 13:10 UTC, Ricbet commented
@AhkunTa CI 处理一下

2023-04-10 09:46 UTC, Ricbet approved these changes
LGTM

2023-04-12 02:17 UTC, erha19 approved these changes

2023-04-12 02:17 UTC, merged

2023-05-29 07:29 UTC, erha19 commented on packages/main-layout/src/browser/accordion/styles.module.less
> +  text-transform: none;
这里的样式冲突了，为啥要把默认大写的样式去掉？ 这个会导致很多面板标题出现大小写问题 @AhkunTa