refactor: replace quickopen label render function, from parseLabel to transformLabelWithCodicon
opensumi/core pull request #2498
Opened 2023-03-25 09:41 UTC by pipiiiiii

### Types

- [x] 🪚 Refactors

### Background or solution
fix: #2301
### Changelog
* replace quickopen label render function, from parseLabel to transformLabelWithCodicon
* transformLabelWithCodicon props iconStyle supports className
* transformLabelWithCodicon will ignore some error icon text, e.g.: $() (~spin)

2023-03-27 02:06 UTC, erha19 requested changes
另外，在 [NOTICE.md](https://github.com/opensumi/core/blob/main/NOTICE.md) 文件里面可以删除这个 parse.ts 的文件了

2023-03-27 02:06 UTC, erha19 commented on packages/quick-open/src/browser/components/highlight-label/index.tsx
> +  const iconService = useInjectable<IIconService>(IIconService);
这里补充一个修改后的效果图吧？看一下修改后效果

2023-03-27 02:18 UTC, pipiiiiii commented on packages/quick-open/src/browser/components/highlight-label/index.tsx
> +  const iconService = useInjectable<IIconService>(IIconService);
before:
![before](https://user-images.githubusercontent.com/9477255/227824874-22969458-af65-4e7e-8565-bce10d9f54ef.jpg)

after:
![after](https://user-images.githubusercontent.com/9477255/227824888-8bffdb68-c86f-4f42-9958-e68b9729ece1.jpg)

2023-03-27 02:20 UTC, erha19 commented on packages/quick-open/src/browser/components/highlight-label/index.tsx
> +  const iconService = useInjectable<IIconService>(IIconService);
咋感觉，这里的 icon string 没有被解析成图标，并且图标也还是不居中的？是不是图标小一点好了？

2023-03-27 02:27 UTC, pipiiiiii commented on packages/quick-open/src/browser/components/highlight-label/index.tsx
> +  const iconService = useInjectable<IIconService>(IIconService);
有解析成图标的，这里面只有 $(gist-new~spin) 是符合标准的，其他的都属于异常的格式，这个图标的样式我再看看

2023-03-27 03:09 UTC, pipiiiiii commented on packages/quick-open/src/browser/components/highlight-label/index.tsx
> +  const iconService = useInjectable<IIconService>(IIconService);
![after-2](https://user-images.githubusercontent.com/9477255/227831307-cce6b5ef-8eec-4cdb-b8a6-5b527120a95b.jpg)

调整 icon 样式为 14px，居中

2023-03-30 02:14 UTC, erha19 approved these changes

2023-03-30 02:14 UTC, merged