feat: add onWillApplyTheme provider
opensumi/core pull request #2502
Opened 2023-03-27 07:06 UTC by bytemain

### Types

- [x] 🎉 New Features

### Background or solution

close: #1736

### Changelog

add onWillApplyTheme provider

2023-03-27 07:23 UTC, bytemain commented
/publish

2023-03-28 08:58 UTC, erha19 requested changes

2023-03-28 08:58 UTC, erha19 commented on packages/theme/src/browser/workbench.theme.service.ts
> +      if (typeof c.onWillApplyTheme === 'function') {
这里用 `isFunction` 判断代替吧

2023-03-30 02:12 UTC, erha19 commented
@bytemain 看一下 E2E 测试

2023-03-30 09:40 UTC, merged

2023-06-28 06:04 UTC, bytemain commented
如何使用：

```ts
@Domain(ThemeContributionProvider)
export class ColorThemeContributionProvider implements ThemeContributionProvider {
  onWillApplyTheme(theme: ITheme) {
    const colors = {} as Record<string, string | undefined>;
    const foreground = theme.getColor('foreground');
    if (foreground) {
      colors['foreground.secondary'] = foreground.darken(0.2).toString();
    }
    if (theme.getColor('menu.foreground')) {
      colors[menuDisableForeground] = theme.getColor('menu.foreground')!.darken(0.4).toString();
    }
    return colors;
  }
}
```

然后把这个 Provider 添加到某个 modules 中即可。