fix: copy diff uri path at editor tab
opensumi/core pull request #2513
Opened 2023-03-28 08:55 UTC by ensorrow

### Types

- [x] 🐛 Bug Fixes

### Background or solution
Copy path & copy relative path from editor tab is not working with diff uri:
<img width="915" alt="image" src="https://user-images.githubusercontent.com/13199771/228183885-befe437a-e9ce-4369-aec6-29388f26c17f.png">

### Changelog
fix: copy diff uri path at editor tab

2023-04-03 07:54 UTC, erha19 requested changes

2023-04-03 07:54 UTC, erha19 commented on packages/file-tree-next/src/browser/file-tree-contribution.ts
> +          uri = new URI(query.modified).withScheme('file');
我记得 new URI 时默认会为 `non-scheme` 的路径追加 file 协议？

2023-04-06 02:15 UTC, ensorrow commented on packages/file-tree-next/src/browser/file-tree-contribution.ts
> +          uri = new URI(query.modified).withScheme('file');
query.modified 左边一般是 git 协议的

2023-04-06 02:29 UTC, erha19 approved these changes
LGTM

2023-04-07 02:53 UTC, merged