fix: remove extension with wrong uri string
opensumi/core pull request #2548
Opened 2023-04-04 11:01 UTC by yantze

### Types

- [x] 🐛 Bug Fixes

### Background or solution
修复删除插件没有使用正确的 uri string，使用了 path 导致代码中 URI.scheme 判断异常。

### Changelog
fix: remove extension with wrong uri string

2023-04-07 06:28 UTC, erha19 approved these changes

2023-04-07 06:29 UTC, erha19 requested changes

2023-04-07 06:29 UTC, erha19 commented on packages/extension/src/browser/extension-management.service.ts
> +      await this.fileService.delete(URI.file(extensionPath).toString());
这里用 new URI 是不是更能兼容 `file://...` 路径和 `/...` 绝对文件路径的情况？

2023-04-07 07:03 UTC, yantze commented on packages/extension/src/browser/extension-management.service.ts
> +      await this.fileService.delete(URI.file(extensionPath).toString());
文件路径转 uri 目前就只有 URI.file 其它的方式都不靠谱的。

至于兼容 file:// 目前看代码里面，变量名都明确的指定的是 path，所以一般都不会出现这种情况

2023-04-12 02:10 UTC, erha19 commented on packages/extension/src/browser/extension-management.service.ts
> +      await this.fileService.delete(URI.file(extensionPath).toString());
不是吧，目前文件路径转 URI 还是 new URI 靠谱点？

Windows：

C:\a\\b --  new URI --> file://C:\a\\b
C:\a\\b --  URI.file --> file://C:\a\\b


file://C:\a\\b --  new URI --> file://C:\a\\b
file://C:\a\\b --  URI.file --> file://file://C:\a\\b

Mac:

/a/b --  new URI --> file:///a/b
/a/b --  URI.file --> file:///a/b

file:///a/b --  new URI --> file:///a/b
file:///a/b --  URI.file --> file://file:///a/b

个人感觉 URI.file 在后面 vscode-uri 升级之后都不推荐用了

2023-04-12 02:20 UTC, erha19 commented on packages/extension/src/browser/extension-management.service.ts
> +      await this.fileService.delete(URI.file(extensionPath).toString());
那应该是我记错了，这个自动补全 file:// 的逻辑应该是在  Uri 内，而不是我们封装的 URI 里面

2023-04-12 02:20 UTC, erha19 approved these changes

2023-04-12 02:20 UTC, merged

2023-04-12 02:43 UTC, yantze commented
URI 在 path 场景下的测试

Mac:
```
/Users/admin/abc.json => new URI => file:///Users/admin/abc.json
file:///Users/admin/abc.json => new URI => file:///Users/admin/abc.json
/Users/admin/abc.json => URI.file => file:///Users/admin/abc.json
file:///Users/admin/abc.json => URI.file => file:///file%3A///Users/admin/abc.json
```

Windows:
```
C:\\Users\\abc.json => new URI => c:%5CUsers%5Cabc.json
C:\\Users\\abc.json => new URI().codeUri.fsPath => \\Users\\abc.json
C:\\Users\\abc.json => URI.file => file://c%3AUsers/abc.json
C:\\Users\\abc.json => URI.file().codeUri.fsPath => C:\\Users\\abc.json

file:///c%3A/Users/abc.json => new URI().toString() => file:///c%3A/Users/abc.json
file:///c%3A/Users/abc.json => new URI().codeUri.fsPath => C:\\Users\\abc.json
```
<img width="412" alt="image" src="https://user-images.githubusercontent.com/2226423/231334313-2f60c7d9-5936-4960-9ab7-b4db4de02a38.png">

2023-04-12 02:46 UTC, erha19 commented
所以看下来，对于 FSPath 做 `URI.file` 是靠谱的，但是直接用 `new URI` 可能会在 Windows 下翻车