fix: change the way to capture IPC messages so listeners passed to ipcRenderer.on are now disposable
opensumi/core pull request #2555
Opened 2023-04-06 07:24 UTC by tyn1998

### Types

- [ ] 🎉 New Features
- [x] 🐛 Bug Fixes
- [ ] 📚 Documentation Changes
- [ ] 💄 Code Style Changes
- [ ] 💄 Style Changes
- [x] 🪚 Refactors
- [ ] 🚀 Performance Improvements
- [ ] 🏗️ Build System
- [ ] ⏱ Tests
- [ ] 🧹 Chores
- [ ] Other Changes

### Background or solution

**Related:**

- #2187 
- #2453
- fix #2359

**How I solve this?** 

Please see https://github.com/opensumi/core/issues/2359#issuecomment-1477821638

**TODO**

- [ ] update opensumi/devtools
- [ ] update opensumi/docs

### Changelog

**BREAKING CHANGE**: Change the way to capture IPC messages so listeners passed to `ipcRenderer.on` are now disposable. In the same time, remove `devtools` option in `core-electron-main` so now there is only a single `devtools` option for `core-browser`.

2023-04-06 07:29 UTC, tyn1998 commented
大家好，这是一个BREAKING CHANGE，因为删了一个之前针对Electron端的配置项`devtools`（browser端的`devtools`仍然保留），所以集成方使用OpenSumi DevTools的方式需要改变，我之后会向opensumi/docs仓库提PR。

如果Changelog填的不对，请指正。

另外，我又把devtools开启了，因为package/startup和tools/electron应该是只对这个项目起作用，而这个项目基本上就是用于开发的，那么devtools保持开启状态好像也合情合理。大家怎么看？

2023-04-06 07:39 UTC, tyn1998 commented on packages/core-browser/src/bootstrap/inner-providers.ts
> +        useValue: createElectronMainApi(IElectronURLService, !!appConfig.devtools),
这里传入的参数肯定是undefined，但是TS提示可能为undefined报错，所以我用了`!!`。如果有更好的方法，请指出~

2023-04-06 09:47 UTC, Ricbet commented on packages/core-browser/src/bootstrap/inner-providers.ts
> +        useValue: createElectronMainApi(IElectronURLService, !!appConfig.devtools),
> 这里传入的参数肯定是undefined，但是TS提示可能为undefined报错，所以我用了`!!`。如果有更好的方法，请指出~

`createElectronMainApi` 第二个参数可以用 `?` 可选链运算符

2023-04-06 10:05 UTC, tyn1998 commented on packages/core-browser/src/bootstrap/inner-providers.ts
> +        useValue: createElectronMainApi(IElectronURLService, !!appConfig.devtools),
好主意，谢谢！

2023-04-06 14:18 UTC, erha19 commented
@yantze 来看一下

2023-04-07 02:14 UTC, yantze submitted a review, later dismissed
LGTM

2023-04-07 06:25 UTC, erha19 requested changes

2023-04-07 06:25 UTC, erha19 commented on packages/core-browser/src/utils/electron.ts
> +  if (capturer !== undefined) {
这里直接用 `isUndefined` 方法吧

2023-04-07 06:25 UTC, erha19 commented on tools/electron/src/main/index.ts
>    overrideWebPreferences: {},
electron 下好像也没有默认开启？

2023-04-07 06:25 UTC, erha19 commented on packages/core-browser/src/utils/electron.ts
> +export function createElectronMainApi(name: string, devtools?: boolean): IElectronMainApi<any> {
这里的 `devtools?: boolean` 是不是表达为 `enableCaptured` 类似的开关更合理

2023-04-07 06:35 UTC, tyn1998 commented on tools/electron/src/main/index.ts
>    overrideWebPreferences: {},
因为现在没有针对Electron单独的开关了，所以只要把core-browser的devtools开启即可。也就是在tools/electron/src/browser/index.ts里令devtools: true。

2023-04-07 06:51 UTC, erha19 approved these changes

2023-04-11 08:55 UTC, merged