feat: menubar supports compact mode
opensumi/core pull request #2556
Opened 2023-04-06 09:06 UTC by Ricbet

### Types

- [x] 🎉 New Features

### Background or solution

![image](https://user-images.githubusercontent.com/20262815/230329865-b44773a8-eb7a-486d-b8e3-736a5d7b4d78.png)

### Changelog
menubar 支持 compact 模式

2023-04-07 02:04 UTC, erha19 requested changes

2023-04-07 02:04 UTC, erha19 commented on packages/menu-bar/src/browser/menu-bar.contribution.ts
> +  registerMenus(): void {}
这个多余的方法是不是可以删了？

2023-04-07 02:04 UTC, erha19 commented on tools/electron/src/browser/layout.ts
> +      '@opensumi/ide-terminal-next',
这里这些 ID 是不是可以都定义到 `container-id` 里面的一个 NAMESPACE 里面，本来所有前端模块也都是依赖 @opensumi/ide-core-browser 的，而且目前这里的命名规范稍微有点不统一

2023-04-07 02:20 UTC, Ricbet commented on tools/electron/src/browser/layout.ts
> +      '@opensumi/ide-terminal-next',
规范的问题另开 pr 解决吧

2023-04-07 02:55 UTC, erha19 commented on tools/electron/src/browser/layout.ts
> +      '@opensumi/ide-terminal-next',
这里还有个问题，你不能用 `DEBUG_CONSOLE_CONTAINER_ID`，而应该是 `DEBUG_CONSOLE_VIEW_ID`, ContainerID 是用于定义子视图 ID 的，这里应该传入的是 `DEBUG_CONSOLE_VIEW_ID`

2023-04-12 02:11 UTC, erha19 approved these changes

2023-04-12 02:14 UTC, erha19 requested changes

2023-04-12 02:14 UTC, erha19 commented on packages/debug/src/browser/view/console/debug-console.contribution.ts
> -      'debug-console',
这里不能用 `DEBUG_CONSOLE_CONTAINER_ID` 这个值，`DEBUG_CONSOLE_CONTAINER_ID` 目前是用在另外的容器 ID 上的，这里用了会有歧义，并不是代表整个 View，要么修改一下这里代码 https://github.com/opensumi/core/blob/96477a517f05e47209e42aa3d53444baa4117b63/packages/debug/src/browser/view/console/debug-console.contribution.ts#L64

2023-04-12 02:21 UTC, Ricbet commented on packages/debug/src/browser/view/console/debug-console.contribution.ts
> -      'debug-console',
这里我改回去好了，这个 pr 先不处理这类问题

2023-04-14 09:27 UTC, erha19 approved these changes

2023-04-14 09:27 UTC, merged