fix: deleted files also appear in file searches
opensumi/core pull request #2557
Opened 2023-04-06 09:16 UTC by wangxiaojuan

### Types
- [X] 🐛 Bug Fixes

### Background or solution
fixed: https://github.com/opensumi/core/issues/2550
![image](https://user-images.githubusercontent.com/1762334/230332098-8e5d2444-d5db-4146-9320-43b9731c4942.png)

### Changelog
修复搜索文件时已删除的文件出现在列表内

2023-04-07 02:08 UTC, erha19 requested changes

2023-04-07 02:08 UTC, erha19 commented on packages/core-browser/src/common/common.storage.ts
> +    this.eventBus.on(FileTreeDelectEvent, async () => {
这里不能依赖文件树上的删除，应该通过文件系统级别的监听事件去控制，否则外部文件删除无法相应。

typo "delect" => "delete"

2023-04-07 02:08 UTC, erha19 commented on packages/core-browser/src/common/common.storage.ts
> +  eventBus: IEventBus;
只读的服务引用，前面加上  private readonly

2023-04-17 02:34 UTC, erha19 requested changes

2023-04-17 02:34 UTC, erha19 commented on packages/core-browser/src/common/common.storage.ts
> +import { IEventBus } from '@opensumi/ide-core-browser';
循环自引用了这里

2023-04-17 02:34 UTC, erha19 commented on packages/core-browser/src/common/common.storage.ts
> +import { FileChangeType } from '@opensumi/ide-file-service/lib/common';
browser 不能依赖 ide-file-service，循环依赖了

2023-04-20 06:37 UTC, Ricbet approved these changes
LGTM

2023-04-21 03:41 UTC, erha19 requested changes

2023-04-21 03:41 UTC, erha19 commented on packages/core-browser/src/common/common.storage.ts
> +          this.recentStorage = await this.getStorage(STORAGE_NAMESPACE.RECENT_DATA);
这里感觉不太对，重新从 Stroage 中获取数据应该不会更新文件列表（有缓存）

2023-04-21 03:41 UTC, erha19 commented on packages/file-service/src/browser/file-service-client.ts
> +    this.eventBus.fire(new UpdateRecentStorageEvent(changes));
同时这里通过在 file-service 和 core-browser 中同时加上一段 Event 代码来实现这块逻辑的方式感觉有点鸡肋。

不如看一下是不是可以把 core-browser 中的 quick-open 逻辑迁移至 file-service 模块里面

另外，原本 recentFile 内也有使用 Event 做的文件监听及处理，是不是可以看一下这段逻辑失效的原因？解决方式我还是比较建议不依赖 Event，而是把确定的功能放到确定模块内。

https://github.com/opensumi/core/blob/3340fa89eab63413a00335f52a81d6cfa20dd2e5/packages/core-browser/src/quick-open/recent-files.ts#L59

2023-04-26 07:52 UTC, closed without merging