fix(core-browser): move react to peerDDependencies
opensumi/core pull request #2562
Opened 2023-04-07 04:03 UTC by gemwuu

### Types

- [ ] 🎉 New Features
- [ ] 🐛 Bug Fixes
- [ ] 📚 Documentation Changes
- [ ] 💄 Code Style Changes
- [ ] 💄 Style Changes
- [x] 🪚 Refactors
- [ ] 🚀 Performance Improvements
- [ ] 🏗️ Build System
- [ ] ⏱ Tests
- [ ] 🧹 Chores
- [ ] Other Changes

### Background or solution
@opensumi/ide-core-browser depends on react@^16.8.6, which should be put in peerDependencies to avoid creating extra unnecessary react@16.x environment.

### Changelog
fix(core-browser): move react to peerDependencies.

2023-04-07 04:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/opensumi/core?pullRequest=2562) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/opensumi/core?pullRequest=2562) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/opensumi/core?pullRequest=2562) it.</sub>

2023-04-07 04:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/opensumi/core?pullRequest=2562) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/opensumi/core?pullRequest=2562) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/opensumi/core?pullRequest=2562) it.</sub>

2023-04-07 05:59 UTC, hacke2 commented
/publish

2023-04-07 06:31 UTC, bytemain commented
请再重新提交一下 lock 文件

2023-04-07 06:38 UTC, gemwuu commented
> 请再重新提交一下 lock 文件

提交了，麻烦再触发下 CI。

2023-04-07 07:13 UTC, hacke2 commented
/publish

2023-04-17 02:26 UTC, erha19 commented
@gemwuu @hacke2 这个有相关结论吗？移动 react 依赖到 DevDeps 的原因是啥？

2023-04-17 02:28 UTC, gemwuu commented
> @gemwuu @hacke2 这个有相关结论吗？移动 react 依赖到 DevDeps 的原因是啥？

是移到 peerDependencies 中。组件强依赖 react 框架，更加合理的做法是声明 peerDependencies，否则会污染依赖树上的 react 版本。

2023-04-17 03:39 UTC, hacke2 approved these changes
LGTM

2023-04-17 08:06 UTC, erha19 requested changes

2023-04-17 08:06 UTC, erha19 commented on packages/core-browser/package.json
> +    "react": "^16.8.6"
这里看到 react 是放到 devDependencies 里面了？是非必要的吗？另外这里两个 deps 的版本号对齐一下吧 @gemwuu

2023-04-17 08:13 UTC, gemwuu commented on packages/core-browser/package.json
> +    "react": "^16.8.6"
dev Dependencies 是为了这个包的本地测试用的，使用 major 版本，让单测更稳定。peerDependencies 是为了让包的兼容性更好。

2023-04-17 08:33 UTC, erha19 approved these changes
LGTM, @Ricbet 也看一下吧

2023-04-18 06:37 UTC, Ricbet approved these changes

2023-04-18 06:37 UTC, Ricbet approved these changes

2023-04-18 07:25 UTC, merged