fix: foreground color of the match highlights on actively focused items
opensumi/core pull request #2564
Opened 2023-04-07 08:15 UTC by wangxiaojuan

### Types

- [X] 🐛 Bug Fixes

### Background or solution
![image](https://user-images.githubusercontent.com/1762334/230570547-1401853c-0a5e-43f5-8af1-4a0355f73fbc.png)
![image](https://user-images.githubusercontent.com/1762334/230570606-0932772d-5524-4522-9048-41bffd38939c.png)
![image](https://user-images.githubusercontent.com/1762334/230570666-257dff48-e58f-46e6-9c03-7a54df48fc89.png)

### Changelog
修复浅色主题下highlights文字颜色问题

2023-04-10 06:03 UTC, Ricbet commented on packages/theme/src/browser/workbench.theme.service.ts
> +      if (targetColor && colorKey.startsWith('vscode')) {
这段逻辑还可以再优化一下

2023-04-14 02:44 UTC, erha19 requested changes

2023-04-14 02:44 UTC, erha19 commented on packages/theme/src/common/color-tokens/custom/monaco.ts
> +  'vscode.editorSuggestWidget.focusHighlightForeground',
为啥这里额外注册了一个非标准的自定义 Token？而且还是 vscode 前缀的，这段逻辑应该不与  vscode 相关

要注册应该也是这个吧？https://github.com/microsoft/vscode/blob/9faf9eb0ba6412b5befbdbcbca9993f533a6077a/src/vs/editor/contrib/suggest/browser/suggestWidget.ts#L48

2023-04-14 03:02 UTC, Ricbet commented on packages/theme/src/common/color-tokens/custom/monaco.ts
> +  'vscode.editorSuggestWidget.focusHighlightForeground',
因为 monaco 里面的 highlight 部分的 color token 是 `--vscode-editorSuggestWidget-focusHighlightForeground`
![image](https://user-images.githubusercontent.com/20262815/231930791-262b7acb-8692-450b-85c5-534b8b76daf5.png)

2023-04-14 08:59 UTC, erha19 commented on packages/theme/src/common/color-tokens/custom/monaco.ts
> +  'vscode.editorSuggestWidget.focusHighlightForeground',
@wangxiaojuan 加个注释信息吧

2023-04-17 07:29 UTC, erha19 requested changes

2023-04-17 08:00 UTC, erha19 approved these changes

2023-04-18 02:02 UTC, merged