fix: deleted files also appear in recentFiles
opensumi/core pull request #2653
Opened 2023-04-26 07:50 UTC by wangxiaojuan

### Types
- [X] 🐛 Bug Fixes

### Background or solution
fixed https://github.com/opensumi/core/issues/2550
![image](https://user-images.githubusercontent.com/1762334/234506399-35f3f260-2275-4e96-8cc1-5169d942355d.png)
问题的原因是已经删除文件在次被打开会触发RecentlyOpenedFile列表更新
### Changelog
修复搜索文件时已删除的文件出现在列表内

2023-04-28 06:08 UTC, Ricbet commented on packages/editor/src/browser/workbench-editor.service.ts
> +    const stat = await this.fileServiceClient.getFileStat(uri.toString());
这里可能会遇到一些没有注册过 `FileSystemProvider` 的情况，比如设置面板，这样的修改就导致设置面板打不开了。
可以考虑只在 `uri.scheme === Schemes.file` 的时候去获取文件的状态

2023-05-17 06:49 UTC, Ricbet commented on packages/editor/src/browser/workbench-editor.service.ts
> +    if (uri.toString().startsWith('file:/')) {
这里不要这样去判断

2023-05-17 06:49 UTC, Ricbet commented on packages/editor/src/browser/workbench-editor.service.ts
>        // 只记录 file 类型的
@wangxiaojuan  你把 `stat` 的文件状态判断逻辑放在这个条件语句里面就行，就能保证他一定是 `file` 协议的文件了

2023-05-24 02:30 UTC, erha19 requested changes

2023-05-24 02:30 UTC, erha19 commented on packages/editor/src/browser/workbench-editor.service.ts
> +        this.recentFilesManager.setMostRecentlyOpenedFile!(uri.withoutFragment().toString());
这里的 ！ 是多余的

2023-05-30 06:42 UTC, erha19 commented on packages/editor/src/browser/workbench-editor.service.ts
> +        this.recentFilesManager.setMostRecentlyOpenedFile!(uri.withoutFragment().toString());
另外你这里的修复还是不能解决这个问题，只是在二次打开已删除文件的时候不会存下这个文件记录，一旦打开过的文件被外部删除，最近打开还是会一直存在这个（已删除的文件）

2024-03-23 06:54 UTC, bytemain commented
This pr has been closed because it has not had recent activity. Thank you for your contributions.

2024-03-23 06:54 UTC, closed without merging