WIP: fix: increase the distance up and down the left panel
opensumi/core pull request #2723
Opened 2023-05-17 11:47 UTC by wangxiaojuan

### Types

- [X] 🐛 Bug Fixes

### Background or solution
fixed: https://github.com/opensumi/core/issues/2721
![image](https://github.com/opensumi/core/assets/1762334/52e44969-359e-4fbc-8028-ba4d46a72f13)

### Changelog
fix：编辑器左侧面板内容区块上下增加间距

2023-05-18 02:00 UTC, erha19 requested changes

2023-05-18 02:00 UTC, erha19 commented on packages/main-layout/src/browser/accordion/styles.module.less
> +  :global {
这里不能这么加，如果需要，应该面板组件内自行实现，Panel 容器不应该具备边距，或者说不是所有面板都希望有间距

2023-06-05 02:11 UTC, erha19 commented on packages/main-layout/src/browser/accordion/styles.module.less
> +  :global {
@wangxiaojuan https://github.com/opensumi/core/blob/06654fe37eb0b0bab833e840f171e9a6ec6367e6/packages/components/src/recycle-list/RecycleList.tsx#L91 可以参考这种属性进行实现，而不是默认调整所有边距

2023-06-13 05:52 UTC, wangxiaojuan commented on packages/main-layout/src/browser/accordion/styles.module.less
> +  :global {
收到，我改下

2023-06-15 08:04 UTC, erha19 requested changes

2023-06-15 08:04 UTC, erha19 commented on packages/components/src/recycle-list/RecycleList.tsx
> +          bottomSpace={5}
这里已经有一个类似的参数 https://github.com/opensumi/core/blob/879b1c53306723c6c8fea28c0db9ecf4899aaa14/packages/components/src/recycle-list/RecycleList.tsx#L67 不需要重复定义，对齐一下命名吧

2023-06-15 08:04 UTC, erha19 commented on packages/extension/src/browser/components/extension-tree-view.tsx
> +            topSpace={5}
为什么要在视图上下都加上边距？修改背景是什么呀？一些插件是会依赖全屏无边距这个样式做定制的

2023-06-15 08:04 UTC, erha19 commented on packages/opened-editor/src/browser/opened-editor.tsx
> +            topSpace={8}
这些边距会让面板于其他面板样式存在差异

2024-03-23 06:55 UTC, closed without merging

2024-03-23 06:55 UTC, bytemain commented
This pr has been closed because it has not had recent activity. Thank you for your contributions.