fix: open recycle only one search result that cannot be clicked
opensumi/core pull request #2734
Opened 2023-05-19 06:38 UTC by wangxiaojuan

### Types

- [X] 🐛 Bug Fixes

### Background or solution
fixed: https://github.com/opensumi/core/issues/2718

### Changelog
bugfix: 修复文件列表结果只有一条时鼠标无法点击的问题

2023-05-19 07:39 UTC, bytemain submitted a review, later dismissed

2023-05-19 09:16 UTC, Ricbet commented
这个在 quick open 模块下修复吧，不要放在 recycle list 去改样式

2023-05-31 02:07 UTC, erha19 requested changes

2023-05-31 02:07 UTC, erha19 commented on packages/quick-open/src/browser/styles.module.less
> +  :global(.kt-recycle-list div:has(.scrollbar-thumb-horizontal)),
不建议强行覆盖样式，建议通过在 RecycleList 提供配置参数用于隐藏横向滚动条

2023-06-09 02:17 UTC, erha19 commented
@wangxiaojuan 这个 PR 里处理了 https://github.com/opensumi/core/pull/2790

2023-06-14 02:02 UTC, closed without merging