WIP: refactor: extract electron essentials
opensumi/core pull request #2742
Opened 2023-05-23 05:57 UTC by bytemain

### Types

- [x] 🪚 Refactors

### Background or solution

[OpenSumi 2023 Roadmap - 移除对 isElectronRenderer 的依赖](https://github.com/opensumi/core/wiki/2023-Roadmap)

优化代码中对于 isElectronRenderer 的依赖，将 isElectronRenderer 相关的代码都抽离出独立的函数。

### Changelog

split the code related to Electron

2023-05-24 02:08 UTC, bytemain commented
暂时先小改，没有大改。

等之后会有个 RFC 写出来，改成用上一些设计模式的

2023-05-24 02:10 UTC, yantze commented on packages/core-common/src/types/application.ts
> +  windowId: string | number;
1. clientId 和 windowId 的用途还不太一样， clientId 是通讯连接的 id，windowId 是窗口的 Id。Web 版本看看如果没有场景直接是 undefined 会更好一些
2. windowId 应该直接是 number 类型

2023-05-24 02:14 UTC, erha19 commented on packages/editor/src/browser/editor-electron.contribution.ts
> +import { Autowired, INJECTOR_TOKEN, Injector } from '@opensumi/di';
用文件名做区分感觉不如基于目录结构做一下分层？例如加一个 electron-renderer 的目录？

2023-05-24 02:14 UTC, erha19 commented on packages/core-browser/src/opener/opener-electron.contribution.ts
> +import { IOpenerService } from '.';
opener 目录下的 `index.ts` 感觉是存在循环引用问题的，这里可以一起改一下

2023-05-25 09:29 UTC, bytemain commented on packages/core-common/src/types/application.ts
> +  windowId: string | number;
<img width="1088" alt="CleanShot 2023-05-25 at 17 28 36@2x" src="https://github.com/opensumi/core/assets/13938334/5e6895a9-27af-45dc-bf00-0eb916013158">

不太敢直接设置为 undefined，因为其他地方还是有在使用的。

2023-05-25 09:32 UTC, bytemain commented on packages/editor/src/browser/editor-electron.contribution.ts
> +import { Autowired, INJECTOR_TOKEN, Injector } from '@opensumi/di';
嗯 最终目标是这个，这次要不就不加了吧，因为是从 browser/index.ts > EditorModule 引入的 browser/editor-electron.contribution.ts

增加目录的话还得弄一个 EditorElectronModule，还得都多引入一个 module

2023-05-25 09:34 UTC, bytemain commented on packages/core-browser/src/opener/opener-electron.contribution.ts
> +import { IOpenerService } from '.';
<img width="1786" alt="CleanShot 2023-05-25 at 17 33 37@2x" src="https://github.com/opensumi/core/assets/13938334/748fad69-3511-48a1-8960-703ff8309d24">

这个 index.ts 里只有类型，不会循环引用。

我直接改了下文件名发现有 17 个文件引用，单独启个 pr 弄吧

2023-05-31 02:22 UTC, erha19 requested changes

2023-05-31 02:22 UTC, erha19 commented on packages/core-browser/src/common/common-electron.contribution.ts
> +import { localize, Domain } from '@opensumi/ide-core-common';
common 内的几个文件名称上感觉有点重复，可以修改一下，例如 ：

`common/common-web.contribution.ts` -> `common/web.contribution.ts`

2023-05-31 02:22 UTC, erha19 commented on packages/core-browser/src/opener/opener-electron.contribution.ts
> +    electronRendererURLService.on('open-url', (payload) => {
这类 `open-url` 的 Events 感觉可以归纳到一个对象里面

2023-05-31 02:22 UTC, erha19 commented on packages/editor/src/browser/editor.contribution.ts
> -      return this.onWillStopElectron();
这个 `onWillStopElectron` 为啥删了？

2023-05-31 09:19 UTC, bytemain commented on packages/editor/src/browser/editor.contribution.ts
> -      return this.onWillStopElectron();
editor-electron 里接管了这部分的代码

2023-05-31 10:20 UTC, bytemain commented on packages/core-browser/src/opener/opener-electron.contribution.ts
> +    electronRendererURLService.on('open-url', (payload) => {
这个 on 似乎根本不能用，我看了下 IElectronURLService 里没有 on 的实现，单独开 pr 解决吧。这个只是移动代码位置

2023-06-01 04:04 UTC, yantze approved these changes

2023-06-02 04:35 UTC, erha19 approved these changes

2023-06-02 04:35 UTC, erha19 approved these changes

2023-06-02 06:05 UTC, merged