feat: infer second terminal cwd from the first one
opensumi/core pull request #2852
Opened 2023-06-28 08:10 UTC by bytemain

### Types

- [x] 🎉 New Features

### Background or solution

### Changelog

Support infer the terminal cwd when split the terminal

2023-06-28 09:54 UTC, Aaaaash submitted a review, later dismissed

2023-06-29 07:04 UTC, erha19 requested changes

2023-06-29 07:04 UTC, erha19 commented on packages/terminal-next/src/node/pty.proxy.ts
> +  switch (os.platform()) {
这里感觉可以复用 utils 里面的 isWindows 等方法？

2023-07-11 07:47 UTC, bytemain commented on packages/terminal-next/src/node/pty.proxy.ts
> +  switch (os.platform()) {
done

2023-07-13 07:27 UTC, Ricbet commented on packages/terminal-next/src/node/pty.proxy.ts
> +  return undefined;
如果是 Windows 呢

2023-07-13 07:30 UTC, bytemain commented on packages/terminal-next/src/node/pty.proxy.ts
> +  return undefined;
刚大概搜了下，似乎没啥简单的方法做到，感觉得写一个 native module 才能做到了

windows 不支持获取某个 process 的 cwd

2023-07-14 03:53 UTC, Ricbet approved these changes

2023-07-17 09:31 UTC, merged