fix: drop-down menu popup position update
opensumi/core pull request #3061
Opened 2023-09-13 07:27 UTC by wangxiaojuan

### Types
- [X] 🐛 Bug Fixes

fix: https://github.com/opensumi/core/issues/3060

### Background or solution

![image](https://github.com/opensumi/core/assets/1762334/11edff01-acd0-46fe-bb67-66a5889f835c)

![image](https://github.com/opensumi/core/assets/1762334/57b1bf5b-c743-437d-8f53-05f310124001)

### Changelog
fix：下拉菜单popup位置优化

2023-09-20 03:02 UTC, erha19 requested changes

2023-09-20 03:02 UTC, erha19 commented on packages/overlay/src/browser/ctx-menu/ctx-menu.view.tsx
> +        offset: [window.scrollX, window.scrollY + 10],
你这里直接把所有位置的右键菜单展示整了一个额外的 offsetY，不能这么搞 ... 很多地方还是需要让右键菜单从点击位置展示的

2023-10-11 09:48 UTC, erha19 commented
@wangxiaojuan 再看看

2024-03-23 06:55 UTC, bytemain commented
This pr has been closed because it has not had recent activity. Thank you for your contributions.

2024-03-23 06:55 UTC, closed without merging