feat: achieve noRecursive fileWatcher
opensumi/core pull request #3095
Opened 2023-09-29 11:07 UTC by wjywy

### Types

- [ ] 🎉 New Features

### Background or solution

目前 Opensumi 已实现文件监听的能力，但是仅支持在单进程内对项目目录及文件进行递归监听。

由于统一的递归监听过于消耗系统资源，而且同时在插件进程、浏览器进程、NodeJs 进程监听会相互影响，导致发生一些异常情况会引起系统错误，所以需要提供一个非递归的文件监听系统，来提供给周边系统实现各自的监听能力。

本此项目需要基于 NodeJS 提供的文件系统，进行对单文件/单目录的文件监听，同时不影响已有的递归实现。

采用fs模块的watch方法进行完善

### Changelog

新增非递归文件监听模块，其路径为file-service/src/node/no-recursive

2023-10-07 02:35 UTC, pipiiiiii commented
issue: https://github.com/opensumi/core/issues/2650

2023-10-10 08:38 UTC, pipiiiiii commented on packages/file-service/src/node/disk-file-system.provider.ts
> +    const id = await this.watcherServer.watchFileChanges('d:\\front_many\\firstIssue\\core\\tools\\workspace\\front', {
这里不对，不要写死

2023-10-10 08:42 UTC, pipiiiiii commented on packages/utils/src/pfs.ts
> +import * as fs from 'fs';
这个文件是做什么的?

2023-10-16 02:09 UTC, pipiiiiii requested changes

2023-10-16 02:09 UTC, pipiiiiii commented on packages/file-service/src/node/no-recursive/file-node-watcher-lib.ts
> +                  this.pushDeleted(changePath);
这里是一样的

2023-10-16 02:09 UTC, pipiiiiii commented on packages/file-service/src/node/no-recursive/file-node-watcher-lib.ts
> +            else {
子目录是不是不应该监听到才对，是非递归的监听，如果需要监听的对象是文件，只需要处理当前文件的事件即可，如果是目录，只处理当前目录下的文件，而不是递归处理。

2023-10-19 02:48 UTC, pipiiiiii requested changes

2023-10-19 02:48 UTC, pipiiiiii commented on packages/file-service/src/node/disk-file-system.provider.ts
> +  constructor(@Optional() recursive = false) {
这里默认值应该是 true，需要兼容现有逻辑

2023-10-19 02:48 UTC, pipiiiiii commented on packages/file-service/src/node/disk-file-system.provider.ts
> +import { UnRecursiveFileSystemWatcher } from './no-recursive/file-node-watcher-lib';
这个文件路径也一起改掉，注意下命名规则

2023-10-19 02:48 UTC, pipiiiiii commented on packages/file-service/src/node/recursive/file-service-watcher.ts
> +          // this.pushUpdated(event.path);
这里是不是应该不能注释

2023-10-19 02:48 UTC, pipiiiiii commented on packages/file-service/src/node/recursive/file-service-watcher.ts
> +      // 这一段需要根据watch的api写非递归监听的逻辑
这里应该删掉吧

2023-10-19 03:02 UTC, erha19 requested changes

2023-10-19 03:02 UTC, erha19 commented on packages/utils/src/disposable.ts
> +   * @param t
这里的注释有些多余，如果没有做特殊修改可以移除掉

2023-10-19 03:02 UTC, erha19 commented on packages/utils/src/disposable.ts
> +   * @param t
这类注释比较适合个人学习时标注，不建议修改到 utils 内的工具方法，如果只是添加注释的话，这里部分方法是从 VS Code 中引入，避免后续畸化无法判断修改

2023-10-25 02:21 UTC, pipiiiiii requested changes

2023-10-25 02:21 UTC, pipiiiiii commented on packages/file-service/src/node/un-recursive/file-node-watcher-lib.ts
> +      if (isDirectory) {
dowatch 的内容逻辑有点混乱，其实这个核心是 
1. 监听传入路径 
2. 当 change 事件触发时判断
  *  如果传入的路径是文件夹，这时触发事件的是文件，所以需要去在之前缓存的内容里面找，来判断文件时新增/更新/删除
  * 如果传入的路径是文件，那么需要找到变更的类型
 3. 发出事件

这里应该是先有监听事件触发，再判断监听的类型

2023-10-25 02:21 UTC, pipiiiiii commented on packages/file-service/src/node/un-recursive/file-node-watcher-lib.ts
> +    if (this.isEnableNSFW()) {
这里不需要

2023-10-25 02:21 UTC, pipiiiiii commented on packages/file-service/src/node/un-recursive/file-node-watcher-lib.ts
> +      // 但是这里始终为 undefined
因为 trywatch 实现返回的是 undefined

2023-10-25 06:00 UTC, pipiiiiii requested changes
补充测试用例，可以完善对代码逻辑的理解，不然代码中很多逻辑都经不起推敲。
测试用例中增加几种场景
1. 监听路径为文件
  * 文件修改
  * 文件删除
  * 文件删除后重新增加
2. 监听路径是文件夹
  * 子目录文件修改、删除、重命名、增加
  * 子目录内文件夹的变更（代码中不需要处理，但是要补充测试用例）

2023-10-25 06:00 UTC, pipiiiiii commented on packages/file-service/src/node/un-recursive/file-node-watcher-lib.ts
> +        const isDirectory = fs.lstatSync(basePath).isDirectory();
这个可以放在最外面，前面也有用到过这个判断

2023-10-25 06:00 UTC, pipiiiiii commented on packages/file-service/src/node/un-recursive/file-node-watcher-lib.ts
> +            if (!fs.lstatSync(changePath).isDirectory()) {
这里似乎不用加这个判断，有试过如果是新增的目录会触发事件么

2023-10-25 06:00 UTC, pipiiiiii commented on packages/file-service/src/node/un-recursive/file-node-watcher-lib.ts
> +          this.pushUpdated(changePath);
这里不太对，如果是单文件，也会有删除的情况吧

2023-10-25 06:00 UTC, pipiiiiii commented on packages/file-service/src/node/un-recursive/file-node-watcher-lib.ts
> +      if (await fs.pathExists(basePath)) {
都有 error 了，为什么要加判断再打日志呢

2023-10-25 06:00 UTC, pipiiiiii commented on packages/file-service/src/node/un-recursive/file-node-watcher-lib.ts
> +    const handler = await tryWatchDir();
tryWatchDir 没有返回值啊，handler 都是空的，这里期望返回什么呢

2023-10-28 18:16 UTC, wjywy commented
测试已经提上去了，麻烦再看看呢

2023-10-30 06:16 UTC, pipiiiiii commented on packages/file-service/src/node/disk-file-system.provider.ts
> +    this.recursive = recursive;
这里有问题，this.recursive 赋值在 init 后面会导致第一次初始化永远是 false

2023-10-30 06:52 UTC, pipiiiiii commented
处理下测试用例问题

2023-10-30 13:26 UTC, pipiiiiii approved these changes
LGTM

2023-10-30 14:11 UTC, erha19 requested changes

2023-10-30 14:11 UTC, erha19 commented on packages/file-service/__tests__/node/file-node-watcher-lib.test.ts
> +    // injector.mock(UnRecursiveFileSystemWatcher, 'watchFileChanges', () => false);
多余注释可以删一下

2023-10-30 14:11 UTC, erha19 commented on packages/file-service/__tests__/node/file-node-watcher-lib.test.ts
> +  const track = temp.track();
初始化流程可以包裹到 beforeAll 里面处理

2023-10-30 14:11 UTC, erha19 commented on packages/file-service/__tests__/node/file-node-watcher-lib.test.ts
> +(isMacintosh ? describe.skip : describe)('watch document delete/update/deleteAndAdd', () => {
为什么在 Mac 环境跳过这些测试？

2023-10-30 14:11 UTC, erha19 commented on packages/file-service/src/common/watcher.ts
> +import { IRelativePattern } from '../../../utils/lib/glob';
从 @opensumi/ide-core-common 里面引用，这里路径错了

2023-10-30 14:11 UTC, erha19 commented on packages/file-service/src/node/recursive/file-service-watcher.ts
> +// 文件监听类型(更新、添加、删除)；文件监听下的文件修改时触发事件；启动和注销文件监听；
多余的注释删了

2023-10-30 14:11 UTC, erha19 commented on packages/file-service/src/node/recursive/file-service-watcher.ts
> +} from '../../common/index';
路径里的 index 应该是多余的

2023-10-30 14:11 UTC, erha19 commented on packages/file-service/src/node/un-recursive/file-node-watcher-lib.ts
> +import { join, basename, normalize } from '@opensumi/ide-utils/lib/path';
建议这么写，import {
  Path,
} from '@opensumi/ide-core-node';

const { join, basename, normalize } = Path;

因为这里在 file-service 是没有声明 ide-utils 依赖的

2023-10-30 14:11 UTC, erha19 commented on packages/file-service/src/node/un-recursive/file-node-watcher-lib.ts
> +
多余的空行

2023-10-30 14:11 UTC, erha19 commented on packages/file-service/src/node/un-recursive/file-node-watcher-lib.ts
> +import { FileChangeType, FileSystemWatcherClient, IFileSystemWatcherServer } from '../../common/index';
多余的 index

2023-10-30 14:25 UTC, erha19 requested changes

2023-10-30 14:25 UTC, erha19 commented on packages/file-service/src/node/un-recursive/file-node-watcher-lib.ts
> +   * @param uri
无用的注释可以删了

2023-10-30 14:25 UTC, erha19 commented on packages/file-service/src/node/un-recursive/file-node-watcher-lib.ts
> +      this.logger.warn('此路径不存在，请重新开始');
不要使用中文报错，报错信息用英文表达一下

2023-10-30 14:25 UTC, erha19 commented on packages/file-service/src/node/un-recursive/file-node-watcher-lib.ts
> +  FileUri,
另外这个文件名 “file-node-watcher-lib.ts” 为什么要加一个 -lib ？是不是可以删了

2023-10-30 14:25 UTC, erha19 commented on packages/file-service/src/node/un-recursive/file-node-watcher-lib.ts
> +      watcher.on('change', (type, raw) => {
这里应该是有类型可以引用的，同时这里应该叫 filename 而不是 raw

2023-10-30 14:25 UTC, erha19 commented on packages/file-service/src/node/un-recursive/file-node-watcher-lib.ts
> +      // 目录下面的所有文件
这个文件里的中文注释可以删一下

2023-10-30 15:10 UTC, wjywy commented on packages/file-service/__tests__/node/file-node-watcher-lib.test.ts
> +(isMacintosh ? describe.skip : describe)('watch document delete/update/deleteAndAdd', () => {
开发环境是windows，不敢确保mac环境下面是否正确

2023-10-31 01:43 UTC, erha19 commented on packages/file-service/__tests__/node/file-node-watcher-lib.test.ts
> +(isMacintosh ? describe.skip : describe)('watch document delete/update/deleteAndAdd', () => {
@wjywy CI 会跑 macOS 环境，这里应该预期是没差异的才对，不能只考虑 windows 环境

2023-10-31 02:00 UTC, wjywy commented on packages/file-service/__tests__/node/file-node-watcher-lib.test.ts
> +(isMacintosh ? describe.skip : describe)('watch document delete/update/deleteAndAdd', () => {
好的  已经重新提交了  麻烦再CI一下呢

2023-10-31 02:49 UTC, erha19 requested changes

2023-10-31 02:49 UTC, erha19 commented on packages/file-service/src/node/un-recursive/file-node-watcher.ts
> +import { Injectable, Optional, Autowired } from '@opensumi/di';
@wjywy 这个文件名改成 file-service-watcher.ts 吧，属于相对应的服务，其他目前没问题了

2023-10-31 02:51 UTC, wjywy commented on packages/file-service/src/node/un-recursive/file-node-watcher.ts
> +import { Injectable, Optional, Autowired } from '@opensumi/di';
好的

2023-10-31 02:53 UTC, wjywy commented on packages/file-service/src/node/un-recursive/file-node-watcher.ts
> +import { Injectable, Optional, Autowired } from '@opensumi/di';
已经修改好重新push了

2023-10-31 06:37 UTC, erha19 approved these changes

2023-10-31 06:37 UTC, erha19 commented on packages/file-service/__tests__/node/file-node-watcher.test.ts
> +    // injector.mock(UnRecursiveFileSystemWatcher, 'watchFileChanges', () => false);
无用的代码

2023-10-31 06:37 UTC, erha19 commented on packages/file-service/__tests__/node/file-node-watcher.test.ts
> +  it('deleted file', async () => {
这里的 Test Case 可以优化一下标题以及内容，可以另外起个 PR 优化一下描述，这个 PR 就先合了

2023-10-31 06:42 UTC, wjywy commented on packages/file-service/__tests__/node/file-node-watcher.test.ts
> +  it('deleted file', async () => {
好的  收到

2023-10-31 06:43 UTC, merged