fix: set correct context menu on empty view block
opensumi/core pull request #318
Opened 2022-01-12 03:23 UTC by erha19

### Types

- [x] 🐛 Bug Fixes

### Background or solution

![Kapture 2022-01-12 at 11 21 58](https://user-images.githubusercontent.com/9823838/149058282-6e11c969-3028-4fc0-8d1b-9ca0af427557.gif)

### Changelog

set correct context menu on empty view block

2022-01-12 05:35 UTC, lengthmin requested changes

2022-01-12 05:35 UTC, lengthmin commented on packages/file-tree-next/src/browser/services/file-tree-model.service.ts
> +        this.contextMenuDecoration.removeTarget(this.contextMenuFile);
要不加点注释？稍微解释一下

2022-01-12 06:19 UTC, lengthmin requested changes

2022-01-12 06:19 UTC, lengthmin commented on packages/file-tree-next/src/browser/services/file-tree-model.service.ts
> +        this.contextMenuDecoration.removeTarget(this.contextMenuFile);
简单理解：那不应该是不管是不是在空白区域右键，都应该清除以前的右键状态嘛。因为都要新建菜单的嘛

2022-01-12 09:59 UTC, erha19 commented
> 简单理解：那不应该是不管是不是在空白区域右键，都应该清除以前的右键状态嘛。因为都要新建菜单的嘛

@lengthmin 对的，需要更新右键选择的文件以及文件的修饰状态

2022-01-13 03:14 UTC, lengthmin commented on packages/file-tree-next/src/browser/services/file-tree-model.service.ts
> +        this.contextMenuDecoration.removeTarget(this.contextMenuFile);
能把这个 if (this.contextMenuFile) 移到 if(!file) 这个判断外面嘛

2022-01-17 02:18 UTC, Ricbet commented on packages/file-tree-next/src/browser/services/file-tree-model.service.ts
> +        this.contextMenuDecoration.removeTarget(this.contextMenuFile);
> 能把这个 if (this.contextMenuFile) 移到 if(!file) 这个判断外面嘛

+1 @erha19

2022-01-17 03:09 UTC, lengthmin approved these changes
LGTM

2022-01-17 07:46 UTC, merged