WIP: refactor: update node ws channel code
opensumi/core pull request #3241
Opened 2023-12-13 11:28 UTC by bytemain

### Types

- [x] 🪚 Refactors

### Background or solution

针对 CommonHandler 的改造，能使其在后期兼容 Electron 端

2023-12-14 06:32 UTC, erha19 requested changes

2023-12-14 06:32 UTC, erha19 commented on packages/connection/src/common/utils.ts
> +import { ChannelMessage } from '.';
这里不要用 . 引用类型

2023-12-14 06:32 UTC, erha19 commented on packages/connection/src/common/ws-channel.ts
> +    this.emitter.on('reOpen', cb);
这里感觉没必要驼峰，reopen 即可

2024-01-10 10:51 UTC, bytemain commented on packages/connection/src/browser/ws-channel-handler.ts
> -    const clientMsg: MessageString = stringify({
移除掉了 clientMessage，这个功能看起来和 open 是重复的。

2024-01-11 08:37 UTC, bytemain commented
我介绍一下这次的改动：
第一个大改动就是统一所有的通信到 WSChannel，WSChannel 发送的数据包都是 fury 序列化后的，移除了目前所有的写死的依赖 jsonrpc 的 MessageConnection 的地方，都换成了 WSChannel

然后就是一些新增的代码，抽象出不同的通道（WS, net.Socket）的通信代码。

第二个就是优化了一下 RPCCenter 的架构，主要是代码重构，没有改太多逻辑，增加了一层 Proxy 抽象（方便加入 SumiRPC）。

第三个就是前后端通信都改成 WSChannel，无论 electron web，也优化了下 ws-channel 的通信消息

第四个就是 ext host 通信和 temrinal 通信改成 ws channel

2024-01-16 02:18 UTC, erha19 requested changes

2024-01-16 02:18 UTC, erha19 commented on packages/connection/src/common/proxy/legacy.ts
> +import { MessageConnection } from '@opensumi/vscode-jsonrpc';
这里的类型是不是可以内部维护，把  `@opensumi/vscode-jsonrpc` 这个依赖干掉了

2024-01-16 02:25 UTC, bytemain commented on packages/connection/src/common/proxy/legacy.ts
> +import { MessageConnection } from '@opensumi/vscode-jsonrpc';
计划中是不能现在干掉的，属于共存状态，这个 legacy proxy 会一直被使用，除非某个 rpc 迁移到 sumi proxy(下一个 pr)
而且还没完全移除 json-rpc，ExtensionWSChannel 还在用

2024-01-16 02:29 UTC, erha19 approved these changes
LGTM

2024-01-16 02:59 UTC, merged