feat: add sumi rpc
opensumi/core pull request #3284
Opened 2024-01-18 10:28 UTC by bytemain

### Types

- [x] 🎉 New Features

### Background or solution

引入了 Sumi RPC，一个通用的 Node.js RPC 解决方案，使用 Fury 进行序列化。

### Changelog

introduce a new rpc framework: sumi rpc, which is a general-purpose Node .js RPC solution, it use `fury` for serialization and deserialization

2024-01-24 06:27 UTC, bytemain commented
/next

2024-01-29 06:22 UTC, bytemain commented
/next

2024-01-30 09:44 UTC, erha19 requested changes

2024-01-30 09:44 UTC, erha19 commented on packages/connection/__test__/node/ws-channel.test.ts
> +  it('[send text] 互相通信 N 次', async () => {
测试文本统一改成英文吧

2024-01-30 09:44 UTC, erha19 commented on packages/connection/__test__/node/ws-channel.test.ts
> +  it('[send binary] 互相通信 N 次', async () => {
同上

2024-01-30 09:44 UTC, erha19 commented on packages/utils/src/buffer.ts
> +  typeof process !== 'undefined' &&
可以用 isUndefined 方法包一下

2024-01-30 09:44 UTC, erha19 commented on packages/utils/src/errors.ts
> +      $isError: true,
这种 $ 包裹变量是为啥？

2024-01-30 09:44 UTC, erha19 commented on packages/utils/src/errors.ts
> +  if (typeof value === 'object' && value.$isError) {
可以用 isObject 方法

2024-01-30 09:46 UTC, bytemain commented on packages/utils/src/errors.ts
> +      $isError: true,
这个是原来就有的代码，我换了个位置。我感觉就是为了比较特殊一些的标志吧

2024-01-30 09:46 UTC, bytemain commented on packages/utils/src/errors.ts
> +  if (typeof value === 'object' && value.$isError) {
isXxx 感觉性能没有这个好

2024-01-31 07:36 UTC, bytemain commented
/next

2024-02-01 02:03 UTC, erha19 commented on packages/utils/src/errors.ts
> +  if (typeof value === 'object' && value.$isError) {
我值得框架内的 isObjective 方法，这里 https://github.com/opensumi/core/blob/8344d6a86e82a05816a9faf6509e16796ffb2f1d/packages/utils/src/types.ts#L47

2024-02-05 11:52 UTC, bytemain commented
/next

2024-02-06 02:39 UTC, bytemain commented
/next

2024-02-06 03:38 UTC, bytemain commented
我自己升级了一下，发现了以下的问题：
- "typescript": "4.9.3",
- ClientApp.start() 的第三个参数需要改成 Channel，或者不传
- import { FileSystemWatcherServer } from '@opensumi/ide-file-service/lib/node/file-service-watcher'; 
  路径变了：'@opensumi/ide-file-service/lib/node/recursive/file-service-watcher'
- 升级 mobx react

2024-02-07 05:42 UTC, bytemain commented
@erha19 可以试试这个版本，如果还有什么 breaking 的我再兼容掉

2024-02-18 02:09 UTC, erha19 approved these changes
LGTM

2024-02-18 02:09 UTC, merged