chore(deps): update deps and types
opensumi/core pull request #3287
Opened 2024-01-19 08:17 UTC by bytemain

### Types

- [x] 🧹 Chores

### Background or solution

1. 移除 tslint comments
2. 升级一些依赖

2024-01-22 09:49 UTC, erha19 requested changes

2024-01-22 09:49 UTC, erha19 commented on packages/extension/src/node/extension.host.manager.ts
> +    extProcess.stdout!.setEncoding('utf8');
这些非必要的 ! 是不是用 ? 更好一点？感觉可能有潜在的报错

2024-01-22 09:57 UTC, bytemain commented on packages/extension/src/node/extension.host.manager.ts
> +    extProcess.stdout!.setEncoding('utf8');
ok 晚点更新下

2024-01-23 08:55 UTC, bytemain commented
"classnames": "2.3.1", 

classnames 因为类型原因，resolutions 锁死了，不如直接移除掉，自己写一个小函数来实现一样的功能

2024-01-24 06:23 UTC, erha19 approved these changes
LGTM

2024-01-24 06:24 UTC, merged