feat: support layout view size config
opensumi/core pull request #3342
Opened 2024-02-06 07:54 UTC by Ricbet

### Types

- [x] 🎉 New Features

### Background or solution

新增 layoutViewSize 的 appconfig 配置。使其可以定义 IDE 各个布局区块的默认大小

### Changelog

2024-02-07 06:37 UTC, bytemain requested changes

2024-02-07 06:37 UTC, bytemain commented on packages/core-browser/src/react-providers/config-provider.tsx
> +   * 定义 IDE 各个布局区块的默认大小（高度）
用英文吧

2024-02-07 06:37 UTC, bytemain commented on packages/scm/src/browser/scm-view-container.tsx
> +    () => appConfig.layoutViewSize?.PANEL_TITLEBAR_HEIGHT || LAYOUT_VIEW_SIZE.PANEL_TITLEBAR_HEIGHT,
似乎这样写很繁琐，可不可以有个类就是 LayoutConfig，然后他里面有属性 panelTitleBarHeight，就不用每次取值并判空了。

这个 LayoutConfig 只会在用户 ClientApp.start 的时候被生成。

2024-02-19 12:06 UTC, Ricbet commented on packages/scm/src/browser/scm-view-container.tsx
> +    () => appConfig.layoutViewSize?.PANEL_TITLEBAR_HEIGHT || LAYOUT_VIEW_SIZE.PANEL_TITLEBAR_HEIGHT,
done

2024-02-20 02:11 UTC, erha19 commented on packages/core-browser/src/layout/constants.ts
> +  PANEL_TITLEBAR_HEIGHT: number;
非常量用大写字母，总觉得怪怪的，要不用驼峰？

2024-02-20 02:21 UTC, Ricbet commented on packages/core-browser/src/layout/constants.ts
> +  PANEL_TITLEBAR_HEIGHT: number;
done

2024-02-20 02:27 UTC, bytemain commented on packages/editor/src/browser/tab.view.tsx
> +                ? { marginRight: lastMarginRight, height: appConfig.layoutViewSize!.editorTabsHeight }
看到好多 ! 操作符，感觉应该么必要吧？

2024-02-20 02:38 UTC, Ricbet commented on packages/editor/src/browser/tab.view.tsx
> +                ? { marginRight: lastMarginRight, height: appConfig.layoutViewSize!.editorTabsHeight }
目前 AppConfig 这个 interface 作为集成方的配置项接口，很多属性都是可选的。而 opensumi 本身内部在使用 appConfig 时依然用的 AppConfig 这个 interface，所以需要加上 !

2024-02-20 06:34 UTC, erha19 approved these changes
LGTM

2024-02-20 07:52 UTC, bytemain approved these changes

2024-02-20 07:52 UTC, merged