fix: layout view state logic and improve panel style
opensumi/core pull request #3344
Opened 2024-02-18 14:29 UTC by erha19

### Types

- [x] 🐛 Bug Fixes

### Background or solution

### Changelog

- 优化部分面板样式，解决布局容器切换时存在的更新问题

2024-02-19 02:44 UTC, bytemain commented on packages/core-browser/src/services/storage-service.ts
> -   * 验证是否还有空间生育用来存储另一个工作区配置
笑死

2024-02-19 02:45 UTC, bytemain requested changes

2024-02-19 02:45 UTC, bytemain commented on packages/main-layout/src/browser/tabbar/tabbar.service.ts
> +  currentContainerId = '__NONE__';
这个会是 breaking change 了吧，我感觉好多地方都判 currentContainerId === '' 的，集成方应该也用到了

2024-02-19 02:55 UTC, erha19 commented on packages/main-layout/src/browser/tabbar/tabbar.service.ts
> +  currentContainerId = '__NONE__';
这个在之前未升级 React18 的默认值是 undefined，当前仅有在 AppConfig 内声明 ：
```ts

defaultPanels: {
  bottom: ''
}
```

这种情况下这个值才可能是 `''`

2024-02-19 02:58 UTC, bytemain commented on packages/main-layout/src/browser/tabbar/tabbar.service.ts
> +  currentContainerId = '__NONE__';
![CleanShot 2024-02-19 at 10 57 44@2x](https://github.com/opensumi/core/assets/13938334/c06120dd-bfb5-49dd-bbc0-3e6aa1ea990d)

不是的吧，我们是把 `''` 当成没有选择任何容器的。

2024-02-19 03:02 UTC, erha19 commented on packages/main-layout/src/browser/tabbar/tabbar.service.ts
> +  currentContainerId = '__NONE__';
是的，目前 `''` 也是代表着没有选择任何容器，只是初始值从 undefined -> __NONE__ ，这个是由于 mobx 目前不会将  `undefined -> ''` 作为一个 Change 事件处理

2024-02-20 02:36 UTC, erha19 commented
纯前端集成需要修改的内容：
1. 文件名修改
```diff
- import { IRPCProtocol, RPCProtocol } from '@opensumi/ide-connection/lib/common/rpcProtocol';
+ import { IRPCProtocol, RPCProtocol } from '@opensumi/ide-connection/lib/common/ext-rpc-protocol';
```

2. 依赖升级
"react-dom": "^18.2.0",
"react": "^18.2.0",
"mobx": "^6.12.0",
"mobx-react-lite": "^4.0.5",

需要保障 react 及 mobx 等依赖仅有一份

3. 如果使用 Webpack4，可移除多余的 external 配置
```diff
- externals: {
-    react: 'React',
-    'react-dom': 'ReactDOM',
- },
```

4. 修改集成中使用的所有 `ReactDOM.render` 写法，采用 `ReactDOM.createRoot` 替代

5. 纯前端 `Render` 层如自定义，需要修改，渲染函数从 React.ReactNode 修改为了 (props) => React.ReactNode

6. 使用了 mobx 的地方需要在 construction 阶段调用一下 makeObservable(this);

2024-02-20 02:44 UTC, Ricbet commented on packages/main-layout/src/browser/tabbar/styles.module.less
> +  + [class^='tab_panel__'] {
这里不能直接 .tab_panel 吗

2024-02-20 02:50 UTC, erha19 commented on packages/main-layout/src/browser/tabbar/styles.module.less
> +  + [class^='tab_panel__'] {
不能，这里的 tab_panel 是在另外的样式文件定义的, 这里用的话 hash 值对不上

2024-02-20 02:53 UTC, Ricbet commented on packages/main-layout/src/browser/tabbar/styles.module.less
> +  + [class^='tab_panel__'] {
搜了下好像就只有这个样式文件有 tab_panel

2024-02-20 02:55 UTC, erha19 commented on packages/main-layout/src/browser/tabbar/styles.module.less
> +  + [class^='tab_panel__'] {
你说得对，我看错了应该

2024-02-20 03:04 UTC, Ricbet approved these changes

2024-02-20 06:31 UTC, bytemain approved these changes

2024-02-20 06:31 UTC, merged