feat: unified connection with different backend
opensumi/core pull request #3348
Opened 2024-02-20 06:49 UTC by bytemain

### Types

- [x] 🎉 New Features

### Background or solution

this close: #1270

previous we use wschannel to communicate with backend in Web, in electron, we create a new socket.

here we unified web and electron, all of those are using WSChannel

### Changelog

2024-02-20 07:38 UTC, erha19 requested changes

2024-02-20 07:38 UTC, erha19 commented on packages/connection/src/electron/common-channel-handler.ts
> +    super('common-channel-4-electron', logger);
为啥要加个 4

2024-02-20 07:38 UTC, erha19 commented on packages/connection/src/node/common-channel-handler.ts
> +    super('common-channel', logger);
这类常量用一些更有意义的变量名管理一下吧

2024-02-20 07:43 UTC, bytemain commented on packages/connection/src/node/common-channel-handler.ts
> +    super('common-channel', logger);
这个 id 没有在代码其他地方用到，我能想到的用处就是调试的时候能方便看出来这个类代表的啥。

2024-02-20 07:43 UTC, bytemain commented on packages/connection/src/electron/common-channel-handler.ts
> +    super('common-channel-4-electron', logger);
done

2024-02-21 06:26 UTC, erha19 approved these changes

2024-02-21 06:59 UTC, merged