feat: support simple testing decorations
opensumi/core pull request #335
Opened 2022-01-17 12:46 UTC by Ricbet

### Types

- [x] 🎉 New Features

### Background or solution

![Kapture 2022-01-17 at 20 43 33](https://user-images.githubusercontent.com/20262815/149771595-5cc2ed53-fad9-4029-bc42-c1939fcf8a24.gif)

PS: 点击触发还未实现

### Changelog
实现简单的 Testing Decorations 装饰器

2022-01-17 12:51 UTC, Aaaaash commented on packages/testing/src/browser/icons/icons.ts
> +export const testingColorIconFailed = registerColor(
这个挪到 packages/theme/src/common/color-tokens 吧

2022-01-17 12:52 UTC, hacke2 commented on packages/testing/src/browser/test-decorations.ts
> +    const args = encodeURIComponent(JSON.stringify([testIdWithMessages]));
args 给谁用？

2022-01-17 12:53 UTC, erha19 requested changes

2022-01-17 12:53 UTC, erha19 commented on packages/testing/src/browser/icons/icons.ts
> +  [TestResultState.Errored]: 'sumi_testing_icon_iconFailed',
这里的 `key` 应该是样式名？感觉可以不和框架名硬编码，不需要 `.sumi` 前缀或者直接用 `module css` 就行了

2022-01-17 12:56 UTC, hacke2 commented on packages/testing/src/browser/test-decorations.ts
> +    this.setDecorations(this.currentUri);
这个没有副作用？

2022-01-17 12:58 UTC, hacke2 commented on packages/testing/src/common/constants.ts
> +  [TestResultState.Errored]: localize('testState.errored', 'Errored'),
这些好像没国际化

2022-01-17 12:59 UTC, Ricbet commented on packages/testing/src/browser/icons/icons.ts
> +export const testingColorIconFailed = registerColor(
我改

2022-01-17 13:00 UTC, Ricbet commented on packages/testing/src/browser/test-decorations.ts
> +    const args = encodeURIComponent(JSON.stringify([testIdWithMessages]));
后面有注释，我干脆这里也注释掉好了

2022-01-17 13:00 UTC, Ricbet commented on packages/testing/src/browser/icons/icons.ts
> +  [TestResultState.Errored]: 'sumi_testing_icon_iconFailed',
那我 sumi 前缀去掉好了，和 debug 的全局样式保持一致

2022-01-17 13:01 UTC, hacke2 commented on packages/testing/src/browser/test-decorations.ts
> +    const args = encodeURIComponent(JSON.stringify([testIdWithMessages]));
没有引用竟然没有报错

2022-01-17 13:01 UTC, Ricbet commented on packages/testing/src/browser/test-decorations.ts
> +    this.setDecorations(this.currentUri);
没有

2022-01-17 13:02 UTC, hacke2 commented on packages/testing/src/browser/test-decorations.ts
> +      isWholeLine: true,
为什么是 true？

2022-01-17 13:03 UTC, hacke2 commented on packages/testing/src/browser/test-decorations.ts
> +    return true;
这是干啥的

2022-01-17 13:14 UTC, Ricbet commented on packages/testing/src/browser/test-decorations.ts
> +    return true;
抽象类的事件，暂时先不用管

2022-01-18 03:10 UTC, erha19 approved these changes
LGTM

2022-01-18 03:10 UTC, merged