WIP: feat: implement design module
opensumi/core pull request #3350
Opened 2024-02-20 08:02 UTC by Ricbet

### Types

- [x] 🎉 New Features
- [x] 💄 Style Changes

### Background or solution

### Changelog

2024-02-22 03:48 UTC, bytemain commented
好像你的 import {} 里的 order 被调了一遍，可以先把这个变更提个 pr

2024-02-22 03:51 UTC, bytemain requested changes

2024-02-22 03:51 UTC, bytemain commented on packages/comments/src/browser/tree/comment-node.tsx
> +        className={cls(styles.segment, designService.wrapStyles(styles.expansion_toggle), getIcon('arrow-right'), {
这种应该全部改成 hooks 风格比较好：
```
useDesignStyles(styles.xxxx)
```


直接放在 className 的属性中的话，会导致每次渲染都要计算一次

2024-02-22 13:21 UTC, Ricbet commented on packages/comments/src/browser/tree/comment-node.tsx
> +        className={cls(styles.segment, designService.wrapStyles(styles.expansion_toggle), getIcon('arrow-right'), {
done

2024-02-28 07:28 UTC, erha19 requested changes

2024-02-28 07:28 UTC, erha19 commented on packages/design/src/browser/design.contribution.ts
> +  onStart() {}
没用的删了吧

2024-02-28 07:28 UTC, erha19 commented on packages/design/src/browser/style/global.less
> +.design-dark,
这两个 css 跟 `.vs-dark` 和 `.vs` 的关系是啥？在同个 Root 上吗？

2024-02-28 08:30 UTC, erha19 requested changes

2024-02-28 08:30 UTC, erha19 commented on packages/design/src/browser/override/editor-tab.service.tsx
> +    <Popover id={uid} title='关闭' onClickAction={handleClick} display={display}>
中文国际化一下

2024-02-28 09:08 UTC, Ricbet commented on packages/design/src/browser/override/editor-tab.service.tsx
> +    <Popover id={uid} title='关闭' onClickAction={handleClick} display={display}>
done

2024-02-28 10:43 UTC, erha19 requested changes

2024-02-28 10:43 UTC, erha19 commented on packages/components/src/icon/iconfont/iconMap.ts
> +  'send1': 'send1',
这里的 icon 还是用含义更好的 key 吧，1,2 这种很奇怪，最终会在 iconfont.html 那个页面看到

2024-02-28 10:43 UTC, erha19 commented on packages/components/src/icon/iconfont/iconMap.ts
> +  'diuqi': 'diuqi',
还有这个中文拼音的 key

2024-02-28 10:43 UTC, erha19 commented on packages/components/src/icon/iconfont/iconMap.ts
> +  'clear1': 'clear1',
这里也是

2024-02-28 10:43 UTC, erha19 commented on packages/components/src/icon/iconfont/iconMap.ts
> +  'zhongxin': 'zhongxin',
这里也是

2024-02-28 11:08 UTC, bytemain requested changes

2024-02-28 11:08 UTC, bytemain commented on .yarnrc.yml
> +npmRegistryServer: 'https://registry.npmmirror.com/'
这个应该移除掉比较好

2024-02-28 11:34 UTC, Ricbet commented on packages/components/src/icon/iconfont/iconMap.ts
> +  'send1': 'send1',
都改好了

2024-02-29 03:07 UTC, erha19 commented on packages/components/src/icon/iconfont/iconMap.ts
> +  'send2': 'send2',
漏了一个

2024-02-29 03:22 UTC, Ricbet commented on packages/components/src/icon/iconfont/iconMap.ts
> +  'send2': 'send2',
done

2024-02-29 03:53 UTC, erha19 approved these changes
LGTM

2024-02-29 03:56 UTC, bytemain approved these changes

2024-02-29 03:56 UTC, merged