feat: sumi rpc support read stream
opensumi/core pull request #3362
Opened 2024-02-26 09:38 UTC by bytemain

### Types

- [x] 🎉 New Features

### Background or solution

previously, we just read full content of a file, if the file is so large, it will consume many memories, so our program maybe oom.

I took a look at the applicable scenarios that can be changed:
- calculate md5
- guess encoding
- load file content

### Changelog

sumi rpc support read stream

2024-03-04 09:11 UTC, Ricbet commented on packages/connection/src/common/ws-channel.ts
> +const serializer = oneOf7([
后面的7是啥

2024-03-04 09:13 UTC, bytemain commented on packages/connection/src/common/ws-channel.ts
> +const serializer = oneOf7([
入参长度为 7，因为里面的实现是用 switch 展开了 7 个 case

![CleanShot 2024-03-04 at 15 43 39@2x](https://github.com/opensumi/core/assets/13938334/b295cc6a-4141-4d64-9872-19035cc74b7d)

2024-03-05 06:24 UTC, bytemain commented
等到 monaco 0.45 的时候，就可以接入这个 stream 了：
![CleanShot 2024-03-05 at 14 23 10@2x](https://github.com/opensumi/core/assets/13938334/46d25bf0-aebb-4e3c-89b5-6bd436922929)

2024-03-05 06:27 UTC, Ricbet submitted a review, later dismissed
LGTM

2024-03-05 06:27 UTC, Aaaaash approved these changes

2024-03-05 06:34 UTC, erha19 requested changes

2024-03-05 06:34 UTC, erha19 commented on packages/connection/benchmarks/frame-decoder.bench.ts
> +/* eslint-disable no-console */
这个好像是多余的？

2024-03-05 06:34 UTC, erha19 commented on packages/connection/src/common/fury-extends/any.ts
> +        case 'VSCODE_URI':
VSCODE_URI 可以找个全局变量存一下

2024-03-05 06:39 UTC, bytemain commented on packages/connection/benchmarks/frame-decoder.bench.ts
> +/* eslint-disable no-console */
嗯 写了个框架没做，我把这个文件删了吧

2024-03-05 06:50 UTC, erha19 approved these changes
LGTM

2024-03-05 08:34 UTC, merged