chore: initialization ai native module
opensumi/core pull request #3368
Opened 2024-02-28 08:10 UTC by Ricbet

### Types

- [x] 🎉 New Features

### Background or solution

初始化 ai native 模块，空实现

### Changelog

2024-02-28 08:40 UTC, pipiiiiii commented on packages/core-browser/src/ai-native/ai-config.service.ts
> +    if (!capabilities) {
这个和上面的逻辑可以合并下

2024-02-28 08:53 UTC, Ricbet commented on packages/core-browser/src/ai-native/ai-config.service.ts
> +    if (!capabilities) {
done

2024-02-29 06:45 UTC, erha19 requested changes

2024-02-29 06:45 UTC, erha19 commented on packages/ai-native/src/node/index.ts
> +      servicePath: AiBackSerivcePath,
Ai -> AI

2024-02-29 06:45 UTC, erha19 commented on packages/core-browser/src/react-providers/config-provider.tsx
> +  aiNativeConfig?: IAiNativeConfig;
ai 这种名词缩写还是大写，不然后续框架内会出现很多种写法，统一大写吧

2024-02-29 07:56 UTC, Ricbet commented on packages/core-browser/src/react-providers/config-provider.tsx
> +  aiNativeConfig?: IAiNativeConfig;
ok，统一都用大写吧

2024-02-29 09:10 UTC, erha19 approved these changes

2024-02-29 09:14 UTC, merged