feat: support ai inline chat
opensumi/core pull request #3378
Opened 2024-03-05 03:07 UTC by Ricbet

### Types

- [x] 🎉 New Features

### Background or solution

- [x] 支持 inline chat 功能
- [x] 支持通过 contribution api

### Changelog

2024-03-05 10:04 UTC, bytemain approved these changes

2024-03-05 10:04 UTC, bytemain commented on packages/ai-native/src/browser/ai-core.contribution.ts
> +@Domain(
有 Domain 了就不用 @Injectable() 了

2024-03-05 11:00 UTC, Ricbet commented on packages/ai-native/src/browser/ai-core.contribution.ts
> +@Domain(
done

2024-03-05 13:48 UTC, bytemain commented on packages/ai-native/src/browser/ai-core.contribution.ts
> +  handleSettingGroup(settingGroup: ISettingGroup[]) {
我看了下源码，这个方法不是用来注册 setting group 的，整个 core 中都没有使用这个来注册，应该是给集成方用来最后删掉，修改某些配置项的。

可以用 `registerSetting` 这个声明周期来注册某个配置项和某个配置组。
或者直接用 `preferenceSettingsService.registerSettingSection` / `preferenceSettingsService.registerSettingGroup`

2024-03-05 13:48 UTC, bytemain commented on packages/ai-native/src/browser/ai-core.contribution.ts
> +  handleSettingSections(settingSections: { [key: string]: ISettingSection[] }) {
同上，不要用这个来注册 sections

2024-03-05 13:50 UTC, bytemain commented on packages/ai-native/src/browser/components/Loading.tsx
> +export const Loading = React.memo((props: { className?: string }) => (
可以放到 ide-components 里吗

2024-03-05 13:52 UTC, bytemain commented on packages/ai-native/src/browser/index.ts
> +    const aiNativeConfig: AINativeConfigService = injector.get(AINativeConfigService);
为啥要放在这个地方，应该要放在 AINativeBrowserContribution.initialize 里面吧，AINativeConfigService 也可以改成单例

2024-03-06 02:33 UTC, Ricbet commented on packages/ai-native/src/browser/ai-core.contribution.ts
> +  handleSettingGroup(settingGroup: ISettingGroup[]) {
done

2024-03-06 03:24 UTC, Ricbet commented on packages/ai-native/src/browser/index.ts
> +    const aiNativeConfig: AINativeConfigService = injector.get(AINativeConfigService);
done

2024-03-06 03:31 UTC, Ricbet commented on packages/ai-native/src/browser/components/Loading.tsx
> +export const Loading = React.memo((props: { className?: string }) => (
可以。ide-components 已经有 loading 组件了，这里我通过 design 模块去控制吧

2024-03-06 03:44 UTC, Ricbet commented on packages/ai-native/src/browser/components/Loading.tsx
> +export const Loading = React.memo((props: { className?: string }) => (
不太好控制，目前 useDesignStyles 的 hooks 是在 core-browser 模块的，components 模块还不能直接引，这里后面再开个 pr 解决吧

2024-03-06 06:41 UTC, erha19 requested changes

2024-03-06 06:41 UTC, erha19 commented on packages/core-browser/src/components/ai-native/enhanceIcon/styles.module.less
> +    background: url(https://mdn.alipayobjects.com/huamei_5nm5zc/afts/img/A*6ZoQRIRuFkcAAAAAAAAAAAAADlrAAQ/original)
这个可以转成 base64

2024-03-06 06:41 UTC, erha19 commented on packages/core-browser/src/components/ai-native/enhanceIcon/styles.module.less
> +    color: #fff !important;
这里的 color 应该没用？

2024-03-06 06:41 UTC, erha19 commented on packages/startup/entry/sample-modules/ai-native.contribution.ts
> +          const prompt = `优化以下代码：\n\`\`\`\n ${crossCode}\`\`\``;
所有 Prompt 建议统一到一个 Prompt 目录里面按照功能区维护，不然代码里面容易耦合太多跟逻辑无关的语句，目前我这边测试下来，Prompt 语句用英文，最后再控制模型用特定语言输出效果更好，而不是通过中文。

2024-03-06 06:43 UTC, Aaaaash commented on packages/startup/entry/sample-modules/ai-native.contribution.ts
> +          const prompt = `优化以下代码：\n\`\`\`\n ${crossCode}\`\`\``;
我倒觉着，Prompt 是不是可以配置更好？

2024-03-06 06:48 UTC, pipiiiiii commented on packages/startup/entry/sample-modules/ai-native.contribution.ts
> +          const prompt = `优化以下代码：\n\`\`\`\n ${crossCode}\`\`\``;
有设计过一个promptManager
[packages/ai-native/src/browser/prompts/sumi.command.ts](https://github.com/opensumi/core/blob/4e9cb01aada23eb979af9efde37ea1b3c49f844d/packages/ai-native/src/browser/prompts/prompt-manager.ts)
https://github.com/opensumi/core/blob/4e9cb01aada23eb979af9efde37ea1b3c49f844d/packages/ai-native/src/browser/prompts/sumi.command.ts
可以评估下是否需要

2024-03-06 07:00 UTC, erha19 commented on packages/startup/entry/sample-modules/ai-native.contribution.ts
> +          const prompt = `优化以下代码：\n\`\`\`\n ${crossCode}\`\`\``;
> 有设计过一个promptManager [packages/ai-native/src/browser/prompts/sumi.command.ts](https://github.com/opensumi/core/blob/4e9cb01aada23eb979af9efde37ea1b3c49f844d/packages/ai-native/src/browser/prompts/prompt-manager.ts) https://github.com/opensumi/core/blob/4e9cb01aada23eb979af9efde37ea1b3c49f844d/packages/ai-native/src/browser/prompts/sumi.command.ts 可以评估下是否需要

感觉这个不错，可以参考搞一下

2024-03-06 07:13 UTC, Ricbet commented on packages/core-browser/src/components/ai-native/enhanceIcon/styles.module.less
> +    color: #fff !important;
子 dom 是个图标，需要设置成白色

2024-03-06 07:27 UTC, Ricbet commented on packages/startup/entry/sample-modules/ai-native.contribution.ts
> +          const prompt = `优化以下代码：\n\`\`\`\n ${crossCode}\`\`\``;
这里只是在 sample 里去注册 inline chat 的代码示例，还没有涉及到 prompt 管理的逻辑。

后面是会把这个 promptManager 给 cherry-pick 过来，只不过不在这个 pr 里做

2024-03-06 07:33 UTC, Ricbet commented on packages/core-browser/src/components/ai-native/enhanceIcon/styles.module.less
> +    background: url(https://mdn.alipayobjects.com/huamei_5nm5zc/afts/img/A*6ZoQRIRuFkcAAAAAAAAAAAAADlrAAQ/original)
done

2024-03-06 07:33 UTC, erha19 submitted a review, later dismissed
LGTM

2024-03-06 08:25 UTC, bytemain approved these changes

2024-03-06 08:27 UTC, merged