feat: when click file node, resize the big pannel
opensumi/core pull request #3389
Opened 2024-03-10 08:39 UTC by ckmilse

### Types

- [ ] 🎉 New Features

### Background or solution
如果之前用户点击pannel 放大按钮，把teminal 终端放到最大时，回头点击文件树中的文件，
一般情况下，还是期望直接看到文件内容的， 所以 点击文件树时，把放大的pannel 重新缩小

### Changelog

2024-03-10 08:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/opensumi/core?pullRequest=3389) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/opensumi/core?pullRequest=3389) before we can accept your contribution.<br/><hr/>**陈科-哈哈** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/opensumi/core?pullRequest=3389) it.</sub>

2024-03-12 07:18 UTC, bytemain submitted a review, later dismissed

2024-03-12 07:19 UTC, bytemain commented
👍 good point, thanks for your contribution!

2024-03-12 07:22 UTC, erha19 requested changes

2024-03-12 07:22 UTC, erha19 commented on packages/file-tree-next/src/browser/services/file-tree-model.service.ts
> +        // 如果panel打开，则将最大化的panel, 变小
小问题，这里的注释，中英文之间加个空格，或使用中文注释，可以参考修改为：
```
如果存在最大化面板，则将最大化的面板缩小
```
@ckmilse

2024-03-12 07:26 UTC, erha19 commented on packages/file-tree-next/src/browser/services/file-tree-model.service.ts
> +        // 如果panel打开，则将最大化的panel, 变小
这里对于面板是否最大化的判断存在问题，这里的 flag 为 true 并不代表面板处于最大化，只是底部面板存在打开的面板而已

2024-03-12 07:28 UTC, erha19 commented on packages/file-tree-next/src/browser/services/file-tree-model.service.ts
> +        // 如果panel打开，则将最大化的panel, 变小
这里可以通过 `IContextKeyService` 服务获取 `bottomFullExpanded` 这个值来判断是否存在最大化面板

2024-03-13 15:13 UTC, ckmilse commented on packages/file-tree-next/src/browser/services/file-tree-model.service.ts
> +        // 如果panel打开，则将最大化的panel, 变小
fix; 通过 bottomExpanded 应该更清晰。不过RETRACT_BOTTOM_PANEL 貌似会自动处理 非最大的情况，所以之前没有发现实际运行有什么问题。

2024-03-14 02:28 UTC, erha19 submitted a review, later dismissed
LGTM

2024-03-14 05:59 UTC, bytemain commented
测试用例挂了，是因为我们的 MockInjector 里没有 IMainLayout.

看看哪些用例挂了，然后加一下这个这个 Token 和一个 Mock 类

可以看下这个文件：tools/dev-tool/src/injector-helper.ts

2024-03-15 03:32 UTC, erha19 approved these changes
LGTM

2024-03-15 03:37 UTC, erha19 commented
@ckmilse 这里还有另一个单测受影响了，可以参考这个文档调试一下 [单元测试](https://opensumi.com/zh/docs/develop/how-to-contribute#%E5%8D%95%E5%85%83%E6%B5%8B%E8%AF%95)

2024-03-19 05:52 UTC, bytemain approved these changes

2024-03-24 04:47 UTC, ckmilse commented
@bytemain 再帮忙试试。我本地单测跑过了

2024-03-24 05:24 UTC, bytemain commented
这个 lint 是我们的 main 分支挂了，在 #3436 中修了

2024-03-26 08:27 UTC, bytemain commented
这个 ci 我之后来修一下吧

2024-03-28 03:08 UTC, bytemain commented
修复这个测试应该是在测试用例中添加 RETRACT_BOTTOM_PANEL 相关的处理逻辑，看它是否正常工作。

原来的修复是把错误忽略掉了，已经修改。

2024-03-28 11:36 UTC, bytemain approved these changes

2024-03-28 11:37 UTC, merged

2024-03-31 13:28 UTC, ckmilse commented
> 这个 ci 我之后来修一下吧

抱歉。之前白天一般在公司，不登github .拖了太长时间。thanks