fix: fix default layout state
opensumi/core pull request #3392
Opened 2024-03-11 06:39 UTC by erha19

### Types

- [x] 🐛 Bug Fixes

### Background or solution

close #3365 

### Changelog

fix default layout config

2024-03-11 06:40 UTC, erha19 commented on packages/core-browser/src/components/layout/default-layout.tsx
> +          defaultSize={layout.left?.currentId ? layout.left?.size || 310 : 49}
之前由于 mobx 升级挂了，导致 size 不更新，才修改了这个默认布局，现在改回去了

2024-03-11 06:45 UTC, bytemain approved these changes

2024-03-12 03:18 UTC, erha19 commented on packages/main-layout/src/browser/tabbar/renderer.view.tsx
> -    tabbarService.viewReady.resolve();
核心修复在这里，原有的 `viewReady` 依赖 `updatePanelVisibility` 方法的同步渲染逻辑，在升级 React18 及 mobx6 后该逻辑失效了

2024-03-12 03:25 UTC, bytemain requested changes

2024-03-12 03:25 UTC, bytemain commented on packages/main-layout/src/browser/tabbar/panel.view.tsx
> -    tabbarService.panelSize = customPanelSize || panelSize || 335;
改成 protected panelSize 吧，可以防止这样误用

2024-03-12 03:25 UTC, bytemain commented on packages/main-layout/src/browser/tabbar/bar.view.tsx
> -      tabbarService.barSize = barSize + panelBorderSize;
改成 protected barSize 吧，可以防止这样误用

2024-03-12 03:25 UTC, bytemain commented on packages/main-layout/src/browser/tabbar/renderer.view.tsx
> -    tabbarService.viewReady.resolve();
这个不能删掉的吧，好几个地方依赖这个 viewReady？
这个真不能删

![CleanShot 2024-03-12 at 11 24 56@2x](https://github.com/opensumi/core/assets/13938334/fff54238-5a93-421b-8bd2-56ab87971ad3)

2024-03-12 03:29 UTC, bytemain commented
ok，那也处理一下这个没有 componentInfos 的情况：
![CleanShot 2024-03-12 at 11 26 29@2x](https://github.com/opensumi/core/assets/13938334/c759515a-59ef-448e-8ba4-10fea3102292)

2024-03-12 03:35 UTC, erha19 commented on packages/main-layout/src/browser/tabbar/bar.view.tsx
> -      tabbarService.barSize = barSize + panelBorderSize;
这里还有外部引用，暂时先保留 public 了

2024-03-12 03:35 UTC, erha19 commented on packages/main-layout/src/browser/tabbar/bar.view.tsx
> -      tabbarService.barSize = barSize + panelBorderSize;
算了，我改成 get 方法吧

2024-03-12 03:39 UTC, erha19 commented
close #3364

2024-03-12 03:52 UTC, bytemain requested changes

2024-03-12 03:52 UTC, bytemain commented on packages/main-layout/src/browser/tabbar/tabbar.service.ts
>    // currentContainerId 默认值应该为一个非空且唯一的字符串，避免在切换容器时触发 MobX 不变错误
is this comment outdated? now the NONE_CONTAINER_ID is undefined

2024-03-12 03:52 UTC, bytemain commented on packages/main-layout/src/browser/tabbar/tabbar.service.ts
> +      this.viewReady.resolve();
我还是 有一些小疑问，viewReady 的意思是组件已经准备好了，和barsize 没有关系吧，barSize 为 0 是隐藏，但是组件还是准备好了。

比如以下这个场景：
barSize 为 0，用户想通过 getTabbarHandler 拿到某个 panel，然后设置它的高度或者 barSize，可是我们之前用的都是要等到 viewReady 后才能取 getTabbarHandler

2024-03-12 04:01 UTC, erha19 commented on packages/main-layout/src/browser/tabbar/tabbar.service.ts
> +      this.viewReady.resolve();
那这里应该改成 isDefined 判断，这里实际上就是需要一个能确切获取到值的时机

2024-03-12 05:03 UTC, bytemain approved these changes

2024-03-12 06:29 UTC, merged