feat: support ai native chat & chat agent
opensumi/core pull request #3394
Opened 2024-03-11 12:49 UTC by Ricbet

### Types

- [x] 🎉 New Features

### Background or solution

1. pick 之前 ai 分支关于 chat 面板和 chat agent 相关功能实现，见 commits 提交列表
2. 代码优化
3. 实现 `registerChatFeature` 模块 api，包含两个 feature

**支持 `registerWelcome` api**
代码示例如下
```typescript
registry.registerWelcome(
  new MarkdownString(`<img src='https://mdn.alipayobjects.com/huamei_htww6h/afts/img/A*66fhSKqpB8EAAAAAAAAAAAAADhl8AQ/original' />
  嗨，我是您的专属 AI 小助手，我在这里回答有关代码的问题，并帮助您思考</br>您可以提问我一些关于代码的问题`),
  [
    {
      icon: getIcon('send-hollow'),
      title: '生成 Java 快速排序算法',
      message: '生成 Java 快速排序算法',
    },
  ],
);
```
注册了该方法后，会在 chat 面板顶部的展示这个欢迎内容。
![image](https://github.com/opensumi/core/assets/20262815/e97639ad-62ab-4630-9459-4d626aa6bd53)
> 其中提交代码和创建 PR 是 chat agent 插件提供的，与该 api 等价

**支持 `registerSlashCommand` api**
代码示例如下
```typescript
registry.registerSlashCommand(
  {
    name: 'Explain',
    description: '解释代码',
    isShortcut: true,
    tooltip: '解释代码',
  },
  {
    providerInputPlaceholder(value, editor) {
      return '请输入或者粘贴代码';
    },
    providerPrompt(value, editor) {
      return `Explain code: \`\`\`\n${value}\n\`\`\``;
    },
    execute: (value: string, send: TChatSlashCommandSend, editor: ICodeEditor) => {
      send(value);
    },
  },
);
```
该 api 主要用于快捷指令，会在 chat 的输入框里按下 / 符号时展示，也可以出现在输入框的上面用于快捷输入
![image](https://github.com/opensumi/core/assets/20262815/5dcfacef-b9ce-4c0b-b71e-9ceecf649771)
> 其中 /Commit 和 /PR 是由 chat agent 插件提供

### Changelog

2024-03-13 07:55 UTC, erha19 requested changes

2024-03-13 07:55 UTC, erha19 commented on packages/ai-native/package.json
> +    "abort-controller": "^3.0.0"
这个依赖是必要的吗？浏览器有一个 `AbortController` 对象可以用

2024-03-13 07:55 UTC, erha19 commented on packages/ai-native/src/browser/chat/chat-agent.service.ts
> +import { flatMap } from 'lodash';
从 lodash/xxx 引入

2024-03-13 07:55 UTC, erha19 commented on packages/ai-native/src/browser/chat/chat-model.ts
> +      } else if (progress.kind === 'markdownContent') {
这些 Kind 可以规范到一个变量里

2024-03-13 07:55 UTC, erha19 commented on packages/ai-native/src/browser/chat/chat.module.less
> +      color: var(--design-text-color-common);
这个变量在哪声明的？--design-text-color-common

2024-03-13 07:55 UTC, erha19 commented on packages/ai-native/src/browser/components/ChatEditor.tsx
> +    }, 1000);
这里的 1000 延迟是为了视觉效果？

2024-03-13 07:55 UTC, erha19 commented on packages/ai-native/src/browser/components/ChatEditor.tsx
> +        <Popover id={`ai-chat-inser-${useUUID}`} title='插入代码'>
缺少国际化文本

2024-03-13 08:01 UTC, Ricbet commented on packages/ai-native/package.json
> +    "abort-controller": "^3.0.0"
误加了，我删掉

2024-03-13 08:08 UTC, Ricbet commented on packages/ai-native/src/browser/chat/chat-model.ts
> +      } else if (progress.kind === 'markdownContent') {
这些 kind 本身已经是字面量类型了，不用再放到某个变量里了吧

2024-03-13 08:13 UTC, Ricbet commented on packages/ai-native/src/browser/components/ChatEditor.tsx
> +        <Popover id={`ai-chat-inser-${useUUID}`} title='插入代码'>
done

2024-03-13 08:15 UTC, Ricbet commented on packages/ai-native/src/browser/components/ChatEditor.tsx
> +    }, 1000);
是的

2024-03-13 08:16 UTC, Ricbet commented on packages/startup/entry/sample-modules/ai-native.contribution.ts
> +          title: '生成 Java 快速排序算法',
这里是 sample 代码示例，用于展示 api 的使用，不需要把这里的国际化放在内置的 i18n 里

2024-03-13 08:17 UTC, Ricbet commented on packages/types/vscode/typings/vscode.proposed.chat.d.ts
> +
done

2024-03-13 08:18 UTC, Ricbet commented on packages/types/vscode/typings/vscode.proposed.chatAgents2.d.ts
> +
done

2024-03-13 08:21 UTC, Ricbet commented on packages/types/vscode/typings/vscode.proposed.interactive.d.ts
> +		/**
done

2024-03-14 03:08 UTC, erha19 requested changes

2024-03-14 03:28 UTC, Ricbet commented on packages/core-node/src/ai-native/base-back.service.ts
> +      // console.log(`Received chunk: ${chunk}`);
done

2024-03-14 03:29 UTC, Ricbet commented on packages/core-node/src/ai-native/base-back.service.ts
> +      // console.log('Stream ended.');
这个文件我得再调整一下，mock 数据应该放在 startup 里

2024-03-14 03:40 UTC, Ricbet commented on packages/core-node/src/ai-native/base-back.service.ts
> +      // console.log('Stream ended.');
迁移到了这里 https://github.com/opensumi/core/blob/efff2607584a4e658816fde6e8a8d7e959a65714/packages/startup/entry/sample-modules/ai-native/ai.back.service.ts#L21

2024-03-14 06:32 UTC, erha19 approved these changes
design token 待处理，先合吧，LGTM

2024-03-14 06:33 UTC, Ricbet commented
> design token 待处理，先合吧，LGTM

可以在另个 pr 里解决

2024-03-14 06:34 UTC, merged