feat: imporve tree property performance
opensumi/core pull request #3398
Opened 2024-03-13 06:43 UTC by erha19

### Types

- [x] 🐛 Bug Fixes

### Background or solution

close #3395

### Changelog

improve tree property performance

2024-03-13 07:12 UTC, bytemain requested changes

2024-03-13 07:12 UTC, bytemain commented on packages/components/src/recycle-tree/tree/TreeNode.ts
> +        this._path = new Path(`${Path.separator}${this.name}`).toString();
这个 new Path 应该是没有必要的

2024-03-13 07:13 UTC, erha19 commented on packages/components/src/recycle-tree/tree/TreeNode.ts
> +        this._path = new Path(`${Path.separator}${this.name}`).toString();
先最小化改动，后续再去掉吧

2024-03-14 03:15 UTC, erha19 commented
/next

2024-03-14 03:20 UTC, bytemain approved these changes

2024-03-14 03:26 UTC, merged

2024-03-25 11:48 UTC, bytemain commented
/backport to chore/ai-native-module