WIP: feat: support ai 3 way merge
opensumi/core pull request #3404
Opened 2024-03-14 11:15 UTC by Ricbet

### Types

- [x] 🎉 New Features

### Background or solution

### Changelog

2024-03-18 13:11 UTC, bytemain requested changes

2024-03-18 13:11 UTC, bytemain commented on packages/core-browser/src/ai-native/conflict-report.service.ts
> +    if (this.aiNativeConfigService.capabilities.supportsConflictResolve === false) {
用 ! 更好吧

2024-03-18 13:11 UTC, bytemain commented on packages/core-browser/src/ai-native/conflict-report.service.ts
> +    if (this.aiNativeConfigService.capabilities.supportsConflictResolve === false) {
用 ! 更好吧

2024-03-18 13:11 UTC, bytemain commented on packages/monaco/src/browser/contrib/merge-editor/merge-editor.service.ts
> +          `AI 已处理 ${resolveLen} 处冲突，${pointLen - resolveLen} 处冲突暂未处理（仍标记为黄色部分），需人工处理`,
i18n

2024-03-18 13:11 UTC, bytemain commented on packages/monaco/src/browser/contrib/merge-editor/view/actions-manager.ts
> +      message.warning('本段冲突代码过长，暂无法通过AI解决。');
i18n

2024-03-18 13:11 UTC, bytemain commented on packages/monaco/src/browser/contrib/merge-editor/widget/resolve-result-widget.tsx
> +interface IWapperAiInlineResultProps {
Wrapper

2024-03-19 02:14 UTC, Ricbet commented on packages/ai-native/src/browser/components/ChatMarkdown.tsx
> +        renderDom.unmount();
已修复

2024-03-19 05:49 UTC, bytemain approved these changes

2024-03-19 07:14 UTC, merged