fix: inline chat reporter
opensumi/core pull request #3536
Opened 2024-04-12 07:26 UTC by Ricbet

### Types

- [x] 🐛 Bug Fixes

### Background or solution

chore: pick #3535

### Changelog

2024-04-12 07:27 UTC, hacke2 approved these changes
+1

2024-04-15 01:44 UTC, erha19 requested changes

2024-04-15 01:44 UTC, erha19 commented on packages/ai-native/src/browser/ai-editor.contribution.ts
> +      replytime: +new Date() - startTime,
这里的时间用 Date.now 感觉更符合预期？

2024-04-15 01:53 UTC, Ricbet commented on packages/ai-native/src/browser/ai-editor.contribution.ts
> +      replytime: +new Date() - startTime,
done

2024-04-15 01:59 UTC, erha19 approved these changes
LGTM

2024-04-15 06:05 UTC, merged