fix: chat thinking render
opensumi/core pull request #3544
Opened 2024-04-15 13:07 UTC by Ricbet

### Types

- [x] 🐛 Bug Fixes

### Background or solution

修复 chat 面板 thinking 不出现的问题

### Changelog

2024-04-15 13:08 UTC, Ricbet commented
/next

2024-04-15 13:22 UTC, Ricbet commented
/next

2024-04-16 02:47 UTC, bytemain requested changes

2024-04-16 02:47 UTC, bytemain commented on packages/ai-native/src/browser/components/StreamReplyRender.tsx
> -    send();
这个 send 不需要了吗

2024-04-16 03:22 UTC, Ricbet commented on packages/ai-native/src/browser/components/StreamReplyRender.tsx
> -    send();
不需要了，首次 send 的逻辑挪到了外层去控制

2024-04-16 03:33 UTC, bytemain approved these changes

2024-04-16 03:34 UTC, merged