fix: require interceptor handle react error
opensumi/core pull request #3570
Opened 2024-04-22 03:53 UTC by bytemain

### Types

- [x] 🐛 Bug Fixes

### Background or solution

我们拦截了 browser 里的 require, 如果一个插件 require 了 react-dom，我们会返回 react-dom/client 的内容给它，会导致它报错。

![CleanShot 2024-04-22 at 11 51 48@2x](https://github.com/opensumi/core/assets/13938334/305c6cb6-41de-4d24-bfd3-f399505747f1)

### Changelog

fix require interceptor return `react-dom/client` when using `react-dom`

2024-04-22 03:53 UTC, bytemain commented
/next

2024-04-22 03:55 UTC, hacke2 approved these changes
LGTM

2024-04-22 09:01 UTC, erha19 requested changes

2024-04-22 09:01 UTC, erha19 commented on packages/extension/src/browser/require-interceptor.contribution.ts
> +const reactDom16Wrapper = {
这里是不是得叫 react18 了？

2024-04-22 09:03 UTC, bytemain commented on packages/extension/src/browser/require-interceptor.contribution.ts
> +const reactDom16Wrapper = {
这个变量名的意思是在 react18 下兼容 react16

2024-04-22 09:06 UTC, erha19 submitted a review, later dismissed

2024-04-22 09:08 UTC, bytemain commented on packages/extension/src/browser/require-interceptor.contribution.ts
> +const reactDom16Wrapper = {
react18 自己的 umd 包就是这么做的，它的导出就是 react-dom/client 和 react-dom 下的东西。

2024-04-22 09:09 UTC, bytemain commented on packages/extension/src/browser/require-interceptor.contribution.ts
> +const reactDom16Wrapper = {
改名成 reactDOMWrapper 吧

2024-04-23 02:16 UTC, erha19 approved these changes

2024-04-23 02:18 UTC, merged