feat: early preference support configure prefix
opensumi/core pull request #3584
Opened 2024-04-23 13:50 UTC by bytemain

### Types

- [x] 🎉 New Features

### Background or solution

现在有 AI 模式和非 AI 模式两种，AI 模式的主题是不一样的，所以不希望 AI 模式的主题存到 localStorage 中被非 AI 模式读取到

### Changelog

2024-04-24 03:58 UTC, erha19 requested changes

2024-04-24 03:58 UTC, erha19 commented on packages/theme/src/browser/theme.contribution.ts
> +  logger: Logger;
protected readonly 对齐下格式

2024-04-24 03:58 UTC, erha19 commented on packages/utils/src/disposable.ts
> +    if (!disposable) {
这句是为了测试用的兜底逻辑吗？感觉不是很有必要

2024-04-24 04:03 UTC, bytemain commented on packages/theme/src/browser/theme.contribution.ts
> +  logger: Logger;
done

2024-04-24 07:01 UTC, hacke2 approved these changes
+1

2024-04-25 02:41 UTC, wangxiaojuan commented
/next

2024-04-25 02:47 UTC, erha19 approved these changes

2024-04-25 02:49 UTC, merged