fix(styles): fix design module style issues
opensumi/core pull request #3586
Opened 2024-04-24 08:24 UTC by bytemain

### Types

- [x] 🐛 Bug Fixes
- [x] 💄 Style Changes

### Background or solution

close: #3562

### Changelog

2024-04-25 09:32 UTC, erha19 requested changes

2024-04-25 09:32 UTC, erha19 commented on packages/ai-native/src/browser/components/WelcomeMsg.tsx
>                  }}
这里是不是可以包裹一下函数

2024-04-28 06:01 UTC, Ricbet approved these changes

2024-04-29 04:16 UTC, bytemain commented on packages/theme/src/common/css-var.ts
> +export const registerCSSVar = cssVarRegistry.register.bind(cssVarRegistry);
下面有用到，注册所有 stacking level 到 css-var 里，就可以这么用了：

```css
z-index: var(--stacking-level-popover)
```

2024-04-29 04:18 UTC, Ricbet approved these changes

2024-04-29 05:04 UTC, merged