feat: support codicon transform on popover content
opensumi/core pull request #3598
Opened 2024-04-29 07:52 UTC by erha19

### Types

- [x] 🎉 New Features

### Background or solution

### Changelog
support codicon transform on popover content

2024-04-29 07:53 UTC, erha19 commented
/next

2024-04-29 08:17 UTC, erha19 commented
/next

2024-04-29 09:22 UTC, erha19 commented
/next

2024-04-29 09:32 UTC, erha19 commented
/next

2024-04-29 09:35 UTC, Ricbet commented
底下的尖尖好像没有了

2024-04-29 09:44 UTC, erha19 commented
> 底下的尖尖好像没有了

其实有的，要细看, 被阴影盖了一层刚好跟底色接近了

2024-04-29 10:00 UTC, erha19 commented
/next

2024-04-30 02:51 UTC, bytemain commented
这个小尖尖完全看不到了，感觉要修一下吧

2024-04-30 03:08 UTC, erha19 commented
@Ricbet @bytemain 好了，层级调整了一下，让箭头盖到上面了

2024-04-30 03:08 UTC, erha19 commented
/next

2024-04-30 03:20 UTC, erha19 commented
/next

2024-04-30 03:21 UTC, bytemain requested changes

2024-04-30 03:21 UTC, bytemain commented on packages/components/src/popover/index.tsx
> +  zIndex = 10000,
改成 StackingLevel 这个枚举值吧

2024-04-30 03:28 UTC, erha19 commented on packages/components/src/popover/index.tsx
> +  zIndex = 10000,
done, 不过这里的 StackingLevel 最好给个说明性的文档或注释

2024-04-30 03:29 UTC, erha19 commented
/next

2024-04-30 03:31 UTC, bytemain commented
这里不太对，component 库不能引用到 core-browser 里的内容

2024-04-30 03:32 UTC, bytemain commented
如果不能改枚举值就算了，component 包里，直接写个 number 也一样

2024-04-30 03:45 UTC, erha19 commented
/next

2024-04-30 05:18 UTC, bytemain approved these changes

2024-04-30 05:19 UTC, bytemain commented on packages/core-browser/src/design/rule.ts
> +  PopoverComponentArrow: 1001,
要不改成 10000 ？原来就是 1w

2024-04-30 06:17 UTC, bytemain requested changes

2024-04-30 06:17 UTC, bytemain commented on packages/components/src/popover/styles.less
> +    z-index: var(--stacking-level-popover-component, 10000);
那把这个后面的数字调成 1000 吧，下面还有个 10001

2024-04-30 06:19 UTC, erha19 commented on packages/components/src/popover/styles.less
> +    z-index: var(--stacking-level-popover-component, 10000);
done

2024-04-30 06:23 UTC, bytemain submitted a review, later dismissed

2024-04-30 06:54 UTC, erha19 commented
/next

2024-04-30 07:08 UTC, erha19 commented
/next

2024-04-30 07:19 UTC, bytemain approved these changes

2024-04-30 07:46 UTC, merged