fix: diff editor refresh revive
opensumi/core pull request #3632
Opened 2024-05-08 10:14 UTC by Ricbet

### Types

- [x] 🐛 Bug Fixes

### Background or solution

修复 diff editor 刷新恢复问题

### Changelog

2024-05-08 10:21 UTC, hacke2 commented on packages/editor/src/browser/doc-model/editor-document-model-service.ts
> +      await Promise.race([Event.toPromise(this.fileSystem.onFileProviderChanged), timeout(6000)]);
可能得判断下新注册的 provider 的 scheme 是否和当前 uri 一致，否则会出等待的时候注册一个其他 scheme 导致继续执行并且还是找不到这个 provider

2024-05-08 10:27 UTC, Ricbet commented on packages/editor/src/browser/doc-model/editor-document-model-service.ts
> +      await Promise.race([Event.toPromise(this.fileSystem.onFileProviderChanged), timeout(6000)]);
done

2024-05-08 10:28 UTC, hacke2 submitted a review, later dismissed
LGTM

2024-05-08 10:36 UTC, MMhunter commented
LGTM，感觉可以先这样修（虽然可能更好的方案是对插件的 onFileSystem:git 这种进行解析预先注册一个空的，这样可以不用 6000 的 magic number）

2024-05-08 11:58 UTC, bytemain requested changes

2024-05-08 11:58 UTC, bytemain commented on packages/editor/src/browser/doc-model/editor-document-model-service.ts
> +        timeout(6000),
感觉这么搞有点 hack 🤔
如果我写了一个插件打开 git 协议，但是 git 插件没装，那整个逻辑要等 6s 才能告诉我失败了。

感觉正解应该是 restoreState 发生在插件信息都加载好了之后

2024-05-08 15:12 UTC, Ricbet commented
> LGTM，感觉可以先这样修（虽然可能更好的方案是对插件的 onFileSystem:git 这种进行解析预先注册一个空的，这样可以不用 6000 的 magic number）

done

2024-05-08 15:13 UTC, Ricbet commented on packages/editor/src/browser/doc-model/editor-document-model-service.ts
> +        timeout(6000),
done

2024-05-09 03:48 UTC, bytemain requested changes

2024-05-09 03:48 UTC, bytemain commented on packages/editor/src/browser/merge-editor/merge-editor.provider.ts
>          // 如果设置为 true，再打开时没有找到对应的 provider 会报错
注释删掉吧

2024-05-09 03:50 UTC, erha19 commented on packages/editor/src/browser/doc-model/editor-document-model-service.ts
> +  protected readonly fileSystem: FileServiceClient;
这里其实可以把 interface 补一下，不用依赖实现 FileServiceClient

2024-05-09 06:11 UTC, bytemain approved these changes

2024-05-09 06:12 UTC, merged