fix: terminal ai suggest z-index fix, remove click event
opensumi/core pull request #3644
Opened 2024-05-10 07:52 UTC by life2015

### Types

修复了终端 AI 自然语言生成命令时的布局 Z-Index 问题：
<img width="828" alt="image" src="https://github.com/opensumi/core/assets/12879047/2aa6a390-918a-4462-b578-5e393e241016">

另外就是终端「输入 # 来获取 AI 建议命令」这个文本的点击事件，可能会造成用户的误触与误解，因此去掉这个点击事件，现在只会被键盘的 「#」 触发。

- [ ] 🎉 New Features
- [x] 🐛 Bug Fixes
- [ ] 📚 Documentation Changes
- [ ] 💄 Code Style Changes
- [ ] 💄 Style Changes
- [ ] 🪚 Refactors
- [ ] 🚀 Performance Improvements
- [ ] 🏗️ Build System
- [ ] ⏱ Tests
- [ ] 🧹 Chores
- [ ] Other Changes

### Background or solution
<img width="818" alt="image" src="https://github.com/opensumi/core/assets/12879047/4c9a1cb5-75bc-4ce2-8af8-ecdfa89f4a52">
新版 Xterm.js 里面的底层 CSS 代码中，z-index 是 7，我们需要改到更大的，避免 z-index 问题。

### Changelog
-fix: terminal ai suggest z-index fix, remove click event

2024-05-10 08:05 UTC, bytemain requested changes

2024-05-10 08:05 UTC, bytemain commented on packages/ai-native/src/browser/ai-terminal/component/terminal-command-suggest-controller.module.less
> -  z-index: 3;
代码里搜一下 StackingLevel 和 var(--stacking-level

你新建一个 TerminalOverlay 的枚举值，然后这里改成使用枚举值

2024-05-10 09:03 UTC, life2015 commented on packages/ai-native/src/browser/ai-terminal/component/terminal-command-suggest-controller.module.less
> -  z-index: 3;
可

2024-05-13 09:34 UTC, bytemain approved these changes

2024-05-13 09:35 UTC, merged