WIP: refactor: channel can use custom serializer
opensumi/core pull request #3711
Opened 2024-05-23 05:42 UTC by bytemain

### Types

- [x] 🪚 Refactors

### Background or solution

### Changelog

2024-05-29 06:02 UTC, bytemain commented
/next

2024-05-29 08:07 UTC, bytemain commented
/next

2024-05-29 09:22 UTC, bytemain commented
/next

2024-05-30 06:41 UTC, erha19 requested changes

2024-05-30 06:41 UTC, erha19 commented on packages/connection/__test__/common/fury-extends/one-of.test.ts
> +import { OpenMessage, PingMessage, PongMessage, ServerReadyMessage } from '../../../lib';
test 从 src 引入才会有覆盖率统计

2024-05-31 03:01 UTC, Ricbet approved these changes
LGTM

2024-05-31 08:45 UTC, merged