WIP: feat: support multiline comment
opensumi/core pull request #3719
Opened 2024-05-27 10:04 UTC by erha19

### Types

- [x] 🎉 New Features

### Background or solution

https://github.com/opensumi/core/assets/9823838/e11c0366-981e-470d-bca5-eb31e96b1d21

### Changelog

support multiline comment

2024-05-28 10:32 UTC, erha19 commented
/next

2024-05-29 06:37 UTC, erha19 commented
/next

2024-05-29 06:51 UTC, bytemain commented
/next

2024-05-29 09:38 UTC, erha19 commented
/next

2024-05-29 11:02 UTC, bytemain requested changes

2024-05-29 11:02 UTC, bytemain commented on packages/comments/src/browser/comments.service.ts
> +      if (ranges && ranges.some((range) => range.endLineNumber <= line && line <= range.endLineNumber)) {
`range.endLineNumber <= line && line <= range.endLineNumber` 这个代码的意思不就是 `line === range.endLineNumber` 吗

2024-05-29 11:48 UTC, erha19 commented on packages/comments/src/browser/comments.service.ts
> +      if (ranges && ranges.some((range) => range.endLineNumber <= line && line <= range.endLineNumber)) {
改错了，修改回来了

2024-05-29 11:49 UTC, erha19 commented
/next

2024-05-30 00:59 UTC, erha19 commented
/next

2024-05-30 01:49 UTC, erha19 commented
/next

2024-05-30 03:38 UTC, erha19 commented
晚点补点测试代码，另外折叠评论的交互需要修改

2024-06-04 03:15 UTC, erha19 commented
由于目前多行评论默认挂载在最后一行位置，故，同一行位置可能为多行评论，也可能为单行评论，故：

将评论显示移动至 `glyphMargin` 位置，保证了同一行的多种评论可能性。

![image](https://github.com/opensumi/core/assets/9823838/25f530eb-4342-4f82-a959-ac61ce2563e7)

2024-06-04 03:52 UTC, erha19 commented
/next

2024-06-04 07:50 UTC, Ricbet commented on packages/monaco-enhance/src/browser/zone-widget.ts
直接用 monaco 自带的 zone widget 吧，这个模块下的 zone widget 已经不建议再维护了

2024-06-04 07:50 UTC, Ricbet commented on packages/monaco-enhance/src/browser/styles.less
> +    width: 100% !important;
其他地方比如 debug、dirty-diff 都用了这个模块下的 zone widget，是否也会被这个样式所影响？

2024-06-04 07:54 UTC, Ricbet commented on packages/monaco-enhance/src/browser/zone-widget.ts
packages/ai-native/src/browser/widget/inline-diff/inline-diff-widget.tsx
这个文件

2024-06-04 08:01 UTC, erha19 commented on packages/monaco-enhance/src/browser/styles.less
> +    width: 100% !important;
这个是 VS Code 上也存在的一个 Bug，一旦动态调整了 LineDecorationWidth，ZoneWidget 的宽度计算就会有问题，这里用 100% 做了兜底，我看看好不好解决，不行还是得保留这个逻辑

2024-06-05 08:29 UTC, erha19 commented on packages/monaco-enhance/src/browser/zone-widget.ts
尝试了一下，使用原生的 ZoneWidget 无法对样式进行精细化控制，后续没办法做设计上的改造，这里还是得用原有的 ZoneWidget
使用原生版本
<img width="595" alt="image" src="https://github.com/opensumi/core/assets/9823838/6bf4f97b-a199-42ec-a288-d1a7e076bf5a">

2024-06-05 08:49 UTC, erha19 commented on packages/monaco-enhance/src/browser/styles.less
> +    width: 100% !important;
Done

2024-06-06 02:12 UTC, Ricbet approved these changes
LGTM

2024-06-06 02:14 UTC, merged