feat: optimize tree performance
opensumi/core pull request #3742
Opened 2024-06-05 08:17 UTC by bytemain

### Types

- [x] 🎉 New Features

### Background or solution

移除了树路径计算中的 new Path 相关逻辑

### Changelog
optimize tree performance

2024-06-06 02:04 UTC, erha19 commented
@bytemain 测试有点问题，看看

2024-06-12 02:37 UTC, erha19 requested changes

2024-06-12 02:37 UTC, erha19 commented on packages/components/__tests__/recycle-tree/tree/path.test.ts
> +  it('relative path', () => {
加点通过 treePath.parse 取 basename 和 dirname 的测试

2024-06-12 03:07 UTC, bytemain commented on packages/components/__tests__/recycle-tree/tree/path.test.ts
> +      const result = treePath.parse(testcase.source);
这里有个对树的前提要求，传给 TreeNode 的 name 不能带 `/`，否则会导致计算出错，但是以前的 Path 也是会出错的，所以没差

2024-06-12 03:08 UTC, erha19 commented on packages/components/__tests__/recycle-tree/tree/path.test.ts
> +      const result = treePath.parse(testcase.source);
在 TreeNode 那里加个 warning？

2024-06-12 04:39 UTC, bytemain commented on packages/components/__tests__/recycle-tree/tree/path.test.ts
> +      const result = treePath.parse(testcase.source);
done

2024-06-12 08:25 UTC, merged