style: improve action widget styles
opensumi/core pull request #3748
Opened 2024-06-06 07:32 UTC by Ricbet

### Types

- [x] 💄 Style Changes

### Background or solution

before:
![image](https://github.com/opensumi/core/assets/20262815/03035562-2a2b-472f-8cbe-08ce7e58c174)

after:
![image](https://github.com/opensumi/core/assets/20262815/98929b57-8ab5-4635-92af-4a3cea5fb390)

### Changelog
改进 design 模式下 code action 的样式

2024-06-06 07:36 UTC, hacke2 submitted a review, later dismissed
LGTM

2024-06-06 07:37 UTC, erha19 commented
感觉可以加点 padding，太挤了边缘

2024-06-06 07:40 UTC, Ricbet commented
> 感觉可以加点 padding，太挤了边缘

加了

2024-06-06 07:42 UTC, erha19 requested changes

2024-06-06 07:42 UTC, erha19 commented on packages/design/src/browser/index.ts
> +    doOverrideMonacoColorToken();
doxxx 这种写法一般用于函数内部的 private 写法，这里感觉可以都改成  overrideColorToken...

2024-06-06 08:06 UTC, Ricbet commented on packages/design/src/browser/index.ts
> +    doOverrideMonacoColorToken();
done

2024-06-06 09:14 UTC, erha19 commented
优化展示：
<img width="189" alt="image" src="https://github.com/opensumi/core/assets/9823838/2a53600e-a071-4628-8931-bce4e2a7df87">

2024-06-11 04:05 UTC, erha19 approved these changes

2024-06-11 04:05 UTC, merged