WIP: feat: support inline hint widget
opensumi/core pull request #3762
Opened 2024-06-11 12:04 UTC by Ricbet

### Types

- [x] 🎉 New Features
- [x] 🪚 Refactors

### Background or solution

### Changelog

2024-06-13 08:06 UTC, erha19 requested changes

2024-06-13 08:06 UTC, erha19 commented on packages/ai-native/src/browser/widget/inline-hint/inline-hint-line-widget.tsx
> +        <span className={styles.text}>{`按 ${
国际化搞一下

2024-06-13 08:07 UTC, erha19 commented on packages/ai-native/src/browser/widget/inline-hint/inline-hint-line-widget.tsx
> +        <span className={styles.text}>{`按 ${
另外这里可能得从注册的快捷键里面获取当前快捷键，用户可能会修改成自定义快捷键？

2024-06-13 09:01 UTC, bytemain requested changes

2024-06-13 09:01 UTC, bytemain commented on packages/ai-native/src/browser/widget/inline-chat/inline-content-widget.tsx
> -    requestAnimationFrame(() => {
把 requestAnimationFrame 加回来吧，直接操作样式的最好都使用 rAF 包裹一下

2024-06-13 09:12 UTC, Ricbet commented on packages/ai-native/src/browser/widget/inline-hint/inline-hint-line-widget.tsx
> +        <span className={styles.text}>{`按 ${
done

2024-06-14 02:00 UTC, erha19 approved these changes

2024-06-14 02:04 UTC, merged