feat: support hover widget on diff editor
opensumi/core pull request #3774
Opened 2024-06-13 10:37 UTC by erha19

### Types

- [x] 🎉 New Features

### Background or solution

![image](https://github.com/opensumi/core/assets/9823838/06ec6c3d-864d-498b-b014-ab83fd68afc3)

### Changelog
support hover widget on diff editor

2024-06-13 13:10 UTC, erha19 commented
/next

2024-06-13 13:48 UTC, erha19 commented
/next

2024-06-13 14:51 UTC, bytemain requested changes

2024-06-13 14:51 UTC, bytemain commented on packages/ai-native/src/browser/ai-editor.contribution.ts
> +    disposables.push(this.inlineCompletionHandler.registerInlineCompletionFeature(editor.originalEditor));
这个 registerFeature 应该可以封装成一个函数吧，要不然写了六遍，现有的一个 pr 又会新增 feature

2024-06-14 02:44 UTC, Ricbet commented
diff 的左侧通常是只读文件，也需要展示 inline chat 吗

2024-06-14 02:57 UTC, erha19 commented
> diff 的左侧通常是只读文件，也需要展示 inline chat 吗

确实不需要，有个 hover widget 就行了

2024-06-15 14:45 UTC, erha19 commented
/next

2024-06-15 14:50 UTC, erha19 commented
/next

2024-06-16 13:57 UTC, erha19 commented
/next

2024-06-18 07:06 UTC, erha19 commented
/next

2024-06-19 03:09 UTC, erha19 commented on packages/ai-native/src/browser/ai-editor.contribution.ts
> +    disposables.push(this.inlineCompletionHandler.registerInlineCompletionFeature(editor.originalEditor));
Done

2024-06-19 03:11 UTC, erha19 commented
/next

2024-06-19 03:23 UTC, erha19 commented
/next

2024-06-19 03:52 UTC, erha19 commented
/next

2024-06-20 02:54 UTC, bytemain requested changes

2024-06-20 02:54 UTC, bytemain commented on packages/ai-native/src/browser/widget/inline-chat/inline-chat.feature.registry.ts
> +  private getSequenceKeyString() {
看起来可以直接写 keybindingRegistry 里面，另外的文件里也有这部分逻辑

2024-06-20 02:58 UTC, Ricbet approved these changes

2024-06-20 02:58 UTC, erha19 commented on packages/ai-native/src/browser/widget/inline-chat/inline-chat.feature.registry.ts
> +  private getSequenceKeyString() {
下个 PR 整合一下，这里修改太多了

2024-06-20 03:12 UTC, bytemain approved these changes

2024-06-20 03:17 UTC, merged