Add enum support
opensumi/core pull request #382
Opened 2022-01-23 08:39 UTC by sinoon

### Types

- [x] 🎉 New Features
- [ ] 🐛 Bug Fixes
- [ ] 📚 Documentation Changes
- [ ] 💄 Code Style Changes
- [ ] 💄 Style Changes
- [ ] 🪚 Refactors
- [ ] 🚀 Performance Improvements
- [ ] 🏗️ Build System
- [ ] ⏱ Tests
- [ ] 🧹 Chores
- [ ] Other Changes

### Background or solution

for #357 ，支持枚举配置，以及 default 提示

### Changelog

2022-01-23 08:44 UTC, lengthmin commented on scripts/watch.ts
> +  const filePatten = '*/src/**/!(*.ts|*.tsx)';
修了 但没完全修

```diff
- patten
+ pattern
```

2022-01-23 09:13 UTC, sinoon commented on scripts/watch.ts
> +  const filePatten = '*/src/**/!(*.ts|*.tsx)';
见笑了，嘿嘿

2022-01-23 09:14 UTC, sinoon commented
![image](https://user-images.githubusercontent.com/6065488/150671941-4bee075e-2fe7-4d24-8ccf-eae8a346634c.png)
在其他样式下的效果，开天默认主题的 `--kt-select-border` 变量似乎有点问题，和背景颜色一样了

2022-01-23 16:37 UTC, erha19 requested changes

2022-01-23 16:37 UTC, erha19 commented on packages/preferences/src/browser/preferenceItem.view.tsx
> +          {item === config.default && <div className={styles.select_default_option_tips}>default</div>}
这里的默认文案 `default` 应该设置一下国际化文案，可以使用 `localize` 方法，同时在 [zh-CN.lang.ts](https://github.com/opensumi/core/blob/7501cbe228da699422b84cba35e23d1077bceeed/packages/i18n/src/common/zh-CN.lang.ts) 和  [en-US.lang.ts](https://github.com/opensumi/core/blob/7501cbe228da699422b84cba35e23d1077bceeed/packages/i18n/src/common/en-US.lang.ts) 设置好正确的国际化文案

2022-01-23 16:37 UTC, erha19 commented on packages/preferences/src/browser/preferenceItem.view.tsx
> +          onMouseEnter={(index) => {
这里的函数建议抽离出来用 `useCallback` 包裹一下

2022-01-23 16:37 UTC, erha19 commented on packages/preferences/src/browser/preferenceItem.view.tsx
> +  console.log('preferenceName', preferenceName, localizedName, currentValue, schema);
这个 `log` 需要移除一下

2022-01-23 16:37 UTC, erha19 commented on packages/components/src/select/index.tsx
> +        onMouseEnter={() => onMouseEnter?.(index)}
这里 `onMouseEnter` 的参数是不是 `value, index` 会更好一点，毕竟一些情况下可能直接就去获取对应值了，不用再根据 `index` 查找一遍

2022-01-24 07:48 UTC, sinoon commented
@erha19 你提到的点都改了

2022-01-24 09:31 UTC, erha19 approved these changes
验证通过，待本周迭代版本发布后合并

2022-01-25 02:14 UTC, Aaaaash approved these changes
LGTM

2022-01-25 06:59 UTC, merged