fix: ai feature accidental invalid
opensumi/core pull request #4089
Opened 2024-10-14 02:23 UTC by Ricbet

### Types

- [x] 🐛 Bug Fixes

### Background or solution

### Changelog
修复 ai feature 偶然失效的问题

2024-10-14 03:12 UTC, bytemain requested changes

2024-10-14 03:12 UTC, bytemain commented on packages/ai-native/src/browser/contrib/problem-fix/problem-fix.controller.ts
> +      return this.featureDisposable;
这个是不是返回 Disposable.NULL 比较好。
总感觉不幂等呢，这里检测到没有 privoder， return 的 disposable 被 dispose，会导致有 provider 的时候的 featureDisposable 被销毁？

2024-10-14 05:04 UTC, hacke2 approved these changes
LGTM

2024-10-15 01:50 UTC, Ricbet commented on packages/ai-native/src/browser/contrib/problem-fix/problem-fix.controller.ts
> +      return this.featureDisposable;
done

2024-10-15 02:26 UTC, bytemain approved these changes

2024-10-15 03:27 UTC, merged