feat: implement language status
opensumi/core pull request #414
Opened 2022-01-29 06:57 UTC by hacke2

### Types

- [x] 🎉 New Features

### Background or solution

![image](https://user-images.githubusercontent.com/6399899/151651164-42bfa7b7-c4f7-475c-ade9-79890ac47c0b.png)

### Changelog
implement language status

2022-02-09 07:48 UTC, erha19 requested changes

2022-02-09 07:48 UTC, erha19 commented on packages/core-browser/src/style/codicons/generator.js
> +const fs = require('fs');
这个文件是用于在 README 里面生成图标？好像没地方调用？为啥不是用 ts？

2022-02-09 07:48 UTC, erha19 commented on packages/core-common/src/utils/arrays.ts
> +export function asArray<T>(x: T | T[]): T[];
这句跟最下面那句应该是重复定义了

2022-02-10 07:45 UTC, hacke2 commented on packages/core-browser/src/style/codicons/generator.js
> +const fs = require('fs');
这个是 README 里的脚本，之前没有落到文件中，更新 codicon 需要执行这个脚本

2022-02-14 02:24 UTC, erha19 commented on packages/core-browser/src/style/codicons/generator.js
> +const fs = require('fs');
更新后可以在 https://opensumi.github.io/core/ 这里访问到吗？

2022-02-14 03:05 UTC, hacke2 commented on packages/core-browser/src/style/codicons/generator.js
> +const fs = require('fs');
应该不行

2022-02-15 09:48 UTC, erha19 commented
@hacke2 冲突处理一下，后续关于 `@vscode/codicons` 不可商用的问题记个 issue 记录一下吧？

2022-02-16 02:50 UTC, hacke2 commented
@erha19 冲突解决了，查了下这个协议是可以商用的

![image](https://user-images.githubusercontent.com/6399899/154186963-5369ebfb-e387-4495-972a-724826077a9f.png)

2022-02-16 15:02 UTC, erha19 approved these changes

2022-02-16 16:56 UTC, merged

2022-03-16 06:18 UTC, hacke2 commented
close #135