feat: support Testing APIs and Test Explorer UI
opensumi/core pull request #421
Opened 2022-02-07 08:53 UTC by Ricbet

### Types

- [x] 🎉 New Features

### Background or solution

现在可以通过内置的测试资源管理器视图来维护测试用例树
支持从测试资源管理器视图、装饰器和内部命令来运行或调试测试用例。
且支持了更丰富的日志输出和差异对比显示

相关文档见: https://code.visualstudio.com/api/extension-guides/testing

目前可以通过安装 vscode-java-test 0.32.0 版本来进行测试

### Changelog
实现 Testing 相关 API 以及支持全新的 Testing UI

2022-02-07 11:45 UTC, erha19 requested changes

2022-02-07 11:45 UTC, erha19 commented on packages/components/src/recycle-tree/basic/tree-node.tsx
> +      <div style={{ paddingRight: '5px', display: 'flex' }}>
这里为啥没用 `Icon` 而是用 `span` 做展示？我理解样式应该统一到 `Icon` 中，用className 或 style 做微调

2022-02-07 11:45 UTC, erha19 commented on packages/components/src/recycle-tree/basic/types.ts
> +  notExpandable?: boolean;
这里的 `notExpandable` 感觉表达成 `expandable` 就行了，`false` 代表不可展开

2022-02-07 11:45 UTC, erha19 commented on packages/extension/src/browser/vscode/api/main.thread.tests.ts
> +    console.log('$appendOutputToRun', runId, taskId, output, locationDto);
这里的 `console.log` 是不是要去掉或者使用 `logger `来展示？

2022-02-07 11:45 UTC, erha19 commented on packages/extension/src/browser/vscode/api/main.thread.tests.ts
>      console.log('$signalCoverageAvailable', runId, taskId);
一样，这里应该使用 `logger`

2022-02-08 02:50 UTC, Ricbet commented on packages/components/src/recycle-tree/basic/tree-node.tsx
> +      <div style={{ paddingRight: '5px', display: 'flex' }}>
当时这里我想用 codicon 来着，我看看怎么改合适

2022-02-08 02:58 UTC, Ricbet commented on packages/components/src/recycle-tree/basic/types.ts
> +  notExpandable?: boolean;
done

2022-02-10 08:20 UTC, Ricbet commented
/publish

2022-02-16 08:09 UTC, Ricbet commented on packages/core-common/src/utils/strings.ts
> +export function count(value: string, character: string): number {
done

2022-02-16 09:23 UTC, erha19 approved these changes

2022-02-16 09:24 UTC, merged