fix: 修复 tabbar 插入 item 后 hidden 状态丢失问题
opensumi/core pull request #442
Opened 2022-02-15 09:34 UTC by EAGzzyCSL

### Types

- [x] 🐛 Bug Fixes

### Background or solution

containerId 同时也是入参的名字，导致之前这里漏了取当前遍历项的 containerId

### Changelog

- 修复 tabbar 插入 item 后 hidden 状态丢失问题

2022-02-15 09:39 UTC, erha19 requested changes

2022-02-15 09:39 UTC, erha19 commented on packages/main-layout/src/browser/tabbar/tabbar.service.ts
> +      const containerId = info.options!.containerId;
这里是不是追加判断一下是否有 `containerId` , 或者用 ?.containerId, `no-non-null-asserted-optional-chain` 后续会设置为 error

2022-02-15 10:52 UTC, EAGzzyCSL commented on packages/main-layout/src/browser/tabbar/tabbar.service.ts
> +      const containerId = info.options!.containerId;
加了~

2022-02-16 01:51 UTC, erha19 approved these changes

2022-02-16 01:51 UTC, merged

2022-02-16 02:32 UTC, erha19 commented
/publish