feat: support debug console ansi escape sequence output
opensumi/core pull request #469
Opened 2022-02-18 07:42 UTC by Ricbet

### Types

- [x] 🎉 New Features

### Background or solution

效果如下

#### 256 前景色
![image](https://user-images.githubusercontent.com/20262815/154633132-55c5b238-41fc-4d1e-9958-f8aa391e322d.png)

#### 256 背景色
![image](https://user-images.githubusercontent.com/20262815/154633228-d3ff60c1-f005-4a36-b74a-426cb96559bf.png)

#### 基本样式码
可参考文档 https://zh.wikipedia.org/wiki/ANSI%E8%BD%AC%E4%B9%89%E5%BA%8F%E5%88%97#%E9%80%89%E6%8B%A9%E5%9B%BE%E5%BD%A2%E5%86%8D%E7%8E%B0%EF%BC%88SGR%EF%BC%89%E5%8F%82%E6%95%B0
![image](https://user-images.githubusercontent.com/20262815/154639208-affdc236-fb87-4e55-b6d9-5e4f82cf100e.png)

### Changelog
调试控制台支持 ANSI escape codes 输出

2022-02-18 07:53 UTC, bytemain commented
you're so good. it's better to add some test cases.

2022-02-18 07:57 UTC, Ricbet commented
> you're so good. it's better to add some test cases.

下次一定

2022-02-18 08:16 UTC, erha19 commented
加个测试吧，这周版本锁需求啦，下个迭代再上

2022-02-18 09:47 UTC, Ricbet commented
> 加个测试吧，这周版本锁需求啦，下个迭代再上

done

2022-03-01 01:35 UTC, erha19 requested changes

2022-03-01 01:35 UTC, erha19 commented on packages/debug/src/browser/view/console/debug-console-tree.model.service.ts
> +        setTimeout(() => this.debugContextKey.contextInDebugConsole.set(false));
这里是不是用 `requestAnimationFrame` 好一点？

2022-03-02 03:57 UTC, erha19 approved these changes

2022-03-02 03:57 UTC, merged