fix: 修复侧边栏 tab 拖拽时拖拽图显示问题
opensumi/core pull request #520
Opened 2022-02-28 08:51 UTC by EAGzzyCSL

### Types

- [x] 🐛 Bug Fixes

### Background or solution

拖拽时图片显示成顶栏上的头像部分了。

<img width="267" alt="image" src="https://user-images.githubusercontent.com/6220109/155952655-87826f26-be50-47d4-b157-d8d2feac65be.png">

### Changelog

- fix: 修复侧边栏 tab 拖拽时拖拽图显示问题

2022-02-28 09:43 UTC, erha19 requested changes

2022-02-28 09:43 UTC, erha19 commented on packages/main-layout/src/browser/tabbar/bar.view.tsx
> +                    setTimeout(() => {
既然改到这里了，是不是可以试试 `requestAnimationFrame` 替换 `setTimeout` 这种写法？

2022-02-28 11:39 UTC, EAGzzyCSL commented on packages/main-layout/src/browser/tabbar/bar.view.tsx
> +                    setTimeout(() => {
有道理！

2022-03-01 01:36 UTC, erha19 approved these changes

2022-03-01 01:36 UTC, merged