feat: update rc-menu to 9
opensumi/core pull request #611
Opened 2022-03-11 10:54 UTC by iamxukai

### Types
- [x] Other Changes

### Background or solution
closes [#531 ](https://github.com/opensumi/core/issues/531)
related: [#409](https://github.com/opensumi/core/issues/409) [#530](https://github.com/opensumi/core/pull/530)
### Changelog
update rc-menu to 9

2022-03-11 11:02 UTC, iamxukai commented on packages/core-browser/src/components/actions/index.tsx
> +      const menuItem = item.props.children[0].props.data as MenuNode;
You can make a breakpoint to see why.
Item.props.children is an array with two elements and the first element contains props.data.

2022-03-11 11:22 UTC, bytemain commented
需要合一下 main 再 push -f 一下，要过这个 lint

2022-03-11 11:24 UTC, bytemain commented
在 rc-menu@7 我们好像通过 ref 做了一些事情，看这个 PR 中去掉了它们，这应该会影响到菜单的工作吧？

2022-03-11 11:28 UTC, iamxukai commented
@bytemain 
我测试了文件子菜单栏的自动保存功能以及帮助的子菜单栏的关于功能，功能是正常的。

2022-03-11 11:51 UTC, bytemain commented
研究了一下，确实应该没什么影响。我会请求一些 changes。

2022-03-11 11:55 UTC, bytemain requested changes

2022-03-11 11:55 UTC, bytemain commented on packages/components/src/menu/MenuItem.tsx
> +            return <Item {...rest} title={title} />;
原来这里的 ref 是为了让外部传入 onKeyDown 事件，现在 rc-menu 已经支持了。所以需要从外部透传进来。

1. 在 `MenuItemProps` 中添加一个 onKeyDown 回调声明
2. 把这里的 28 行到 35 行也删除掉就行了。

2022-03-11 11:55 UTC, bytemain commented on packages/components/src/menu/SubMenu.tsx
> +    return <RcSubMenu {...this.props} popupClassName={popupClassName} />;
1. 在 SubMenuProps 中添加 onKeyDown 回调的声明
2. 删除 33 至 37 行

2022-03-12 06:30 UTC, bytemain approved these changes
LGTM
测试确实没什么问题

@Aaaaash @hacke2 看看呢

你们在各自的集成上有用到 menu 相关的 onKeyDown 能力的吗

2022-03-14 01:44 UTC, Aaaaash approved these changes
LGTM

2022-03-14 01:46 UTC, erha19 commented
等待 2.16 迭代完成后合入，见 #605

2022-03-17 13:13 UTC, merged