feat: implement forceNewSession and silent to authentication api
opensumi/core pull request #615
Opened 2022-03-13 01:28 UTC by hacke2

### Types

- [x] 🎉 New Features

### Background or solution

<img width="698" alt="93688797-A018-49F7-8A01-0C7B1A10C715" src="https://user-images.githubusercontent.com/6399899/158040914-256a8f0c-4010-44cc-9418-91c8aa988e99.png">

package.json
```json
{
  "publisher": "opensumi",
  "name": "auth-demo",
  "version": "1.0.0",
  "engines": {
    "vscode": "^1.22.0"
  },
  "activationEvents": [
    "*"
  ],
  "main": "./index",
  "contributes": {
    "commands": [
      {
        "command": "auth.login",
        "title": "Login"
      },
      {
        "command": "auth.relogin",
        "title": "Relogin"
      },
      {
        "command": "auth.logout",
        "title": "Logout"
      }
    ]
  },
  "dependencies": {
    "express": "^4.17.1",
    "passport": "^0.4.1",
    "passport-github2": "^0.1.12"
  }
}

```

index.js
```js
const vscode = require('vscode');
const express = require('express');
const passport = require('passport');
const { Strategy: GitHubStrategy } = require('passport-github2');

const AUTH_PORT = 10899;
const clientID = '7629552d4c5f0116620d';
const clientSecret = 'fd24f43e4b0248fed5abba5a1ba49037c67b4bc9';

let init = false;

class Deferred {
  resolve;
  reject;

  promise = new Promise((resolve, reject) => {
      this.resolve = resolve;
      this.reject = reject;
  });
}

function initGitHubStrategy(url) {
  passport.use(new GitHubStrategy({
    clientID,
    clientSecret,
    callbackURL: `${url}/auth/github/callback`,
  }, (accessToken, refreshToken, profile, cb) => {
      // format user
      const user = {
        id: profile.id,
        name: profile.username,
        displayName: profile.displayName,
        photo: profile.photos && profile.photos[0] && profile.photos[0].value,
        accessToken,
        refreshToken,
        profile,
      }
      return cb(null, user);
    }
  ));
}

async function createServer(url, port) {
  if (!init) {
    // gitHub strategy 只需初始化一次
    await initGitHubStrategy(url);
    init = true;
  }

  let serverTimer;
  const userDeferred = new Deferred();

  function cancelServerTimer() {
		clearTimeout(serverTimer);
  }

  const serverPromise = new Promise((resolve, reject) => {
    serverTimer = setTimeout(() => {
			reject(new Error('Timeout waiting for port'));
    }, 5000);

    const app = express();
    app.use(passport.initialize());

    // 使用 passport 进行 github 授权跳转
    app.get('/auth/github', passport.authenticate('github', { session: false }));
    // 授权成功后的回调地址
    app.get('/auth/github/callback', passport.authenticate('github', { session: false }), (req, res) => {
      userDeferred.resolve(req.user);
      res.send('授权成功，请关闭该页面');
    });
    const server = app.listen(port, () => resolve(server));
  });

  let server;
  try {
    server = await serverPromise
  } finally {
    cancelServerTimer();
  }

  return {
    server,
    userDeferred,
  };

}

exports.activate =  function(context) {
  const sessions = context.globalState.get('sessions') || [];
  const onDidChangeSessions = new vscode.EventEmitter();

  context.subscriptions.push(vscode.commands.registerCommand('auth.login', async () => {
    const session = await vscode.authentication.getSession('github', [], {
      createIfNone: true,
    });
    vscode.window.showInformationMessage('hello ' + session.account.label);
  }));

  context.subscriptions.push(vscode.commands.registerCommand('auth.relogin', async () => {
    const session = await vscode.authentication.getSession('github', [], {
      forceNewSession: {
        detail: 'I want opensumi~'
      },
    });
    vscode.window.showInformationMessage('hello ' + session.account.label);
  }));

  context.subscriptions.push(vscode.commands.registerCommand('auth.logout', async () => {
    const session = await vscode.authentication.getSession('github', []);
    vscode.authentication.logout('github', session.id);
  }));

  context.subscriptions.push(vscode.authentication.registerAuthenticationProvider('github', 'Github', {
    onDidChangeSessions: onDidChangeSessions.event,
    getSessions: async () => sessions,
    createSession: async (scopes) => {
      const url = `http://0.0.0.0:${AUTH_PORT}`;
      // 启动 auth server，提供回调地址
      const { server, userDeferred } = await createServer(url, AUTH_PORT);
      // 访问验证服务器
      vscode.env.openExternal(vscode.Uri.parse(`${url}/auth/github`));
      // 等待用户进行验证授权
      const user = await userDeferred.promise;
      const session = {
        id: user.id,
        accessToken: user.accessToken,
        account: { label: user.displayName || user.name, id: user.id },
        scopes,
      };
      const sessionIndex = sessions.findIndex((s) => s.id === session.id);
      if (sessionIndex > -1) {
        sessions.splice(sessionIndex, 1, session);
      } else {
        sessions.push(session);
      }
      context.globalState.update('sessions', sessions);
      onDidChangeSessions.fire({ added: [session], removed: [], changed: [] });
      server.close();
      return session;
    },
    removeSession: async (id) => {
      const sessionIndex = sessions.findIndex((session) => session.id === id);
      if (sessionIndex > -1) {
        const session = sessions[sessionIndex];
        sessions.splice(sessionIndex, 1);
        context.globalState.update('sessions', sessions);
        onDidChangeSessions.fire({
          added: [],
          removed: [session],
          changed: [],
        });
      }
    },
  }));
}

```

### Changelog
implement forceNewSession and silent to authentication api

2022-03-14 06:10 UTC, erha19 requested changes

2022-03-14 06:10 UTC, erha19 commented on packages/extension/__tests__/hosted/api/vscode/ext.host.authentication.test.ts
> +      account: { label: '蛋总', id: 'xinglong.wangwxl' },
这里不硬编码中文名字吧，直接用 opensumi 代替就行了

2022-03-16 06:19 UTC, hacke2 commented
fixed #615

2022-03-18 03:17 UTC, Aaaaash approved these changes

2022-03-21 02:29 UTC, erha19 approved these changes

2022-03-21 02:30 UTC, merged