fix: cannot create connection in electron
opensumi/core pull request #616
Opened 2022-03-13 07:21 UTC by bytemain

### Types

- [x] 🐛 Bug Fixes

### Background or solution

### Changelog
Fix cannot create connection to backend in electron

2022-03-13 08:39 UTC, erha19 requested changes

2022-03-13 08:39 UTC, erha19 commented on packages/core-browser/src/bootstrap/app.ts
> +    type?: 'electron' | 'web' | string,
后面的 `string` 好像没必要了？有别的直接定义一个 type 就行了

2022-03-16 07:40 UTC, erha19 submitted a review, later dismissed

2022-03-16 07:43 UTC, hacke2 commented on packages/core-browser/src/bootstrap/connection.ts
> +  const { createSocketConnection } = require('@opensumi/ide-connection/lib/node');
这里会不会把 node 里的也打包进去

2022-03-16 08:30 UTC, yantze commented on packages/core-browser/src/bootstrap/connection.ts
> +  const { createSocketConnection } = require('@opensumi/ide-connection/lib/node');
不用加这块，直接使用 electron preload 的内容吧，类似这样
<img width="692" alt="image" src="https://user-images.githubusercontent.com/2226423/158548353-b98744fe-1f8a-41e1-8b7c-76b1ebfaf59a.png">

2022-03-16 08:32 UTC, yantze commented on tools/electron/src/browser/app.tsx
> +    const messageConntect = createSocketConnection(netConnection);
这里也是一样的，使用 `electronEnv.getSocketConnection()`

2022-03-16 08:54 UTC, bytemain commented
那就统一收敛到 electronEnv.getSocketConnection() 吧

2022-03-16 08:58 UTC, bytemain commented on packages/core-browser/src/bootstrap/connection.ts
> +  const { createSocketConnection } = require('@opensumi/ide-connection/lib/node');
在 window 上挂的东西在这个 electronEnv 中也能拿到吗？

2022-03-16 08:59 UTC, bytemain commented on packages/core-browser/src/bootstrap/connection.ts
> +  const { createSocketConnection } = require('@opensumi/ide-connection/lib/node');
看了一下，electronEnv 就是一个 global，和 window 是同一个东西咯？

2022-03-16 09:02 UTC, yantze commented on packages/core-browser/src/bootstrap/connection.ts
> +  const { createSocketConnection } = require('@opensumi/ide-connection/lib/node');
> 看了一下，electronEnv 就是一个 global，和 window 是同一个东西咯？

是，electronEnv 赋值到了 global

2022-03-17 02:35 UTC, bytemain commented
merge 了 main 之后，好像带来了一个 jsx 文件的 format

2022-03-17 03:33 UTC, erha19 approved these changes

2022-03-17 03:36 UTC, yantze approved these changes
LGTM

2022-03-17 06:08 UTC, erha19 approved these changes

2022-03-17 06:09 UTC, yantze approved these changes

2022-03-17 06:09 UTC, merged