fix: improve file tree navigator
opensumi/core pull request #818
Opened 2022-04-12 10:56 UTC by erha19

### Types

- [x] 🐛 Bug Fixes

### Background or solution

### Changelog

improve file tree navigator

2022-04-12 15:11 UTC, bytemain commented
#814 中提到的内容还没有实现：

<img width="980" alt="image" src="https://user-images.githubusercontent.com/13938334/162994659-4410fae4-f395-450a-b57a-cd4a92ac03dc.png">


其他的 behavior works good，跟预期一样~

2022-04-13 02:23 UTC, erha19 commented
没注意看，#814 的需求单独开 PR 实现好了

2022-04-13 02:50 UTC, bytemain requested changes

2022-04-13 02:50 UTC, bytemain commented on packages/file-tree-next/src/browser/services/file-tree-model.service.ts
> +      const lastFile = roots[roots.length - 1].node;
roots.length 为 0 的情况下要判断一下。

2022-04-13 03:20 UTC, bytemain commented
/publish

2022-04-13 03:36 UTC, erha19 commented
给删除添加了队列操作逻辑，整体删除更加顺滑
![Kapture 2022-04-13 at 11 30 39](https://user-images.githubusercontent.com/9823838/163095111-247b2bf6-db54-409b-a3c3-00fc81e3c02c.gif)

2022-04-13 03:37 UTC, bytemain approved these changes

2022-04-13 08:22 UTC, merged