feat: add ExtensionsInitializedEvent
opensumi/core pull request #873
Opened 2022-04-20 05:59 UTC by Aaaaash

### Types

- [x] 🎉 New Features

### Background or solution

### Changelog
-  add ExtensionsInitializedEvent

2022-04-20 05:59 UTC, Aaaaash commented
/publish

2022-04-20 06:09 UTC, hacke2 commented
这个事件干啥的？

2022-04-20 06:23 UTC, Aaaaash commented
> 这个事件干啥的？

表示插件已经扫描并且实例化完了，之前集成会依赖 extensionService 的这个时机，实现方式是比较 hack 的调用了 extensionService，改成事件比较合理

2022-04-21 06:51 UTC, bytemain requested changes

2022-04-21 06:51 UTC, bytemain commented on packages/extension/src/browser/types.ts
> +export class ExtensionsInitializedEvent extends BasicEvent<IExtension[]> {}
> 表示插件已经扫描并且实例化完了，之前集成会依赖 extensionService 的这个时机，实现方式是比较 hack 的调用了 extensionService，改成事件比较合理

把这个事件的作用加个注释吧

2022-04-21 07:22 UTC, bytemain approved these changes

2022-04-22 03:57 UTC, merged