feat: support VSCode `TerminalProfileProvider` API
opensumi/core pull request #92
Opened 2021-12-06 04:11 UTC by bytemain

### 变动类型

- [x] 新特性提交

### 需求背景和解决方案

disscussion: https://github.com/opensumi/core/discussions/371

close: #34

### changelog

Support VSCode TerminalProfileProvider API
Show help message when create terminal error
Make create terminal async

2021-12-28 13:20 UTC, Aaaaash commented on configs/ts/tsconfig.resolve.json
> +      "@opensumi/ide-language-server/lib/*": ["../packages/language-server/src/*"],
我们似乎没有这个包？好像是上古传下来的..

2021-12-30 06:03 UTC, Aaaaash commented
这个咋说? 要再 rebase 下吗

2021-12-30 06:04 UTC, lengthmin commented
啥 rebase？

这个现在空实现已经完成了，这两天把内部启动逻辑接到 TerminalProfile，就能把这个合了。

2021-12-30 07:51 UTC, Aaaaash commented
/publish

2022-01-04 06:41 UTC, hacke2 commented
> 这两天把内部启动逻辑接到 TerminalProfile

这个啥时候搞？

2022-01-04 07:56 UTC, lengthmin commented
> > 这两天把内部启动逻辑接到 TerminalProfile
> 
> 这个啥时候搞？

ing 了，在写了

2022-01-07 08:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/opensumi/core?pullRequest=92) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/opensumi/core?pullRequest=92) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/opensumi/core?pullRequest=92) it.</sub>

2022-01-14 11:58 UTC, lengthmin commented
20220114:
今天就先写到这吧，还差这么一些：
1. 之前把创建 node-pty 的 cols,rows 参数给去掉了，现在发现还是需要这部分，需要加回来
2. 看 vscode 使用了一个 xterm-headless，看看用法

2022-01-18 12:57 UTC, lengthmin commented
20220118:

现在可以通过 profile.service 获取到默认的 profile 并启动了。

比如在 unix 下可以获取到 /etc/shell 的第一项启动。

这里还需要参考 vscode 的逻辑补充一些各 shell 相关的 args，比如 bash 等需要有个 args --login 等 

下一步可以引入 vscode 中各平台的相关配置项

```ts
	ProfilesWindows = 'terminal.integrated.profiles.windows',
	ProfilesMacOs = 'terminal.integrated.profiles.osx',
	ProfilesLinux = 'terminal.integrated.profiles.linux',
	DefaultProfileLinux = 'terminal.integrated.defaultProfile.linux',
	DefaultProfileMacOs = 'terminal.integrated.defaultProfile.osx',
	DefaultProfileWindows = 'terminal.integrated.defaultProfile.windows',
	UseWslProfiles = 'terminal.integrated.useWslProfiles',
```

2022-01-19 07:26 UTC, lengthmin commented
还有几个问题记录一下：

1. vscode 为什么会默认启动我的 zsh，而我们相同的 profile 逻辑，却启动了 bash

2022-01-19 12:26 UTC, lengthmin commented
进度：
1. 还没有搞清楚为什么 vscode 默认启动我的 zsh 而不是 bash（按理说启动逻辑应该是一样的了）
2. 优化了一个 preference.get 的 typing，然后就可以优化掉各种用 get 时用的 typing 了（比如 !!，比如 non-null assert）。。。下一个单独 pr 来

现在在修各种 test case

2022-01-20 09:39 UTC, erha19 requested changes

2022-01-20 09:39 UTC, erha19 commented on package.json
> +    "test:cov": "cross-env NODE_OPTIONS=--max_old_space_size=32768 node --trace-warnings ./node_modules/.bin/jest --coverage --forceExit --detectOpenHandles",
这个是你测试加的吗？

2022-01-20 09:39 UTC, erha19 commented on packages/editor/src/browser/doc-model/editor-document-model-service.ts
> +    timer = window.setTimeout(() => {
为啥要加个 `window` 感觉可以省略掉

2022-01-20 09:39 UTC, erha19 commented on packages/terminal-next/src/browser/terminal.controller.ts
> +   * @deprecated 请使用 `createClientWithWidget2`. Will removed in 2.14.0
2.14.0 发布不会带这个修改，中间版本应该是 2.15.，2.16.0，这里标注 2.17.0 移除吧

2022-01-20 15:04 UTC, lengthmin commented on packages/editor/src/browser/doc-model/editor-document-model-service.ts
> +    timer = window.setTimeout(() => {
因为这次改动了 preference.get<T>  的 typing，如果设置了 `defaultValue` 就返回 `T` 而不是 `T | undefined`。
原来这一行的上面在获取 timeout 的时间，原来的 typing 是 `number | undefined`，这是不正确的，因为设置了 defaultValue 了，所以现在获取到的 timeout 的时间的 typing 就是 `number`。

然后这个 setTimeout 就报错了，因为会 infer 到 Node.setTimeout，而 Node.setTimeout 的返回值是一个 Node.Timer，这里就编译不过了。

2022-01-25 08:23 UTC, lengthmin commented
支持 terminal.type 设置的 shell

2022-01-25 12:12 UTC, lengthmin commented
0125:
支持了 contributions.terminal 的注入

正在实现兼容旧的 terminal.type。

2022-01-26 07:56 UTC, hacke2 commented on packages/terminal-next/src/browser/terminal.api.ts
> +    const client = await this.controller.createClientWithWidget2({
这些方法之后都是这么命名吗？

2022-01-26 08:49 UTC, lengthmin commented on packages/terminal-next/src/browser/terminal.api.ts
> +    const client = await this.controller.createClientWithWidget2({
应该要这样，毕竟是不兼容更新。

2022-01-27 07:47 UTC, lengthmin commented
还有新增的启动事件：onTerminalProfile:xxxx

2022-02-14 03:19 UTC, Aaaaash approved these changes

2022-02-14 06:41 UTC, yantze commented
<img width="954" alt="image" src="https://user-images.githubusercontent.com/2226423/153811718-2babbfa7-e63f-4ec7-9fd3-9f450beaad9b.png">
看起来这个分支有个报错关于 TerminalClient 的,有可能是 init 时机有点问题

2022-02-14 06:55 UTC, bytemain commented
> <img alt="image" width="954" src="https://user-images.githubusercontent.com/2226423/153811718-2babbfa7-e63f-4ec7-9fd3-9f450beaad9b.png">
> 
> 看起来这个分支有个报错关于 TerminalClient 的,有可能是 init 时机有点问题

就是直接启动的 termianl 面板报的这个错嘛？还是其他啥操作报了这个错？electron or web？

2022-02-14 06:57 UTC, yantze commented
> > <img alt="image" width="954" src="https://user-images.githubusercontent.com/2226423/153811718-2babbfa7-e63f-4ec7-9fd3-9f450beaad9b.png">
> > 看起来这个分支有个报错关于 TerminalClient 的,有可能是 init 时机有点问题
> 
> 就是直接启动的 termianl 面板报的这个错嘛？还是其他啥操作报了这个错？electron or web？

复现路径：
1. npm run start
2. web 启动后打开 Temrinal
3. 控制台里面就有这个报错

2022-02-14 07:00 UTC, bytemain commented
<img width="807" alt="image" src="https://user-images.githubusercontent.com/13938334/153815286-54c4211e-cdf8-44ba-9c53-21d76127ea0c.png">

看起来是这个地方报了错，onError 的回调中，我研究一下。

2022-02-14 09:03 UTC, bytemain commented
已经修复了。
有一个启动失败展示失败原因的 feature，之后可以加个配置项默认不启动这个，让集成方通过配置项启动。

我又自己 review 了一遍，LGTM。

2022-02-14 09:46 UTC, yantze approved these changes
LGTM

2022-02-16 03:03 UTC, hacke2 approved these changes
LGTM

2022-02-16 03:29 UTC, erha19 commented
合啦

2022-02-16 03:29 UTC, merged