feat: remove shortid dependency
opensumi/core pull request #923
Opened 2022-04-27 04:19 UTC by dqhl76

### Types

- [ ] 🎉 New Features

### Background or solution

Use [nanoid](https://github.com/ai/nanoid) to replace [shortid]

close #882  

### Changelog

2022-04-27 04:58 UTC, dqhl76 commented
![image](https://user-images.githubusercontent.com/69136320/165443687-78c92b71-ef5a-4511-baa7-cfce74334599.png)

这个报错似乎是和我的修改无关，其似乎于快捷键功能相关

2022-04-27 06:13 UTC, bytemain commented
@erha19 #784 不是还没合吗，这个 pr 合进去之后你那边又冲突了

2022-04-27 08:36 UTC, bytemain submitted a review, later dismissed

2022-04-27 08:40 UTC, dqhl76 commented
@bytemain 请问刚才是重新运行了一下CI，它就不报错了吗

2022-04-27 08:46 UTC, bytemain commented
> @bytemain 请问刚才是重新运行了一下CI，它就不报错了吗

是的，那个 case 可能有点问题，已经记录在了 #849

2022-04-27 08:49 UTC, dqhl76 commented
> > @bytemain 请问刚才是重新运行了一下CI，它就不报错了吗
> 
> 是的，那个 case 可能有点问题，已经记录在了 #849

好的，明白了🚀

2022-04-27 12:48 UTC, erha19 requested changes

2022-04-27 12:48 UTC, erha19 commented on packages/core-common/src/uuid.ts
> -import * as shortid from 'shortid';
@dqhl76 目前有冲突，可以把这块代码挪到 `packages/utils` 里面了

2022-04-27 12:48 UTC, erha19 commented on packages/connection/package.json
> +    "nanoid": "^3.3.3",
这里的依赖没必要了

2022-04-27 12:58 UTC, dqhl76 commented on packages/core-common/src/uuid.ts
> -import * as shortid from 'shortid';
我需要在本地获取新的版本merge，然后继续在这个PR提交commit嘛？

2022-04-27 12:59 UTC, erha19 commented on packages/core-common/src/uuid.ts
> -import * as shortid from 'shortid';
继续在这个 PR 提交就行，你可以本地 merge 一下 main 分支

2022-04-27 13:01 UTC, bytemain commented
需要解决一下冲突：

首先把 opensumi/core:main 设置为你的上游。

```sh
git remote add upstream https://github.com/opensumi/core.git
git pull upstream main --rebase
```

然后就可以解决冲突了

2022-04-27 13:13 UTC, dqhl76 commented
> 需要解决一下冲突：
> 
> 首先把 opensumi/core:main 设置为你的上游。
> 
> ```shell
> git remote add upstream https://github.com/opensumi/core.git
> git pull upstream main --rebase
> ```
> 
> 然后就可以解决冲突了

好的，我已经解决了冲突，感谢您的指导，剩下我需要做的是：
1. 去除connection中的shortid依赖（修改package）
2.  将原本位于packages/core-common的nanoid，转移到packages/utils

2022-04-28 02:02 UTC, erha19 requested changes

2022-04-28 02:02 UTC, erha19 commented on packages/connection/src/browser/ws-channel-handler.ts
> +    this.clientId = clientId || `CLIENT_ID_${nanoid()}`;
目前 OpenSumi 框架内有一个基础的依赖规则 ，见 [依赖潜规则](https://opensumi.com/zh/docs/develop/how-to-design-module#%E5%85%B3%E4%BA%8E%E4%BE%9D%E8%B5%96%E7%9A%84%E6%BD%9C%E8%A7%84%E5%88%99)，即可以通过 `@opensumi/ide-core-browser` 引入 `@opensumi/ide-core-common` 进而 引入 `@opensumi/ide-utils` 内的方法。

你这里比较好的写法是 `import { uuid } from '@opensumi/ide-core-browser';` 然后使用封装的 uuid 方法，而不是直接依赖 nanoid 这个依赖

2022-04-28 02:04 UTC, dqhl76 commented on packages/connection/src/browser/ws-channel-handler.ts
> +    this.clientId = clientId || `CLIENT_ID_${nanoid()}`;
我当时看这个地方之前也没有引用‘core-common’里的uuid，所以就没有直接改掉

2022-04-28 02:07 UTC, erha19 commented on packages/connection/src/browser/ws-channel-handler.ts
> +    this.clientId = clientId || `CLIENT_ID_${nanoid()}`;
嗯，目前这里应该是可以从 `@opensumi/ide-core-common` 引入的，这样一些公共的方法能统一在 `utils` 模块管理，测试以及修改都会简单一些

2022-04-28 09:48 UTC, dqhl76 commented
[CI/coverage(12.x)](https://github.com/opensumi/core/runs/6204207677?check_suite_focus=true)这个似乎又是和我本次PR无关的问题失败了，我在我fork的仓库中跑了一下是没问题的，但我没有办法让它重新在这个仓库重新运行， @erha19 @bytemain  可以帮我重新跑一下这个CI吗

2022-04-28 09:50 UTC, bytemain requested changes

2022-04-28 09:50 UTC, bytemain commented on packages/startup/entry/web/render-app.tsx
> +import { nanoid } from 'nanoid';
这里也从 ide-utils 里引吧

2022-04-28 09:52 UTC, dqhl76 commented on packages/startup/entry/web/render-app.tsx
> +import { nanoid } from 'nanoid';
好的

2022-04-28 10:05 UTC, bytemain approved these changes

2022-04-29 02:04 UTC, erha19 approved these changes

2022-04-29 02:04 UTC, merged