Fix: send custom request type
opensumi/core pull request #931
Opened 2022-04-28 08:13 UTC by kidswong999

#930

2022-04-28 08:23 UTC, erha19 commented
@kidswong999 感谢提交 ~ PR 需要根据我们的模板提交一下便于我们后面归档 [PULL_REQUEST_TEMPLATE](https://github.com/opensumi/core/blob/main/.github/PULL_REQUEST_TEMPLATE.md)

2022-04-28 08:25 UTC, erha19 requested changes

2022-04-28 08:25 UTC, erha19 commented on packages/debug/src/browser/debug-session-connection.ts
> +    return (await this.doSendRequest<T>(command, args)).body;
这里可能在 body 前面加个 `?` 合理一点，防止出现无 body 返回情况

2022-04-28 08:40 UTC, kidswong999 commented on packages/debug/src/browser/debug-session-connection.ts
> +    return (await this.doSendRequest<T>(command, args)).body;
添加了

2022-04-28 08:43 UTC, erha19 approved these changes
LGTM

2022-04-28 09:51 UTC, erha19 commented
@kidswong999 测试需要修一下，看一下这个测试  `debug/__tests__/browser/debug-session-connection.test.ts`,  测试的调试可以参考 [单元测试](https://opensumi.com/zh/docs/develop/how-to-contribute#%E5%8D%95%E5%85%83%E6%B5%8B%E8%AF%95)

2022-04-29 07:26 UTC, erha19 approved these changes

2022-04-29 07:27 UTC, merged