chore: simplify dependencies
opensumi/core pull request #979
Opened 2022-05-08 10:46 UTC by bytemain

### Types

- [x] 🧹 Chores

### Background or solution

### Changelog

2022-05-09 08:22 UTC, bytemain commented
使用 fse.move 替换掉了 mv 这个包，有一些表现改变了，但我觉得没啥关系：
比如这个 test: 
https://github.com/opensumi/core/pull/979/files#diff-cdc49641af2950ef06231493855cdd23601db43ac9be032793266da753a376c4

2022-05-09 10:01 UTC, erha19 requested changes

2022-05-09 10:01 UTC, erha19 commented on packages/core-node/src/fs/move.ts
> +  return fse.move(src, dest, options);
fs-extra 已经对 fs 包裹了一层了，这里再单独对一个方法做重载，感觉有点多余，我理解的合理情况是我们需要对某个方法的行为做特殊定制的时候才需要这个文件。

2022-05-09 14:57 UTC, erha19 commented on package.json
> +    "node-fetch": "^2",
这里为啥改成这种写法？直接写大版本的写法好像不太常见？

2022-05-09 14:57 UTC, erha19 commented on packages/components/package.json
> +    "rc-menu": "^9.3.2",
这里改成 '^' 的考虑是啥？看了一下上下几个类似依赖依旧保留了 `~` 的版本写法

2022-05-09 14:58 UTC, bytemain commented on package.json
> +    "node-fetch": "^2",
因为 ^3 以上就用 esm 了，^2 只是维护状态。当时懒得查最新版本就这样写了，下一个 pr 也统一一下请求库吧。

2022-05-13 02:03 UTC, erha19 commented
@bytemain 冲突处理一下，最好 rebase 一下 main

2022-05-16 08:39 UTC, erha19 approved these changes

2022-05-16 08:39 UTC, merged