fix: add missing data when use ApplicationError
opensumi/core pull request #997
Opened 2022-05-10 08:16 UTC by iamxukai

### Types
- [x] 🐛 Bug Fixes

### Background or solution
closes #779 
### Changelog
原来后端报错的时候，返回给前端的只有message和stack，所以前端不具有使用`FileSystemError`进行错误的信息判断的能力。
在使用了`FileSystemError`的时候，补充了相关属性。

2022-05-16 03:20 UTC, erha19 requested changes

2022-05-16 03:20 UTC, erha19 commented on packages/workspace-edit/src/browser/workspace-edit.service.ts
> +        if (err.cause && FileSystemError.FileNotFound.is(err.cause) && options.ignoreIfNotExists) {
感觉这种结构下面，对于每个 error 信息都要使用 `FileSystemError.xxx.is(err.cause)` 的结构去判断，感觉有点冗余，可以考虑把 `error.cause` 的结构放到 `is` 方法内做判断, 需要兼顾考虑一下后端直接使用 `FileSystemError.xxx.is(error)` 的用法

2022-05-16 03:57 UTC, iamxukai commented on packages/workspace-edit/src/browser/workspace-edit.service.ts
> +        if (err.cause && FileSystemError.FileNotFound.is(err.cause) && options.ignoreIfNotExists) {
> 感觉这种结构下面，对于每个 error 信息都要使用 `FileSystemError.xxx.is(err.cause)` 的结构去判断，感觉有点冗余，可以考虑把 `error.cause` 的结构放到 `is` 方法内做判断, 需要兼顾考虑一下后端直接使用 `FileSystemError.xxx.is(error)` 的用法

那么我直接把if的第一个判断去掉，因为`undefined` 不是 Impl 类的 实例，[application-error.ts](https://github.com/opensumi/core/blob/main/packages/core-common/src/application-error.ts#L48)。
我测试了下 `FileSystemError.xxx.is(undefined)`  返回为 `false` ，符合预期。

2022-05-17 02:51 UTC, erha19 commented
![image](https://user-images.githubusercontent.com/9823838/168718429-0bf5a89e-299f-4304-b26f-d990be945e72.png)

本地构建目前有这个报错，重跑了一下 CI 看一下什么情况 ..

2022-05-17 03:58 UTC, erha19 requested changes

2022-05-17 03:58 UTC, erha19 commented on packages/connection/src/common/proxy.ts
> +          applicationError: ApplicationError.is(e) ? e : null,
看了一下代码，这里不建议使用一个新定义的 `applicationError`, 原先使用 `error: boolean` 仅仅作为状态判断有点多余， 倒是可以把返回的 error 直接放到数据结构 `{error: Error, data: {}}` 里面的 error 上，即可以用于是否有错误信息的判断，也可以承接你这里的构造

2022-05-17 04:16 UTC, bytemain commented
> ![image](https://user-images.githubusercontent.com/9823838/168718429-0bf5a89e-299f-4304-b26f-d990be945e72.png)
> 
> 本地构建目前有这个报错，重跑了一下 CI 看一下什么情况 ..

error.cause 看起来是新版本的类型才有这个

2022-05-17 09:00 UTC, iamxukai commented on packages/connection/src/common/proxy.ts
> +          applicationError: ApplicationError.is(e) ? e : null,
@erha19 
按照建议改好了，那个`arg.cause`问题要怎么办呢？

2022-05-17 09:10 UTC, erha19 requested changes

2022-05-17 09:10 UTC, erha19 commented on packages/connection/src/common/proxy.ts
> +  error: ApplicationError<number, any> | null;
这里的类型有点问题，这里应该不止有 `ApplicationError | null`  还有普通的 error，建议可以用 `error?: ApplicationError<number, any> | Error;` , 下面没有 error 的情况直接移除掉整行。只留 data 就行了。

cause 构建的问题我再试试，可能升级一下 `@types/node` 可以解决这个问题

2022-05-17 09:37 UTC, erha19 commented on packages/connection/src/common/proxy.ts
> +  error: ApplicationError<number, any> | null;
改成 `error?: ApplicationError<number, any>` 吧，感觉可以

2022-05-18 07:24 UTC, erha19 approved these changes

2022-05-18 07:40 UTC, bytemain approved these changes

2022-05-18 10:16 UTC, merged